apache/struts

plugins/json/src/main/java/org/apache/struts2/json/JSONWriter.java
in hibernate4.3.7,because javassist3.18.1's class name generate rule is '_$$_jvst'+...
see WW-4449
=> change findBaseAccessor method

core/src/main/java/com/opensymphony/xwork2/DefaultActionProxyFactory.java
I needed to extend DefaultActionProxyFactory to return my own ActionInvocation, but I had to override all of createActionProxy() to do so.  Seems like a safe change to break out the ActionInvocation creation to make it easier to just override that piece.
=> Make it easier to extend to use own ActionInvocation

core/src/main/java/com/opensymphony/xwork2/DefaultActionInvocation.java
Just as createAction is split out from init, it would be great to split out creating the interceptor iterator creation so it can be overridden without having to override all of init().  (Needed this to always prepend an i18n interceptor to all stacks).
=> Make it easier to extend to override interceptor stack

core/src/main/java/org/apache/struts2/components/Form.java, core/src/test/java/org/apache/struts2/TestAction.java, core/src/test/java/org/apache/struts2/components/FormTest.java
WW-4139 removed method name from getValidators call.  While this works
fine for a case mentioned in that ticket it fails to account for a case
when
dynamicMethodCalls and validateAnnotatedMethodOnly are used. Without
method name actionValidatorManager.getValidators returns all validators
defined for a given field.
Expected behavior for dynamicMethodCalls with
validateAnnotatedMethodOnly case is to return validators for a given
field defined at the method level.
=> Form.getValidators does not respect validateAnnotatedMethodOnly flag

core/src/main/java/com/opensymphony/xwork2/util/CompoundRoot.java
NPE/ concurrent modification exception
using a CopyOnWriteArrayList. This is to keep Memory consistency on the
ValueStack.
=> fix for WW-4573

plugins/rest/src/test/java/org/apache/struts2/rest/DefaultHttpHeadersTest.java
In DefaultHttpHeadersTest.java some tests fail when somebody's timezone is not GMT. So I add codes using GMT date format and US locale to ensure tests pass in anywhere.
=> make test passed for people not using GMT.

plugins/jasperreports/src/main/java/org/apache/struts2/views/jasperreports/ValueStackDataSource.java
patch ww-3266
getFieldValue() method of ValueStackDataSource uses getDescription() to get field value may not appropriate.
Reason:
In JasperReports, a description of a field is just like a documentation for this field. So it may not good to use it as expression
=> patch ww-3266 getFieldValue() method of ValueStackDataSource uses getDescription() to get field value may not appropriate.

apps/showcase/src/main/java/org/apache/struts2/showcase/validation/AjaxFormSubmitAction.java, apps/showcase/src/main/java/org/apache/struts2/showcase/validation/AjaxFormSubmitSuccessAction.java, apps/showcase/src/main/resources/struts-validation.xml, apps/showcase/src/main/resources/template/ajaxErrorContainers/actionerror.ftl, apps/showcase/src/main/resources/template/ajaxErrorContainers/controlfooter.ftl, apps/showcase/src/main/resources/template/ajaxErrorContainers/controlheader-core.ftl, apps/showcase/src/main/resources/template/ajaxErrorContainers/theme.properties, apps/showcase/src/main/webapp/WEB-INF/decorators/main.jsp, apps/showcase/src/main/webapp/WEB-INF/validation/ajaxFormSubmit.jsp, apps/showcase/src/main/webapp/WEB-INF/validation/ajaxFormSubmitSuccess.jsp, plugins/json/src/main/java/org/apache/struts2/json/JSONActionRedirectResult.java, plugins/json/src/main/java/org/apache/struts2/json/JSONValidationInterceptor.java, plugins/json/src/main/resources/struts-plugin.xml, plugins/json/src/test/java/org/apache/struts2/json/JSONActionRedirectResultTest.java
Adds new result 'JSONActionRedirectResult' to json-plugin. Contains tests and example in showcase app. The new result type is intended to be used along with existing JSONValidationInterceptor. It makes it possible to do form validation via ajax and handle form submitting, action execution and redirect evaluation all in one request inside JS context.
The sample Action is called `AjaxFormSubmitAction`. That example is by far longer that the change to json-plugin itself (not just that action class but other files that it requires). Here is an excerpt of it's javadoc, that shows what can be done with the new result:
* Depends on `json-plugin`.
* Requires `jsonValidationInterceptor` to be on stack.
* Uses a special json redirect result type.
* Uses http parameters …
=> New result 'JSONActionRedirectResult' in json-plugin

plugins/rest/src/main/java/org/apache/struts2/rest/RestActionMapper.java, plugins/rest/src/test/java/org/apache/struts2/rest/RestActionMapperTest.java
Lukasz,
here is a proposed fix for WW-4589.  This makes sure a url specified method name is not overwritten by an implied method name.  It passes the unit tests that I have added
=> WW-4589 do not overwrite explicit method name

core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java
HI Lukasz,
This is a proposal to fix WW-4456 - Got NPE when File Upload Limitation exceeds in portal env.
We should catch in any case a FileUploadException, then try to cast down if we want any info about the exception. Valid subtype of FileUploadException:
InvalidContentTypeException
IOFileUploadException
SizeLimitExceededException
FileSizeLimitExceededException
I couldn't get the complete test on a running test env, because I had issues getting the logging to work.
But it seems to works.
=> WW-4456 Got NPE when File Upload Limitation exceeds in portal env

core/src/main/java/com/opensymphony/xwork2/config/providers/XmlConfigurationProvider.java, core/src/test/java/com/opensymphony/xwork2/config/providers/XmlConfigurationProviderResultsTest.java, core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-result-names.xml, plugins/convention/src/main/java/org/apache/struts2/convention/DefaultResultMapBuilder.java, plugins/convention/src/main/java/org/apache/struts2/convention/annotation/Result.java, plugins/convention/src/test/java/org/apache/struts2/convention/DefaultResultMapBuilderTest.java, plugins/convention/src/test/java/org/apache/struts2/convention/PackageBasedActionConfigBuilderTest.java, plugins/convention/src/test/java/org/apache/struts2/convention/actions/result/ActionLevelResultsNamesAction.java
Allow to use multiple values in `result` tag `name` attribute and in `Result` annotation `name`.
So this typical configuration:
```
<action name="save">
<result>success.jsp</result>
<result name="error">input-form.jsp</result>
<result name="input">input-form.jsp</result>
</action>
```
Can be shorten to that:
```
<action name="save">
<result>success.jsp</result>
<result name="error, input">input-form.jsp</result>
</action>
```
And this annotations:
```
@Action(results = {
@Result(name="error", location="input-form.jsp"),
@Result(name="input", location="input-form.jsp"),
@Result(name="success", location="success.jsp")
})
```
To that:
```
@Action(results = {
@Result(name="error, input", location="input-form.jsp"),
@Result(name="success", location="success.jsp")
})
```
=> WW-4590 - Allow to use multiple names in result

plugins/javatemplates/src/main/java/org/apache/struts2/views/java/simple/TextFieldHandler.java
=> Allow html5 attributes

core/src/main/java/org/apache/struts2/dispatcher/PrepareOperations.java
Now StrutsPrepareFilter set the ServletActionContext with the proper MultiPartRequestWrapper (or StrutsRequestWrapper)
=>     WW-4610  ServletActionContext.getRequest() doesn't return the MultiPartRequestWrapper (or StrutsRequestWrapper) when using StrutsPrepareFilter

core/src/main/java/com/opensymphony/xwork2/util/LocalizedTextUtil.java
Defend NPE if not ValueStack presented, for example non-struts request like static util method or backend thread.
reopen #35
=> Improve LocalizedTextUtil.getMessage() defend NPE

core/src/main/java/com/opensymphony/xwork2/config/entities/PackageConfig.java, plugins/convention/src/main/java/org/apache/struts2/convention/ConventionUnknownHandler.java
Prior to strict-method-invocation, the convention plugin would allow for executing results (JSP) without an associated Action via the ConventionUnknownHandler.handleUnknownAction method.  This continues to work with SMI disabled but when enabled the allowedMethods list in the ActionConfig does not get populated which causes a 404.  There was already a member Set hard coded to the most common methods to which I added "index" used by the REST plugin.  
Ideally, line 224 would use the globalAllowedMethods set from the PackageConfig instead of a hard coded list but there is currently no associated getter method and I figured it would be better to discuss adding that functionality via the PR.
=> add allowed methods to handleUnknownAction

core/src/main/java/com/opensymphony/xwork2/interceptor/DefaultWorkflowInterceptor.java
To make it clear that the behavior is not limited to validation errors, but also extendend to conversion errors and (most important) to action errors, that will be stored and retrieved by the Message Store Interceptor during a redirection, and that will generate an undesired result.
=> Change to the documentation

core/src/main/resources/template/css_xhtml/checkbox.ftl
Fix freemaker error when set label position to left on a checkbox tag of a form (Missing brackets).
=> Fix freemaker error in checkbox.ftl of css_xhtml template 

core/src/main/java/com/opensymphony/xwork2/interceptor/ConversionErrorInterceptor.java, core/src/main/java/org/apache/struts2/util/URLDecoderUtil.java, core/src/main/java/org/apache/struts2/views/util/DefaultUrlHelper.java, core/src/test/java/com/opensymphony/xwork2/interceptor/ConversionErrorInterceptorTest.java, core/src/test/java/org/apache/struts2/util/URLDecoderUtilTest.java, core/src/test/java/org/apache/struts2/views/util/DefaultUrlHelperTest.java
=> ConversionErrorInterceptor to extend MethodFilterIntercept

core/src/main/java/org/apache/struts2/dispatcher/LocalizedMessage.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/MultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/MultiPartRequestWrapper.java, core/src/main/java/org/apache/struts2/interceptor/FileUploadInterceptor.java, core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java, plugins/pell-multipart/src/main/java/org/apache/struts2/dispatcher/multipart/PellMultiPartRequest.java
=> WW-4636 - File upload error message always in default language

core/src/main/java/com/opensymphony/xwork2/interceptor/DefaultWorkflowInterceptor.java, core/src/main/java/com/opensymphony/xwork2/util/AnnotationUtils.java, core/src/test/java/com/opensymphony/xwork2/util/AnnotationUtilsTest.java, core/src/test/java/com/opensymphony/xwork2/util/annotation/DummyClass.java, core/src/test/java/com/opensymphony/xwork2/util/annotation/DummyClassExt.java, core/src/test/java/com/opensymphony/xwork2/util/annotation/DummyInterface.java, core/src/test/java/com/opensymphony/xwork2/util/annotation/MyAnnotationI.java
With these changes, [AnnotationUtils](https://github.com/apache/struts/blob/master/core/src/main/java/com/opensymphony/xwork2/util/AnnotationUtils.java) can navigate around proxies, superclasses and interfaces.
known issue: for keep it simple, currently it does not support [Bridge Methods](https://docs.oracle.com/javase/tutorial/java/generics/bridgeMethods.html).
=> [WW-4694] annotation processing improved

core/src/main/java/com/opensymphony/xwork2/interceptor/ChainingInterceptor.java, core/src/test/java/com/opensymphony/xwork2/interceptor/ChainingInterceptorTest.java, core/src/test/java/com/opensymphony/xwork2/interceptor/ChainingInterceptorWithConfigTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java
With these changes, they will be handled as comma separated String like what ParameterFilterInterceptor do.
=> [WW-4528] handling ChainingInterceptor excludes and includes lists

core/src/main/java/com/opensymphony/xwork2/ActionSupport.java, core/src/main/java/com/opensymphony/xwork2/DefaultLocaleProvider.java, core/src/main/java/com/opensymphony/xwork2/DefaultLocaleProviderFactory.java, core/src/main/java/com/opensymphony/xwork2/LocaleProviderFactory.java, core/src/main/java/com/opensymphony/xwork2/TextProviderFactory.java, core/src/main/java/com/opensymphony/xwork2/TextProviderSupport.java, core/src/main/java/com/opensymphony/xwork2/config/impl/DefaultConfiguration.java, core/src/main/java/com/opensymphony/xwork2/config/providers/XWorkConfigurationProvider.java, core/src/main/java/com/opensymphony/xwork2/conversion/impl/DefaultTypeConverter.java, core/src/main/java/com/opensymphony/xwork2/validator/DelegatingValidatorContext.java, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/main/java/org/apache/struts2/components/I18n.java, core/src/main/java/org/apache/struts2/config/DefaultBeanSelectionProvider.java, core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java, core/src/main/java/org/apache/struts2/interceptor/FileUploadInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/I18nInterceptor.java, core/src/main/resources/struts-default.xml, core/src/test/java/org/apache/struts2/interceptor/I18nInterceptorTest.java, plugins/tiles/src/main/java/org/apache/struts2/tiles/StrutsTilesLocaleResolver.java
Replaces injectable `LocaleProvider` with `LocaleProviderFactory` to avoid problems with multiple beans implementing the `LocaleProvider` interface.
Implements [WW-4757](https://issues.apache.org/jira/browse/WW-4757)
=> WW-4757: LocaleProvider factory

core/src/main/java/com/opensymphony/xwork2/conversion/TypeConverterCreator.java, core/src/main/java/com/opensymphony/xwork2/conversion/annotations/TypeConversion.java, core/src/main/java/com/opensymphony/xwork2/conversion/impl/DefaultConversionAnnotationProcessor.java, core/src/main/java/com/opensymphony/xwork2/conversion/impl/DefaultTypeConverterCreator.java, core/src/main/java/com/opensymphony/xwork2/conversion/impl/XWorkConverter.java, core/src/test/java/com/opensymphony/xwork2/conversion/ConversionTestAction.java, core/src/test/java/com/opensymphony/xwork2/test/AnnotationDataAware.java, core/src/test/java/com/opensymphony/xwork2/test/AnnotationTestBean2.java, core/src/test/java/com/opensymphony/xwork2/test/AnnotationUser.java, core/src/test/java/com/opensymphony/xwork2/test/annotations/PersonAction.java, core/src/test/java/com/opensymphony/xwork2/util/AnnotatedCat.java
This PR extends existing `TypeConversion` annotation to allow define converters as a class instead of a raw string.
Implements [WW-4210](https://issues.apache.org/jira/browse/WW-4210)
=> WW-4210: Type conversion class

core/src/main/java/com/opensymphony/xwork2/validator/AnnotationValidationConfigurationBuilder.java, core/src/main/java/com/opensymphony/xwork2/validator/annotations/CreditCardValidator.java, core/src/main/java/com/opensymphony/xwork2/validator/annotations/Validations.java, core/src/main/java/com/opensymphony/xwork2/validator/validators/CreditCardValidator.java, core/src/main/java/com/opensymphony/xwork2/validator/validators/RegexFieldValidator.java, core/src/main/resources/template/xhtml/form-close-validate.ftl, core/src/test/java/com/opensymphony/xwork2/validator/AnnotationValidationAction.java, core/src/test/java/com/opensymphony/xwork2/validator/AnnotationValidationConfigurationBuilderTest.java, core/src/test/java/com/opensymphony/xwork2/validator/validators/CreditCardValidatorTest.java, core/src/test/resources/org/apache/struts2/views/jsp/ui/Formtag-2.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/Formtag-22.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/Formtag-24.txt, core/src/test/resources/validators.xml
Implements a credit card validator
[WW-3952](https://issues.apache.org/jira/browse/WW-3952)
=> WW-3952: Credit card validator

core/src/main/java/org/apache/struts2/views/freemarker/FreemarkerResult.java, core/src/test/java/org/apache/struts2/views/freemarker/FreeMarkerResultTest.java
Implements [WW-4749](https://issues.apache.org/jira/browse/WW-4749)
=> WW-4749: Buffer/Flush behaviour in FreemarkerResult

core/src/main/java/com/opensymphony/xwork2/conversion/impl/NumberConverter.java, core/src/main/java/com/opensymphony/xwork2/conversion/impl/StringConverter.java, core/src/test/java/com/opensymphony/xwork2/conversion/impl/NumberConverterTest.java, core/src/test/java/com/opensymphony/xwork2/conversion/impl/StringConverterTest.java, core/src/test/java/com/opensymphony/xwork2/conversion/impl/XWorkConverterTest.java, core/src/test/java/com/opensymphony/xwork2/validator/DoubleRangeFieldValidatorTest.java, core/src/test/resources/org/apache/struts2/views/jsp/ui/Select-3.txt
This PR introduces Locale aware conversion of `BigDecimal` and `Double` and `Double`
[WW-3171](https://issues.apache.org/jira/browse/WW-3171)
[WW-3650](https://issues.apache.org/jira/browse/WW-3650)
[WW-4581](https://issues.apache.org/jira/browse/WW-4581)
=> WW-3171 WW-3650 WW-4581: Locale aware converters

core/src/main/java/com/opensymphony/xwork2/interceptor/ChainingInterceptor.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlReflectionProvider.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/util/ProxyUtil.java, core/src/main/java/com/opensymphony/xwork2/util/reflection/ReflectionProvider.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java, core/src/test/java/com/opensymphony/xwork2/spring/ActionsFromSpringTest.java, core/src/test/java/com/opensymphony/xwork2/spring/SpringProxyUtilTest.java, core/src/test/java/com/opensymphony/xwork2/spring/TestAspect.java, core/src/test/resources/com/opensymphony/xwork2/spring/actionContext-spring.xml
These fix some bugs in my previous PR, #135 which passes the unwrapped object of the proxied action to the `reflectionProvider.copy`, then we miss aspects executions which are implemented inside the proxied object rather than the unwrapped one.
Also fix some bugs in unit tests of my previous PR and improves them.
=> WW-4800 Executes aspects when chaining AOPed actions

core/src/main/java/com/opensymphony/xwork2/interceptor/ChainingInterceptor.java, core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/main/java/com/opensymphony/xwork2/util/ProxyUtil.java, core/src/test/java/com/opensymphony/xwork2/spring/ActionsFromSpringTest.java, core/src/test/java/com/opensymphony/xwork2/spring/SpringProxyUtilTest.java, core/src/test/java/com/opensymphony/xwork2/spring/TestAspect.java, core/src/test/resources/com/opensymphony/xwork2/spring/actionContext-xwork.xml
Fixes what I sent to security@struts.apache.org (3/15/2017)
=> WW-4805 Blocks ognl access to class members of Spring proxy

plugins/jasperreports/src/main/java/org/apache/struts2/views/jasperreports/ValueStackDataSource.java
Deletes wrong `!` from `wrapField`'s where clause.
=> WW-4794 Fixes wrapField's where clause

plugins/convention/src/main/java/org/apache/struts2/convention/AbstractActionNameBuilder.java, plugins/convention/src/main/java/org/apache/struts2/convention/ActionConfigBuilder.java, plugins/convention/src/main/java/org/apache/struts2/convention/ActionNameBuilder.java, plugins/convention/src/main/java/org/apache/struts2/convention/ClasspathConfigurationProvider.java, plugins/convention/src/main/java/org/apache/struts2/convention/ClasspathPackageProvider.java, plugins/convention/src/main/java/org/apache/struts2/convention/ConventionConstants.java, plugins/convention/src/main/java/org/apache/struts2/convention/ConventionUnknownHandler.java, plugins/convention/src/main/java/org/apache/struts2/convention/ConventionsService.java, plugins/convention/src/main/java/org/apache/struts2/convention/ConventionsServiceImpl.java, plugins/convention/src/main/java/org/apache/struts2/convention/DefaultActionNameBuilder.java, plugins/convention/src/main/java/org/apache/struts2/convention/DefaultClassFinder.java, plugins/convention/src/main/java/org/apache/struts2/convention/DefaultInterceptorMapBuilder.java, plugins/convention/src/main/java/org/apache/struts2/convention/DefaultResultMapBuilder.java, plugins/convention/src/main/java/org/apache/struts2/convention/InterceptorMapBuilder.java, plugins/convention/src/main/java/org/apache/struts2/convention/PackageBasedActionConfigBuilder.java, plugins/convention/src/main/java/org/apache/struts2/convention/ReflectionTools.java, plugins/convention/src/main/java/org/apache/struts2/convention/ResultMapBuilder.java, plugins/convention/src/main/java/org/apache/struts2/convention/SEOActionNameBuilder.java, plugins/convention/src/main/java/org/apache/struts2/convention/StringTools.java
Implements multiple Action suffixes in the Convention Plugin, right now you can define suffixes as follow
```xml
<constant name="struts.convention.action.suffix" value="Action,Controller,Endpoint"/>
```
[WW-4808](https://issues.apache.org/jira/browse/WW-4808)
=> WW-4808: Multiple suffixes

core/src/main/java/com/opensymphony/xwork2/ObjectFactory.java, core/src/main/java/com/opensymphony/xwork2/spring/SpringObjectFactory.java, core/src/main/java/com/opensymphony/xwork2/spring/SpringProxyableObjectFactory.java, core/src/main/java/com/opensymphony/xwork2/spring/interceptor/ActionAutowiringInterceptor.java, core/src/test/java/com/opensymphony/xwork2/ProxyObjectFactory.java, core/src/test/java/com/opensymphony/xwork2/interceptor/ScopedModelDrivenInterceptorTest.java, core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java, plugins/cdi/src/main/java/org/apache/struts2/cdi/CdiObjectFactory.java, plugins/cdi/src/test/java/org/apache/struts2/cdi/CdiObjectFactoryTest.java, plugins/convention/src/test/java/org/apache/struts2/convention/PackageBasedActionConfigBuilderTest.java, plugins/osgi/src/main/java/org/apache/struts2/osgi/DelegatingObjectFactory.java, plugins/osgi/src/main/java/org/apache/struts2/osgi/SpringOsgiObjectFactory.java, plugins/plexus/src/main/java/org/apache/struts2/plexus/PlexusObjectFactory.java, plugins/spring/src/main/java/org/apache/struts2/spring/StrutsSpringObjectFactory.java
Inject `Container` in constructor of the `ObjectFactory`.
Can someone test `cdi`, `osgi` and `plexus` plugins.
Better ideas how to fix the issue are welcome. :)
=> WW-4827 Not fully initialized ObjectFactory tries to create beans

plugins/rest/src/main/java/org/apache/struts2/rest/ContentTypeHandlerManager.java, plugins/rest/src/main/java/org/apache/struts2/rest/ContentTypeInterceptor.java, plugins/rest/src/main/java/org/apache/struts2/rest/DefaultContentTypeHandlerManager.java, plugins/rest/src/main/java/org/apache/struts2/rest/RestActionInvocation.java, plugins/rest/src/main/java/org/apache/struts2/rest/RestWorkflowInterceptor.java, plugins/rest/src/main/java/org/apache/struts2/rest/handler/AbstractContentTypeHandler.java, plugins/rest/src/main/java/org/apache/struts2/rest/handler/ContentTypeHandler.java, plugins/rest/src/main/java/org/apache/struts2/rest/handler/FormUrlEncodedHandler.java, plugins/rest/src/main/java/org/apache/struts2/rest/handler/HtmlHandler.java, plugins/rest/src/main/java/org/apache/struts2/rest/handler/JacksonLibHandler.java, plugins/rest/src/main/java/org/apache/struts2/rest/handler/JsonLibHandler.java, plugins/rest/src/main/java/org/apache/struts2/rest/handler/MultipartFormDataHandler.java, plugins/rest/src/test/java/org/apache/struts2/rest/ContentTypeHandlerManagerTest.java, plugins/rest/src/test/java/org/apache/struts2/rest/DefaultContentTypeHandlerManagerTest.java, plugins/rest/src/test/java/org/apache/struts2/rest/RestWorkflowInterceptorTest.java, plugins/rest/src/test/java/org/apache/struts2/rest/handler/JacksonLibHandlerTest.java, plugins/rest/src/test/java/org/apache/struts2/rest/handler/JsonLibHandlerTest.java
This PR changes API a bit to allow pass current `ActionInvocation` to the REST content type handlers to allow implement different behaviour based on a current action.
[WW-4835](https://issues.apache.org/jira/browse/WW-4835)
=> WW-4835: Configurable handlers

core/src/test/java/org/apache/struts2/views/jsp/ui/SelectTest.java
[WW-4840](https://issues.apache.org/jira/browse/WW-4840) Build Fails Due to Unused com.sun Import
=> WW-4840 Build Fails Due to Unused com.sun Import

plugins/portlet/src/main/java/org/apache/struts2/portlet/servlet/PortletServletRequest.java
multipart validation added to Dispatcher in WW-4768 and JakartaMultiPartRequest in WW-4767 can't be passed within a portlet since PortletServletRequest.getMethod() only returns null
=> return request HTTP method to fix problem for portlets with multipart validation

core/src/test/java/org/apache/struts2/views/freemarker/FreemarkerResultMockedTest.java
At commit e262854e2a1b7548efa0a1eb50d350ecd215231b the project switch from JDK1.5 to JDK1.7 . At commit f0797388bc220b48c720e0fb29d42d4f58243757, line 104/109, expectedJDK{15,16} was changed to expectedJDK{17,18}. However, the corresponding TODO comment was not changed. 
We should remove this obsolete comment.
=> remove an obsolete TODO comment

core/src/main/java/org/apache/struts2/components/Text.java, core/src/main/java/org/apache/struts2/views/jsp/PropertyTag.java, core/src/main/java/org/apache/struts2/views/jsp/TextTag.java, core/src/site/resources/tags/text.html, core/src/test/java/org/apache/struts2/views/jsp/TextTagTest.java, core/src/test/resources/org/apache/struts2/TestAction.properties
Added the option of escaping the result of an `<s:text>` tag.
Defaults set to not escaping in order not to break current behavior.
possible improvement:
* now holds duplicate prepare method from the `Property` class
=> WW-4888 add escaping possibilities to text-tag

.travis.yml, README.md, pom.xml
Some small tweaks to be better visible via GitHub
Coverage report is available here
https://coveralls.io/github/apache/struts
[![Coverage Status](https://coveralls.io/repos/github/apache/struts/badge.svg?branch=pimp-my-struts)](https://coveralls.io/github/apache/struts?branch=pimp-my-struts)
=> Pimp my struts

plugins/rest/pom.xml, plugins/rest/src/main/java/org/apache/struts2/rest/handler/JsonLibHandler.java, plugins/rest/src/main/resources/struts-plugin.xml, pom.xml
Implements [WW-4892](https://issues.apache.org/jira/browse/WW-4892)
Closes [WW-4893](https://issues.apache.org/jira/browse/WW-4893)
=> WW-4892 WW-4893: Use Jackson to handle JSON request

core/src/main/java/com/opensymphony/xwork2/config/impl/AbstractMatcher.java, core/src/main/java/com/opensymphony/xwork2/config/impl/ActionConfigMatcher.java, core/src/main/java/com/opensymphony/xwork2/config/impl/DefaultConfiguration.java, core/src/main/java/com/opensymphony/xwork2/config/providers/InterceptorBuilder.java, core/src/main/java/com/opensymphony/xwork2/conversion/impl/XWorkConverter.java, core/src/main/java/com/opensymphony/xwork2/interceptor/ParameterFilterInterceptor.java, core/src/main/java/com/opensymphony/xwork2/interceptor/ParametersInterceptor.java, core/src/main/java/org/apache/struts2/components/UIBean.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java, core/src/main/java/org/apache/struts2/interceptor/CheckboxInterceptor.java, core/src/main/java/org/apache/struts2/result/PostbackResult.java, core/src/main/java/org/apache/struts2/views/freemarker/FreemarkerManager.java, plugins/convention/src/main/java/org/apache/struts2/convention/PackageBasedActionConfigBuilder.java, plugins/javatemplates/src/main/java/org/apache/struts2/views/java/XHTMLTagSerializer.java, plugins/json/src/main/java/org/apache/struts2/json/JSONCleaner.java, plugins/osgi/src/main/java/org/apache/struts2/osgi/host/BaseOsgiHost.java, plugins/portlet/src/main/java/org/apache/struts2/portlet/util/PortletUrlHelper.java, plugins/tiles/src/main/java/org/apache/struts2/tiles/StrutsWildcardServletApplicationContext.java
Changed iterations over the keySet of Maps when the values were (also) used.
Sonar build 
* see: [Iterate over the "entrySet" instead of the "keySet"](https://builds.apache.org/analysis/issues/search#resolved=false|rules=squid%3AS2864|projectUuids=AVkMC6uolrNkgx9HJrOf)
I did not change 1 of the warnings, because i think the code could throw a  `ConcurrentModificationException`
* see: [CheckboxInterceptor.java#L63-L80](https://github.com/apache/struts/blob/master/core/src/main/java/org/apache/struts2/interceptor/CheckboxInterceptor.java#L63-L80)
=> changed Map iterations to use entrySet when both key and value are used

core/src/main/java/org/apache/struts2/interceptor/BackgroundProcess.java, core/src/main/java/org/apache/struts2/interceptor/ExecuteAndWaitInterceptor.java, core/src/test/java/org/apache/struts2/interceptor/BackgroundProcessTest.java, core/src/test/java/org/apache/struts2/interceptor/ExecuteAndWaitInterceptorTest.java
Currently we won't support exec and wait from de-serialized session and maybe add this support some day on user demand. Why I think to drop such support? It's not a good practice to try serializing such large or variant unpredictable objects like action and invocation ([CWE-579: J2EE Bad Practices: Non-serializable Object Stored in Session](https://cwe.mitre.org/data/definitions/579.html)).
=> WW-4900 Makes BackgroundProcess transient

core/src/main/java/com/opensymphony/xwork2/ActionInvocation.java, core/src/main/java/com/opensymphony/xwork2/DefaultActionInvocation.java, core/src/main/java/com/opensymphony/xwork2/mock/MockActionInvocation.java, core/src/main/java/org/apache/struts2/util/InvocationSessionStore.java, core/src/test/java/com/opensymphony/xwork2/DefaultActionInvocationTest.java, core/src/test/java/com/opensymphony/xwork2/spring/interceptor/TestActionInvocation.java, core/src/test/java/org/apache/struts2/util/InvocationSessionStoreTest.java, plugins/dwr/src/main/java/org/apache/struts2/validators/DWRValidator.java, plugins/json/src/test/java/org/apache/struts2/json/JSONInterceptorTest.java, plugins/rest/src/main/java/org/apache/struts2/rest/RestActionInvocation.java, plugins/sitemesh/src/main/java/org/apache/struts2/sitemesh/OldDecorator2NewStrutsDecorator.java
⚠️  For simpler review, please review each commit separately.
❓ Why `serialize` and `deserialize` methods of `ActionInvocation` deleted? `ActionInvocation` is a large complex object which contains request, response, container, value stack and action context. It's hard to maintain it serializable e.g. user may want to store a private not serializable object in action. And It's not a good practice ([CWE-579: J2EE Bad Practices: Non-serializable Object Stored in Session](https://cwe.mitre.org/data/definitions/579.html)).
ℹ️ I know I also deleted `that.container = actionContext.getContainer();` (replacing restored invocation container with current container) with `ActionInvocation.deserialize` method. I saw it's not needed and even it's better for restored default invocation to work with …
=> WW-4873 Makes ActionInvocation not serializable and InvocationSessionStore$InvocationContext transient

core/src/main/java/com/opensymphony/xwork2/config/entities/AllowedMethods.java, core/src/main/java/com/opensymphony/xwork2/util/GlobalLocalizedTextProvider.java, core/src/main/java/com/opensymphony/xwork2/util/StrutsLocalizedTextProvider.java, core/src/main/java/com/opensymphony/xwork2/util/finder/ClassFinder.java, core/src/main/java/org/apache/struts2/components/ServletUrlRenderer.java, core/src/main/java/org/apache/struts2/components/template/BaseTemplateEngine.java, core/src/main/java/org/apache/struts2/dispatcher/mapper/DefaultActionMapper.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java, core/src/main/java/org/apache/struts2/result/ServletDispatcherResult.java, core/src/main/java/org/apache/struts2/result/ServletRedirectResult.java, core/src/main/java/org/apache/struts2/views/jsp/TagUtils.java, core/src/main/java/org/apache/struts2/views/velocity/components/AbstractDirective.java
Fixes sonar reported issue about single character strings being used inside the struts2 core module.
Sonar reported issue:
[Sonar - char instead of string](https://builds.apache.org/analysis/issues/search#resolved=false|tags=performance|rules=squid%3AS3027|projectUuids=AVkMC6uolrNkgx9HJrOf|moduleUuids=AVkMC7FC5zvJuQXqiyMz)
=> used char instead of a single character string

core/src/main/java/org/apache/struts2/components/Anchor.java, core/src/main/java/org/apache/struts2/components/UIBean.java, core/src/main/java/org/apache/struts2/components/UrlRenderer.java, core/src/test/java/org/apache/struts2/components/UIBeanTest.java
- made some minor formatting changes concerning:
- mixed tabs and spaces
- add curly brackets around single line conditional statements
- added some missing ´@Override´ annotations
=> Minor Formatting changes

plugins/bean-validation/src/main/java/org/apache/struts/beanvalidation/constraints/ValidateGroup.java, plugins/bean-validation/src/main/java/org/apache/struts/beanvalidation/constraints/ValidationGroup.java, plugins/bean-validation/src/main/java/org/apache/struts/beanvalidation/validation/interceptor/BeanValidationInterceptor.java, plugins/bean-validation/src/test/java/org/apache/struts/beanvalidation/BeanValidationInterceptorTest.java, plugins/bean-validation/src/test/java/org/apache/struts/beanvalidation/actions/ValidateGroupAction.java, plugins/bean-validation/src/test/java/org/apache/struts/beanvalidation/models/Person.java, plugins/bean-validation/src/test/resources/bean-validation-test.xml
it would be nice Feature if BeanValidation-Plugin would support 'Grouping Constraints'
https://docs.jboss.org/hibernate/validator/5.1/reference/en-US/html/chapter-groups.html
Hedju Hor
Implements [WW-4907](https://issues.apache.org/jira/browse/WW-4907)
=> WW-4907 support JSR 303 Validation Groups in BeanValidation-Plugin

apps/showcase/src/main/java/org/apache/struts2/showcase/tag/nonui/debugtag/DebugTagAction.java, apps/showcase/src/main/resources/struts-tags-non-ui.xml, apps/showcase/src/main/webapp/WEB-INF/tags/non-ui/debug.jsp, core/src/main/java/org/apache/struts2/components/Debug.java, core/src/test/java/org/apache/struts2/views/jsp/ui/DebugTagTest.java
one solution
if a user really wants to show the Debug Flag on his production release, he can use  `<s:debug disabled="false"/>`
got another solution 17b598433db28681344b65d10436ccac5f1fff54
this will solve the problem with client/server side control
=> WW-4891 Debug tag should not display anything when not in dev mode

core/src/test/java/com/opensymphony/xwork2/DefaultUnknownHandlerManagerTest.java
This is a very trivial test dedicated for the DefaultUnknownHandlerManager. 
I'm doing some research that includes Apache Struts as an example. Most of the classes I'm interested in have sufficient tests. However, even though DefaultUnknownHandlerManager is tested through other tests created for other classes, those tests are not sufficient enough for my purpose. I'm pushing the given test for DefaultUnknownHandlerManager to confirm that it is acceptable by you.
=> Initial test dedicated for the DefaultUnknownHandlerManager

core/src/main/java/org/apache/struts2/interceptor/I18nInterceptor.java, core/src/test/java/org/apache/struts2/interceptor/I18nInterceptorTest.java
Resolves [WW-4741](https://issues.apache.org/jira/browse/WW-4741)
=> WW-4741: Do not create session

core/src/main/java/com/opensymphony/xwork2/FileManager.java, core/src/main/java/com/opensymphony/xwork2/util/fs/JarEntryRevision.java, core/src/main/java/com/opensymphony/xwork2/util/fs/StrutsJarURLConnection.java, core/src/test/java/com/opensymphony/xwork2/util/fs/JarEntryRevisionTest.java
I inspired such fix from Spring Framework when I found it during my research at [here](https://github.com/spring-projects/spring-framework/blob/8d3264f680018ccbec6a40253b477283aa3a7e6e/spring-core/src/main/java/org/springframework/util/ResourceUtils.java#L316).
Oracle WebLogic may report jar urls like "zip:C:/web-app-lib-path/some-jar.jar" but JDK's JarURLConnection#parseSpecs breaks on such urls.
While JDK's JarURLConnection#parseSpecs is private then I had to extend URLConnection instead.
Struts keeps a reference of all loaded files regardless of `devMode` or `struts.configuration.xml.reload` values (i.e. user may get a warning exception if framework was not able to create a revision for loaded file). But Struts checks if reload is needed only when `struts.configuration.xml.reload` …
=> WW-4920 fix java.net.JarURLConnection#parseSpecs

apps/showcase/src/main/java/org/apache/struts2/showcase/model/Skill.java, core/pom.xml, core/src/main/java/com/opensymphony/xwork2/DefaultActionProxy.java, core/src/main/java/com/opensymphony/xwork2/config/providers/EnvsValueSubstitutor.java, core/src/main/java/com/opensymphony/xwork2/interceptor/ConversionErrorInterceptor.java, core/src/main/java/com/opensymphony/xwork2/validator/validators/RepopulateConversionErrorFieldValidatorSupport.java, core/src/main/java/org/apache/struts2/components/Property.java, core/src/main/java/org/apache/struts2/components/Text.java, core/src/main/java/org/apache/struts2/dispatcher/Parameter.java, core/src/main/java/org/apache/struts2/util/TextProviderHelper.java, core/src/main/java/org/apache/struts2/views/util/DefaultUrlHelper.java, plugins/config-browser/src/main/java/org/apache/struts2/config_browser/ActionNamesAction.java, plugins/config-browser/src/main/java/org/apache/struts2/config_browser/ShowConfigAction.java, plugins/javatemplates/pom.xml, plugins/javatemplates/src/main/java/org/apache/struts2/views/java/Attributes.java, plugins/javatemplates/src/main/java/org/apache/struts2/views/java/XHTMLTagSerializer.java, plugins/javatemplates/src/main/java/org/apache/struts2/views/java/simple/CheckboxHandler.java, plugins/javatemplates/src/main/java/org/apache/struts2/views/java/simple/CheckboxListHandler.java, plugins/json/pom.xml, plugins/json/src/main/java/org/apache/struts2/json/JSONValidationInterceptor.java, pom.xml
`org.apache.commons.lang3.StringEscapeUtils.escapeXml` was replaced with `org.apache.commons.text.StringEscapeUtils.escapeXml10` which escapes more characters and potentially can break some things.
@apache/struts-committers
=> WW-4915 Replace deprecated commons-lang3 classes

core/src/main/java/com/opensymphony/xwork2/ActionContext.java, core/src/main/java/com/opensymphony/xwork2/ActionSupport.java, core/src/main/java/com/opensymphony/xwork2/conversion/impl/ConversionData.java, core/src/main/java/com/opensymphony/xwork2/conversion/impl/XWorkConverter.java, core/src/main/java/com/opensymphony/xwork2/interceptor/ConversionErrorInterceptor.java, core/src/main/java/com/opensymphony/xwork2/validator/validators/ConversionErrorFieldValidator.java, core/src/main/java/com/opensymphony/xwork2/validator/validators/RepopulateConversionErrorFieldValidatorSupport.java, core/src/test/java/com/opensymphony/xwork2/ActionContextTest.java, core/src/test/java/com/opensymphony/xwork2/ActionSupportTest.java, core/src/test/java/com/opensymphony/xwork2/conversion/impl/AnnotationXWorkConverterTest.java, core/src/test/java/com/opensymphony/xwork2/conversion/impl/XWorkConverterTest.java, core/src/test/java/com/opensymphony/xwork2/interceptor/ConversionErrorInterceptorTest.java, core/src/test/java/com/opensymphony/xwork2/validator/ConversionErrorFieldValidatorTest.java, core/src/test/java/com/opensymphony/xwork2/validator/RepopulateConversionErrorFieldValidatorSupportTest.java, core/src/test/java/com/opensymphony/xwork2/validator/VisitorFieldValidatorTest.java, core/src/test/java/org/apache/struts2/interceptor/StrutsConversionErrorInterceptorTest.java, core/src/test/resources/com/opensymphony/xwork2/SimpleAction.properties
Another one for 2.6. :)
Note: Because of the `Object` in conversion errors map (`Map<String, Object> conversionErrors`) there is no type check when switching to `Map<String, ConversionData>`, which can lead to some errors.
Note: The `ConversionData` can be improved and used later in other places.
=> WW-685 Add generic type conversion error message

core/src/main/java/org/apache/struts2/components/Checkbox.java, core/src/main/java/org/apache/struts2/views/jsp/ui/CheckboxTag.java, core/src/main/resources/template/simple/checkbox.ftl, core/src/site/resources/tags/checkbox.html, core/src/test/java/org/apache/struts2/views/jsp/ui/CheckboxTest.java, core/src/test/resources/org/apache/struts2/views/jsp/ui/Checkbox-1.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/Checkbox-2.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/Checkbox-3.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/Checkbox-33.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/Checkbox-4.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/Checkbox-5.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/Checkbox-6.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/Checkbox-7.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/Checkbox-8.txt
Added requiredValue to Checkbox Struts Tag as a parameter to give developer flexibility to use/not use "submit unchecked values" design pattern.  When requiredValue set to "false", unchecked checkbox elements will not be submitted with the form (i.e. no hidden input html elements will be created for the checkbox).  Default value is true for backwards compatibility.
[WW-4865](https://issues.apache.org/jira/browse/WW-4865)
=> WW-4865: Add "requiredValue" parameter to Checkbox Struts Tag

core/src/main/java/com/opensymphony/xwork2/ActionContext.java, core/src/main/java/com/opensymphony/xwork2/conversion/TypeConverter.java, core/src/main/java/com/opensymphony/xwork2/conversion/impl/DefaultTypeConverter.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/main/java/org/apache/struts2/views/jsp/ui/OgnlTool.java, core/src/main/resources/struts-default.xml, core/src/test/java/com/opensymphony/xwork2/ActionContextTest.java, core/src/test/java/com/opensymphony/xwork2/DefaultActionInvocationTest.java, core/src/test/java/com/opensymphony/xwork2/conversion/impl/AnnotationXWorkConverterTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/SetPropertiesTest.java, core/src/test/java/org/apache/struts2/factory/StrutsResultFactoryTest.java, core/src/test/java/org/apache/struts2/result/ServletActionRedirectResultTest.java, core/src/test/java/org/apache/struts2/result/ServletDispatcherResultTest.java, core/src/test/java/org/apache/struts2/result/ServletRedirectResultTest.java, plugins/oval/src/main/java/org/apache/struts2/oval/interceptor/OValValidationInterceptor.java, pom.xml
This PR uses the latest OGNL version which drops access to `#context` via a magical key and makes `OgnlContext` a bit immutable.
[OGNL 3.2 version notes](https://github.com/jkuhnert/ognl#release-notes---version-32)
Implements [WW-4927](https://issues.apache.org/jira/browse/WW-4927)
=> Immutable context

plugins/json/src/main/java/org/apache/struts2/json/JSONPopulator.java, plugins/json/src/test/java/org/apache/struts2/json/JSONPopulatorTest.java, plugins/json/src/test/java/org/apache/struts2/json/WrapperClassBean.java, plugins/json/src/test/resources/org/apache/struts2/json/json-7.txt
Currently when I try to deserialize a bean that contains fields of type SortedSet, I get the following exception: `java.lang.IllegalArgumentException: argument type mismatch`. This is due to the fact that JSONPopulator does not distinguish between Set and SortedSet interface. 
I added this support by creating a TreeSet for SortedSet fields. I also added a couple of tests to show the issue and confirm that it's fixed. 
I tried to follow the local code style, but since it's my first contribution to Struts project, I might have made some mistakes. I would be very happy to hear any comments and make necessary changes to this pull request. I truly appreciate your hard work of maintaining this project.
=> WW-4937 Add SortedSet support to JSON plugin

apps/showcase/src/main/resources/struts-token.xml, apps/showcase/src/main/resources/struts-validation.xml, apps/showcase/src/main/webapp/WEB-INF/token/example4.ftl
1) Token examples. Examples 2 and 3 previously resulted in 403's upon submit (config issue).
2) Token examples. Example 4 resulted in error 500 when selected from the menu (FTL param type issue).
3) Validation examples.  Examples quizBasic, quizClient and quizClientCss resulted in 404's when selected from menu (config issue).
=> Minor config fixes for the Showcase Application:

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/main/java/com/opensymphony/xwork2/util/ProxyUtil.java, core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessProxyTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessTest.java, core/src/test/java/com/opensymphony/xwork2/spring/SpringProxyUtilTest.java, pom.xml
Refs [WW-4973](https://issues.apache.org/jira/browse/WW-4973)
=> [WW-4973] Upgrades to OGNL 3.2.8

core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/main/java/org/apache/struts2/components/Include.java, core/src/main/java/org/apache/struts2/util/FastByteArrayOutputStream.java, core/src/test/java/org/apache/struts2/views/jsp/IncludeTagTest.java
Adds a config flag to make all s:include tags use response page encoding.
Adds an encoding override property to the s:include tag (flexibility).
Adds a warning log output to FastByteArrayBuffer when decoding has errors.
Fixes [WW-4971](https://issues.apache.org/jira/projects/WW/issues/WW-4971)
=> Proposed fix for WW-4971 (broken includes for non-UTF8 content).

plugins/embeddedjsp/pom.xml, plugins/oval/src/test/java/org/apache/struts2/oval/interceptor/OValValidationInterceptorTest.java, pom.xml
Update Struts 2.5.19 build with some newer (compatible) library versions.
- Fix SCM tag entry typo in main pom.xml.
- Enhance main pom.xml maven-surefire-plugin configuration to avoid some test-ng related duplication failures:  "Cannot find JUnit method class junit.framework.TestSuite$1.warning".
- Remove unnecessary plugins/embeddedjsp/pom.xml (struts2-embeddedjsp-plugin) maven-surefire-plugin version override (noted with preceding change).
- Update Struts 2.5.19 build to use some newer (compatible) library versions.
Change the main pom.xml library versions for the following:
- spring.platformVersion 4.3.13.RELEASE -> 4.3.20.RELEASE
- ognl 3.1.15 -> 3.1.18  (Note: newest version that passes unit tests)
- oval 1.31 -> 1.90      (Note: required unit test fix for …
=> Update Struts 2.5.19 build with some newer (compatible) library versions

apps/showcase/src/main/webapp/WEB-INF/fileupload/multiple-success.jsp, plugins/embeddedjsp/pom.xml, plugins/oval/src/main/java/org/apache/struts2/oval/interceptor/OValValidationInterceptor.java, plugins/oval/src/test/java/org/apache/struts2/oval/interceptor/OValValidationInterceptorTest.java, pom.xml
Update Struts 2.6.0 build with some newer (compatible) library versions.
- Add missing multiple-success.jsp for Showcase application.
- Enhance main pom.xml maven-surefire-plugin configuration to avoid some test-ng related duplication failures:  "Cannot find JUnit method class junit.framework.TestSuite$1.warning".
- Remove unnecessary plugins/embeddedjsp/pom.xml (struts2-embeddedjsp-plugin) maven-surefire-plugin version override (noted with preceding change).
- Update Struts 2.6.0 build to use some newer (compatible) library versions.
Change the main pom.xml library versions for the following:
- spring.platformVersion 4.3.13.RELEASE -> 4.3.20.RELEASE
- oval 1.31 -> 1.90  (Note: required unit test fix for OValValidationInterceptorTest.java AND code fix for OvalValidationInterceptor.java) …
=> Update Struts 2.6.0 build with some newer (compatible) library versions.

core/pom.xml, plugins/portlet/pom.xml, pom.xml
* jmock-cglib brings cglib-nodep as a transitive dependency -- no need for explicit declaration
* cglib isn't needed at all -- plugins/portlet build runs perfectly fine without it (`mvn install`)
=> Remove dependencies cglib and cglib-nodep

plugins/convention/src/main/java/org/apache/struts2/convention/ConventionConstants.java, plugins/convention/src/main/java/org/apache/struts2/convention/PackageBasedActionConfigBuilder.java, plugins/convention/src/main/java/org/apache/struts2/convention/config/entities/ConventionConstantConfig.java, plugins/convention/src/main/resources/struts-plugin.xml, plugins/convention/src/test/java/org/apache/struts2/convention/PackageBasedActionConfigBuilderTest.java
Adds the `struts.convention.enable.smi.inheritance` constant which determines if a newly created package config inherits the strict-method-invocation value of its parent package config.
=> WW-4930 Add constant to enable smi inheritance

plugins/portlet/src/test/java/org/apache/struts2/portlet/dispatcher/Jsr168DispatcherTest.java, plugins/portlet/src/test/java/org/apache/struts2/portlet/dispatcher/Jsr286DispatcherTest.java
Issue link: https://issues.apache.org/jira/browse/WW-4977
testRender_ok and testProcessAction_ok in Jsr168DispatcherTest have test-order dependencies and fail when they are run after testModeChangeUsingPortletWidgets. Similarly, testRender_ok and testProcessAction_ok in Jsr286DispatcherTest also have this problem.
These tests can be fixed by adding the entry {STRUTS_ALWAYS_SELECT_FULL_NAMESPACE=“true”} to initParams in testModeChangeUsingPortletWidgets. The fix will enable the tests in these classes to now pass in any order. Let me know if you want to discuss more.
=> [WW-4977] Fixing flaky test in Jsr168DispatcherTest and Jsr286DispatcherTest.

core/src/main/java/org/apache/struts2/dispatcher/HttpParameters.java
This method can be potentially dangerous as it allows access to raw
parameter values.
=> WW-4983 Set private access modifier for HttpParameters.toMap

.travis.yml
Use default bash if-then-else block with semicolon after each command and fix spelling for "incompatibility".
Don't do `mvn clean` b/c we need the test results for the following tasks and don't need to rebuild everything.
=> Enhance after_success for Travis CI

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java
Minor update to Struts 2.6 `SecurityMemberAccess`.
Code changes:
- updated `SecurityMemberAccess` constructor (minor parameter name cleanup, added comment).  Mirrors recent update to 2.5.x equivalent constructor.
- added `final` modifier to a couple of local variable declarations (clearly constant within the given methods).
=> Minor update to Struts 2.6 SecurityMemberAccess.

pom.xml
Update Struts 2.5.19 to use latest OGNL 3.1.x release available.
Refers [WW-4993](https://issues.apache.org/jira/browse/WW-4993)
=> Update Struts 2.5.19 to use latest OGNL 3.1.x release available.

core/src/main/java/com/opensymphony/xwork2/config/providers/XWorkConfigurationProvider.java, core/src/main/java/com/opensymphony/xwork2/ognl/ErrorMessageBuilder.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlNullHandlerWrapper.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlTypeConverterWrapper.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStackFactory.java, core/src/main/java/com/opensymphony/xwork2/ognl/XWorkTypeConverterWrapper.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/CompoundRootAccessor.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/XWorkCollectionPropertyAccessor.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/XWorkEnumerationAccessor.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/XWorkIteratorPropertyAccessor.java, core/src/main/java/com/opensymphony/xwork2/security/DefaultAcceptedPatternsChecker.java, core/src/main/java/com/opensymphony/xwork2/security/DefaultExcludedPatternsChecker.java, core/src/main/resources/struts-default.xml, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java, core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowstatic-devmode-false.xml, core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowstatic-devmode-true.xml, core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowstatic-true.xml, core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-devmode-true.xml
Updates and cleanup for some configuration-related items.
- Made several attributes final.
- Added limiter logic to the setting of certain configuration elements, and increased logging around them.
- Updated unit tests impacted by the limiter logic, including minor typo fixes and locale consistency.
- Minor cleanup while making the changes.
=> Updates and cleanup for some configuration-related items (2.5.x).

core/src/main/java/com/opensymphony/xwork2/config/providers/XWorkConfigurationProvider.java, core/src/main/java/com/opensymphony/xwork2/ognl/ErrorMessageBuilder.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlNullHandlerWrapper.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlTypeConverterWrapper.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStackFactory.java, core/src/main/java/com/opensymphony/xwork2/ognl/XWorkTypeConverterWrapper.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/CompoundRootAccessor.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/XWorkCollectionPropertyAccessor.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/XWorkEnumerationAccessor.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/XWorkIteratorPropertyAccessor.java, core/src/main/java/com/opensymphony/xwork2/security/DefaultAcceptedPatternsChecker.java, core/src/main/java/com/opensymphony/xwork2/security/DefaultExcludedPatternsChecker.java, core/src/main/resources/struts-default.xml, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java, core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowstatic-devmode-false.xml, core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowstatic-devmode-true.xml, core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowstatic-true.xml, core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-devmode-true.xml
Updates and cleanup for some configuration-related items.
- Made several attributes final.
- Added limiter logic to the setting of certain configuration elements, and increased logging around them.
- Updated unit tests impacted by the limiter logic, including minor typo fixes and locale consistency.
- Minor cleanup while making the changes.
=> Updates and cleanup for some configuration-related items (2.6.x)

core/src/main/java/org/apache/struts2/components/Set.java, core/src/main/java/org/apache/struts2/views/jsp/SetTag.java, core/src/test/java/org/apache/struts2/views/jsp/SetTagTest.java
Enhancement for `s:set` tag to allow better tag body whitespace control.
- Allow disabling of the default body whitespace trim behaviour.  
- Forward port change from PR #296 for WW-4995 into master (2.6)
=> Enhancement for s:set tag to allow better tag body whitespace control.

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStackFactory.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/CompoundRootAccessor.java, core/src/main/java/com/opensymphony/xwork2/security/DefaultAcceptedPatternsChecker.java, core/src/main/java/com/opensymphony/xwork2/security/DefaultExcludedPatternsChecker.java
Address `devMode` log flooding concern raised by Greg Huber in the Struts Dev List review of the 2.5.19 test build.
Changes:
- Introduce a static count-limiter for the `devMode` set warning in `OgnlValueStack`.  It _limits the total number of log warnings produced to 250 total_, after which it switches to trace level logs to avoid log flooding.
This is a single change which should be safe enough to include in a revised 2.5.19 build (and cherry-picked into the 2.6 master branch as well).  Since the log flooding could be somewhat annoying to developers, a compromise like this might be a reasonable response.
=> Address devMode log flooding concern raised by Greg Huber (on Dev List)

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStackFactory.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/CompoundRootAccessor.java, core/src/main/java/com/opensymphony/xwork2/security/DefaultAcceptedPatternsChecker.java, core/src/main/java/com/opensymphony/xwork2/security/DefaultExcludedPatternsChecker.java
Equivalent to PR#309 (for 2.5.x), but this one is for the master (2.6.x) branch.
- Removed most of the logging added in PR#292.
- Left the added logging for the `setExcludedPatterns `and `setAcceptedPatterns `methods in their respective modules (please see PR#309 for justification).  Made the if-else blocks consistent with preferred styling for the log blocks.
- Removed a dangling "/\*\*" start comment tag with no proper close (and the whitespace between it and the next "/\*\*") in the `OgnlValueStack `module.
=> Equivalent to PR#309, but for the master (2.6.x) branch.

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/security/DefaultAcceptedPatternsChecker.java, core/src/main/java/com/opensymphony/xwork2/security/DefaultExcludedPatternsChecker.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java, core/src/test/java/com/opensymphony/xwork2/security/DefaultAcceptedPatternsCheckerTest.java, core/src/test/java/com/opensymphony/xwork2/security/DefaultExcludedPatternsCheckerTest.java
Minor cleanup/consistency changes for 3 modules (2.5.x).
- Made a private `ConcurrentMap` reference final, made initial sets immutable (consistency).
- Made sets for Accepted and Excluded patterns checkers immutable in 2 modules (consistency).
- Added `@Override` annotations missing from a few methods in 2 modules.
- Updated the 3 relevant unit tests to verify immutable states of various sets.
=> Minor cleanup/consistency changes for 3 modules.

core/src/main/java/com/opensymphony/xwork2/config/providers/XWorkConfigurationProvider.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStackFactory.java, core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/test/java/com/opensymphony/xwork2/interceptor/ParametersInterceptorTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessProxyTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/SetPropertiesTest.java, core/src/test/java/org/apache/struts2/result/ServletRedirectResultTest.java, core/src/test/java/org/apache/struts2/util/SecurityMemberAccessInServletsTest.java, core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-staticfield-false.xml, core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-staticfield-true.xml
Fix for access issue for 2.6 discovered in WW-5004:
- Restored ability to access public static fields by default.
- Introduced a configuration flag (staticFieldAccessLevel) with three levels:
0 - disable static field access completely.
1 - allow public static field access (default).
2 - allow limited non-public static field access (primitives and strings only, with hardcoded exclusions).
- Required 3 new test configuration files, enhanced unit tests and updates to multiple modules to handle the new flag.
- Fixed bad/mismatched injection parameter name for setStaticFieldAccessLevel in OgnlValueStackFactory.
=> Fix for access issue for 2.6 discovered in WW-5004:

plugins/convention/src/main/java/org/apache/struts2/convention/DefaultClassFinder.java, pom.xml
fixes WW-5005
According to ASM7's source codes, it seems it uses passed `api` version only to check if it should throw an unsupported exception or not (i.e. doesn't have any effect on functionality and somehow is just a validation). So, as we upgrade to asm.version=7.0 for default then I think it's OK to upgrade `Opcodes.ASM5` to `Opcodes.ASM7` as well. It only breaks when user manually exclude ASM7 dependency with an older version which is not usually expected.
=> WW-5005 upgrade to ASM 7

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java
Move public member check to be the first performed
Remove final-s from methods to allow overriding
Split check for statics into two separate methods
=> Improve SecurityMemberAccess

apps/showcase/src/main/resources/struts-fileupload.xml, apps/showcase/src/main/resources/struts-token.xml, apps/showcase/src/main/resources/struts-validation.xml, apps/showcase/src/main/webapp/WEB-INF/fileupload/multiple-success.jsp, apps/showcase/src/main/webapp/WEB-INF/tags/non-ui/ifTag/testIf.jsp, apps/showcase/src/main/webapp/WEB-INF/token/example4.ftl
Minor config fixes for the Showcase Application in 2.5.x:
1) Token examples. Examples 2 and 3 previously resulted in 403's upon submit (config issue).
2) Token examples. Example 4 resulted in error 500 when selected from the menu (FTL param type issue).
3) Validation examples.  Examples quizBasic, quizClient and quizClientCss resulted in 404's when selected from menu (config issue).
4) File upload examples.  Multiple file upload missing result page (list and array), added missing JSP.  Added missing input results in configuration.
Similar to `PR#255` for 2.6.x.
=> Minor config fixes for the Showcase Application in 2.5.x:

apps/showcase/pom.xml, plugins/bean-validation/pom.xml
The 2.6 Showcase application is throwing JAXB-classloading-related failures when deployed to a container running Java 11.
The stacktrace indicates the issues relate to the bean-validator and Hibernate-Validator (but no issues with Java 8).
Upgrade `Hibernate-Validator` version to resolve failure:
1) Showcase upgrade 5.1.3.Final to 5.4.3.Final (most recent available).
2) bean-validator upgrade 5.4.1-Final to 5.4.3.Final (to match versions).
=> Fix 2.6 Showcase bean-validator Java 11 failures.

core/src/main/java/org/apache/struts2/interceptor/TokenSessionStoreInterceptor.java, core/src/main/java/org/apache/struts2/util/InvocationSessionStore.java, core/src/test/java/org/apache/struts2/util/InvocationSessionStoreTest.java
Fix issue introduced with earlier WW-4873 fix:
- Fixes error 500 processing failures for double-submit results with TokenSessionStoreInterceptor processing
- Fix to InvocationSessionStore, new unit test confirming fix in InvocationSessionStoreTest
- Minor whitespace fix to TokenSessionStoreInterceptor
=> Proposed fix for WW-5026 (TokenSessionStoreInterceptor double-submit failure)

core/src/main/java/org/apache/struts2/dispatcher/HttpParameters.java, core/src/main/java/org/apache/struts2/interceptor/ActionMappingParametersInterceptor.java, core/src/test/java/org/apache/struts2/interceptor/ActionMappingParametersInterceptorTest.java
Proposed fix for WW-5024 in the 2.5.x branch:
- **NOTE**: If the PR is accepted **_please credit_ Robert Hollencamp (Github @rhollencamp) for this change**
as he found the issue, proposed a solution for 2.6 (master), and opened the JIRA.
- Updated HttpParameters, ActionMappingParametersInterceptor to prevent multi-level Parameter wrapping from occuring.
- Added a new ActionMappingParametersInterceptorTest to verify the fix.
=> Proposed fix for WW-5024 in the 2.5.x branch:

core/src/main/java/org/apache/struts2/interceptor/TokenSessionStoreInterceptor.java, core/src/main/java/org/apache/struts2/util/InvocationSessionStore.java, core/src/test/java/org/apache/struts2/util/InvocationSessionStoreTest.java
Forward-port fix for WW-5026 to 2.6
- Equivalent to PR#342 for 2.5.x, fixes double-submit error 500 failure with
- Fixes error 500 processing failures for double-submit results with TokenSessionStoreInterceptor processing
- Fix to InvocationSessionStore, new unit test confirming fix in InvocationSessionStoreTest
- Minor whitespace fix to TokenSessionStoreInterceptor
=> Forward-port fix for WW-5026 to 2.6

core/src/main/java/org/apache/struts2/dispatcher/HttpParameters.java, core/src/main/java/org/apache/struts2/interceptor/ActionMappingParametersInterceptor.java, core/src/test/java/org/apache/struts2/interceptor/ActionMappingParametersInterceptorTest.java
Forward port fix for WW-5024 to 2.6:
- **NOTE**: _If the PR is accepted_ **please credit Robert Hollencamp (Github @rhollencamp)** for this change
as he found the issue, proposed a solution for 2.6 (master), and opened the JIRA.
- Updated HttpParameters, ActionMappingParametersInterceptor to prevent multi-level Parameter wrapping from occuring.
- Updated HttpParameters create(), build() and buildNoNestedWrapping() to replace redundant type operators with <> based on IDE hint.
- Made HttpParameters parameters member final based on IDE hint.
- Added a new ActionMappingParametersInterceptorTest to verify the fix.
=> Forward port fix for WW-5024 to 2.6:

.gitignore
Ignore .factorypath b/c it gets generated during maven compile.
Don't need to ignore every single target folder.
Instead use target/ pattern and add more common maven files.
Ignore .sonar folder for local sonar scanning.
=> Add common .gitignore patterns from gitignore.io

core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java, core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java
Proposed fix for WW-5028 for the 2.5.x branch:
- Disable printing stacktrace on exceptions by the Dispatcher by default.
- Printing stacktrace on exception can be re-enabled by configuration.
- Now prints stacktrace on exception using LOG, as suggested by A. Mashchenko and the the JIRA reporter.
=> Proposed fix for WW-5028 for the 2.5.x branch:

core/src/main/java/com/opensymphony/xwork2/config/providers/XmlConfigurationProvider.java, core/src/test/java/com/opensymphony/xwork2/config/providers/XmlConfigurationProviderTest.java
Proposed fix for WW-5029 for the 2.5.x branch:
- NOTE: If the PR is accepted **please credit Maxime Clement for this change** as they found
the issue, identified the probable cause/related details and opened the JIRA.
- Updated XWorkConfigurationProvider buildAllowedMethods(), loadGlobalAllowedMethods() so that
they now handle situations when a SAX parser produces multiple elements to represent the tag
body value.
- No changes to unit tests.
=> Proposed fix for WW-5029 for the 2.5.x branch

core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java, core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java
parameter      = token "=" ( token / **quoted-string** )
Note: Unlike some similar constructs in other header fields, media
type parameters **do not allow whitespace (even "bad" whitespace)
around the "=" character.**
Reference: https://tools.ietf.org/html/rfc7231#section-3.1.1.1
=> fix multipart request RegEx (relates to WW-4958)

core/src/main/java/com/opensymphony/xwork2/config/providers/XmlConfigurationProvider.java
Minor consistency update correction for WW-5029 fix to the 2.5.x branch:
- Correct missing verification in `buildAllowedMethods()`/`loadGlobalAllowedMethods()` that the nodes are of type `Node.TEXT_NODE` (as `buildResults()` does).
- Made two class fields `final`, as suggested by IDE.
=> Minor consistency update correction for WW-5029 fix to the 2.5.x branch

pom.xml
Update Three Struts 2.5.x dependencies to latest versions:
- Jackson 2.9.8 -> 2.9.9
- Log4j2 2.11.1 -> 2.11.2
- OGNL 3.1.22 -> 3.1.23
Struts 2.5.21-SNAPSHOT builds successfully with these versions.
=> Update Three Struts 2.5.x dependencies to latest versions

core/src/main/java/com/opensymphony/xwork2/util/AbstractLocalizedTextProvider.java, core/src/test/java/com/opensymphony/xwork2/util/StrutsLocalizedTextProviderTest.java
Minor enhancement/fix to AbstractLocalizedTextProvider:
- Made "constant" RELOADED static to save an initialization every time.
- Updated clearBundle(final String bundleName) method comment as it
seemed inaccurate, added debug log output when called.
- Introduced protected clearBundle(final String bundleName, Locale locale)
method for use by descendants, with debug log output when called.
- Introduced protected clearMissingBundlesCache() method for use by
descendants, with debug log when called.
=> Minor enhancement/fix to AbstractLocalizedTextProvider:

.travis.yml, core/src/test/resources/log4j2.xml, plugins/tiles/src/main/java/org/apache/struts2/tiles/StrutsApplicationResource.java, plugins/tiles/src/main/java/org/apache/struts2/tiles/StrutsWildcardServletApplicationContext.java, plugins/tiles/src/test/java/org/apache/struts2/tiles/StrutsApplicationResourceTest.java, plugins/tiles/src/test/resources/emptyTiles###2.xml, plugins/tiles/src/test/resources/emptyTiles.xml
include ref in path for StrutsApplicationResource as WW-5011 workaround (when real path or filename contains "#" character)
=> include ref in path as WW-5011 workaround

core/src/main/java/com/opensymphony/xwork2/util/AbstractLocalizedTextProvider.java, core/src/test/java/com/opensymphony/xwork2/util/StrutsLocalizedTextProviderTest.java
[WW-5034] Forward port - Minor enhancement/fix to AbstractLocalizedTextProvider:
- Forward port of equivalent change from 2.5.x.
- Made "constant" RELOADED static to save an initialization every time.
- Made ineffective clearBundle(final String bundleName) method a "no-op" with a debug log indicating the same.  Marked method as deprecated.
- Introduced protected clearBundle(final String bundleName, Locale locale) method for use by descendants, with debug log output when called.
- Introduced protected clearMissingBundlesCache() method for use by descendants, with debug log when called.
=> [WW-5034] Forward port - Minor enhancement/fix to AbstractLocalizedTextProvider:

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/CompoundRootAccessor.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java
Moves checking OgnlValueStack.THROW_EXCEPTION_ON_FAILURE outside loop because it shouldn't throw exception on first failure while is trying all root objects.
Returns on first successful call because it's not rational and is confusing user to skip when user method successfully returns null as an actual result.
Fixes WW-4999 via honoring (devMode && logMissingProperties) for OgnlValueStack.THROW_EXCEPTION_ON_FAILURE and REPORT_ERRORS_ON_NO_PROP.
=> fix logMissingProperties (WW-4999)

core/src/main/java/org/apache/struts2/interceptor/MultiselectInterceptor.java
Correcting `Sting` to `String`
=> Fix typo in MultiselectInterceptor javadoc

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java
Proposed WW-5035 enhancement:
- Provide cache clearing methods for `OgnlUtil` (expression cache, BeanInfo cache).
- Provide methods to check the cache sizes (entry number for expression cache, BeanInfo cache).
- Provide static method to clear the `OgnlRuntime` cache (convenience method).
=> Proposed WW-5035 enhancement:

core/src/main/java/org/apache/struts2/dispatcher/DefaultDispatcherErrorHandler.java, core/src/main/java/org/apache/struts2/dispatcher/DefaultStaticContentLoader.java, core/src/test/java/org/apache/struts2/dispatcher/DefaultDispatcherErrorHandlerTest.java, core/src/test/java/org/apache/struts2/dispatcher/DefaultStaticContentLoaderTest.java
Improved logging for DefaultDispatcherErrorHandler and DefaultStaticContentLoader.
Provide informational logging for the processing of the two dispatcher classes when an http sendError fails for the two known failure types (IOException, IllegalStateException).
In both circumstances it is beneficial to have the developer aware of the failures via the logs.  These are not events that should be happening on a regular basis, so there is little risk of a log flood.
DefaultStaticContentLoader didn't catch either exception type previously, so changing it to make handling the same as DefaultDispatcherErrorHandler.
For DefaultDispatcherErrorHandler the IOException was caught with no notice of failure previously.  Now there will be an info level log output.
Previously the IllegalStateException was …
=> Improved logging for DefaultDispatcherErrorHandler, DefaultStaticContentLoader

core/src/main/java/org/apache/struts2/result/ServletRedirectResult.java, core/src/test/java/org/apache/struts2/result/ServletRedirectResultTest.java
Minor improvement proposed for ServletRedirectResult sendRedirect()
Supply log warning when an IOException or IllegalStateException occurs to better allow developers to track the failed redirect location and status details.  The exceptions are re-thrown to ensure existing flow-control behaviour is preserved.
When getWriter() is called, utilize a finally block to ensure close is called.
=> Minor improvement proposed for ServletRedirectResult sendRedirect()

core/src/main/java/com/opensymphony/xwork2/config/providers/XmlConfigurationProvider.java
Hello Apache Struts Team.
This PR is a cherry-pick of a change, PR#354, that was missed for 2.6.x.  The change for PR#347 was previously cherry-picked into master, but PR#354 provided an update to that logic.
Merge pull request #354 from JCgH4164838Gh792C124B5/localS2_25x_B10
Minor consistency update correction for WW-5029 fix to the 2.5.x branch
(cherry picked from commit bb9ce7582b5b8e021eb458527777db07594e5739)
=> Forward-port PR#354 from 2.5.x to 2.6.x (cherry-pick)

pom.xml
Update multiple Struts 2.5.x libraries to more recent versions.
Relates to WW-5033 and PRs: #356, #362.  Updated libraries:
Spring Platform 4.3.24 -> 4.3.25
Log4j2 2.11.2 -> 2.12.1
Jackson 2.9.9 -> 2.9.10 (allows removal of jackson 2.9.9.3 "micro patch" entry, taking care of pom.xml FIXME).
stax2-api 4.1 -> 4.2 (noted during Jackson update)
Fluido Skin 1.7 -> 1.8
SLF4J 1.7.26 -> 1.7.28
=> Update multiple Struts 2.5.x libraries to more recent versions.

core/src/site/confluence/ww-template-autoexport.html
Remove duplicate attributes in an HTML file at the confluence directory.
Signed-off-by: Lucca Scarano <lucca.scarano@hotmail.com>
=> Remove duplicate attribute

pom.xml
(cherry picked from commit 4556f404bddc99c90f90c359351797f4b54b3917)
@lukaszlenart I guess, this is also needed for the current support branch 2.5.x
=> WW-5042 Upgrade jackson-databind to version 2.10.0

apps/showcase/src/main/webapp/WEB-INF/decorators/main.jsp, apps/showcase/src/main/webapp/WEB-INF/filedownload/index.jsp, apps/showcase/src/main/webapp/WEB-INF/tags/non-ui/iteratorTag/appendIteratorTagDemoResult.jsp, apps/showcase/src/main/webapp/WEB-INF/tags/non-ui/iteratorTag/iteratorGeneratorTagDemoResult.jsp, apps/showcase/src/main/webapp/WEB-INF/tags/non-ui/iteratorTag/mergeIteratorTagDemoResult.jsp, apps/showcase/src/main/webapp/WEB-INF/tags/non-ui/iteratorTag/subsetIteratorTagDemoResult.jsp, core/src/main/java/org/apache/struts2/components/Anchor.java, core/src/main/java/org/apache/struts2/components/Component.java, core/src/main/java/org/apache/struts2/components/Submit.java, core/src/main/java/org/apache/struts2/views/jsp/ui/AnchorTag.java, core/src/main/java/org/apache/struts2/views/jsp/ui/SubmitTag.java, core/src/main/resources/template/simple/a-close.ftl, core/src/main/resources/template/simple/submit-close.ftl, core/src/test/java/org/apache/struts2/components/ComponentTest.java, core/src/test/java/org/apache/struts2/views/jsp/ui/AnchorTest.java, core/src/test/java/org/apache/struts2/views/jsp/ui/SubmitTest.java, core/src/test/resources/org/apache/struts2/views/jsp/ui/Submit-11.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/Submit-12.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/href-3.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/href-4.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/href-5.txt
Proposed fix for WW-5022 (escape html tag body control flag)
- Added escapeHtmlBody parameter to s:a and s:submit tags.
- No other tags appear to require this feature (but can be added to any component).
- Added new unit tests for escapeHtmlBody (and usesBody for component).
- Fixed broken s:a tags in ShowCase app.
=> Proposed fix for WW-5022 (escape html tag body control flag)

core/src/main/java/com/opensymphony/xwork2/inject/ContainerImpl.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/main/java/org/apache/struts2/views/jsp/ui/OgnlTool.java, core/src/main/resources/org/apache/struts2/default.properties, core/src/main/resources/struts-default.xml, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java, core/src/test/java/org/apache/struts2/result/StreamResultTest.java, pom.xml
It is green on my local builds. When OGNL 3.1.26 released, this one would be green either.
If merged, Struts would be less brittle when user applies an OgnlSecurityManager. Also Struts would block OGNL expressions longer than 200 characters (albeit it's unit-tested that it's still able to set long values e.g. a long email text).
=> WW-5041 Upgrade to OGNL 3.1.26 and adapt to its new features

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/resources/struts-default.xml, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java
Minor follow-up changes to PR #371
- added some additional exclusions in struts-default.xml.
- added log warning that specifies the value of maxLength involved if applyExpressionMaxLength(maxLength) fails.
- added null guards to two handleOgnlException() methods that could result in an NPE with #371 changes (a null OgnlException parameter was permissible previously, correct or not).
=> Minor follow-up changes to PR #371

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/resources/org/apache/struts2/default.properties, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java
Disable struts.ognl.expressionMaxLength by default for Struts 2.5.x.
- Commented out struts.ognl.expressionMaxLength line in default.properties and provided in-place comments about its usage.
- Changed OgnlValueStack.handleOgnlException() methods to output error instead of warn for failures to evaluate expressions due to security constraints.
- Updated existing unit tests to compensate for change in default behaviour.
- Added a unit test to confirm default behaviour for struts.ognl.expressionMaxLength is disabled.
=> Disable expressionMaxLength by default for Struts 2.5.x.

core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java
Fix incorrect encoding strings provided in FileUploadInterceptorTest
- Tests were using "text/html" which is not a valid character encoding. No impact currently, but the tests could fail in the future if this is not corrected.  If the code is re-used elsewhere for a test of an action a
valid encoding will be needed.
- Switch to a predefined constant Charset to get the string instead.
=> Fix incorrect encoding strings in FileUploadInterceptorTest

core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java
Fix incorrect encoding strings in FileUploadInterceptorTest (cherry-pick fix for 2.6.x)
Merge pull request #385 from JCgH4164838Gh792C124B5/local_25x_TstFix1
Fix incorrect encoding strings in FileUploadInterceptorTest
(cherry picked from commit 47c87bc62cd41c668146e18c1b06d49ecec7fd0a)
=> Fix incorrect encoding strings in FileUploadInterceptorTest (cherry-pick fix for 2.6.x)

core/src/main/java/com/opensymphony/xwork2/conversion/impl/DateConverter.java, core/src/main/java/com/opensymphony/xwork2/conversion/impl/NumberConverter.java, core/src/main/java/com/opensymphony/xwork2/conversion/impl/XWorkBasicConverter.java, core/src/main/java/org/apache/struts2/conversion/TypeConversionException.java, core/src/test/java/com/opensymphony/xwork2/conversion/impl/DateConverterTest.java, core/src/test/java/com/opensymphony/xwork2/conversion/impl/NumberConverterTest.java, core/src/test/java/com/opensymphony/xwork2/conversion/impl/XWorkBasicConverterTest.java
The StrutsException was switched to TypeConversionException in these classes:
- DateConverter
- NumberConverter
- XWorkBasicConverter
Required tests were added in these classes:
- DateConverterTest (New class)
- NumberConverterTest
- XWorkBasicConverterTest
=> WW5052 TypeConversionException instead StrutsException

apps/showcase/pom.xml, core/pom.xml, plugins/bean-validation/pom.xml, plugins/cdi/pom.xml, pom.xml
Proposed WW-5067 change
------
Proposed list of library version updates:
---
- cdi-api 1.0-SP4 -> 1.2
- weld-core 1.0.1-SP4 -> 2.2.16.SP1
- weld-se 1.0.1-Final -> weld-se-core 2.2.16.SP1
- slf4j-api 1.7.28 -> 1.7.30
- slf4j-simple 1.7.28 -> 1.7.30
- jackson 2.10.0 -> 2.10.3
- ognl 3.1.26 -> 3.1.28
- asm 7.1 -> 7.3.1
- spring 4.3.25.RELEASE -> 4.3.26.RELEASE
- freemarker 2.3.28 -> 2.3.30
- org.apache.felix.main 4.6.1 -> 6.0.3
---
Proposed list of Maven plugin version updates:
---
- doxia-core 1.8 -> 1.9.1
- doxia-module-markdown 1.7 -> 1.9.1
- maven-project-info-reports-plugin 2.7 -> 3.0.0
- updateimpact-maven-plugin 1.0.10 -> 1.0.12
- maven-surefire-plugin 2.22.1 -> 3.0.0-M4
- maven-war-plugin 2.1 -> 3.2.3
- maven-dependency-plugin 2.10 -> 3.1.2
- dependency-check-maven 3.3.4 -> 5.3.2 …
=> Proposed WW-5067 change

apps/rest-showcase/pom.xml, apps/showcase/pom.xml, plugins/bean-validation/pom.xml, plugins/cdi/pom.xml, pom.xml
Proposed WW-5068 change.
------
Proposed list of library version updates:
---
cdi-api 1.0-SP4 -> 1.2
weld-core 1.0.1-SP4 -> 2.2.16.SP1
weld-se 1.0.1-Final -> weld-se-core 2.2.16.SP1
htmlunit 2.27.0 and 2.37.0 -> 2.39.0
slf4j-api 1.7.29 -> 1.7.30
slf4j-simple 1.7.29 -> 1.7.30
log4j2 2.12.1 - > 2.13.1
jackson 2.10.1 -> 2.10.3
ognl 3.2.12 -> 3.2.14
asm 7.2 -> 7.3.1
spring 4.3.25.RELEASE -> 4.3.26.RELEASE
fluido-skin 1.8 -> 1.9
freemarker 2.3.28 -> 2.3.30
org.apache.felix.main 4.6.1 -> 6.0.3
velocity 2.1 -> 2.2
junit 4.12 -> 4.13
easymock 3.5.1 -> 4.2
javax.el 3.0.1-b10 -> 3.0.1-b11
jstl 1.1.2 -> 1.2
tomcat-jasper 8.5.37 -> 8.5.53
tomcat-api 8.5.37 -> 8.5.53
tomcat-juli 8.5.37 -> 8.5.53
commons-lang3 3.9 -> 3.10
assertj-core 2.9.1 -> 3.15.0
mockito-core 2.23.0 -> 3.3.3   (required exclusion …
=> Proposed WW-5068 change

core/src/test/java/com/opensymphony/xwork2/validator/DateRangeValidatorTest.java, core/src/test/java/com/opensymphony/xwork2/validator/VisitorFieldValidatorTest.java
Initial fix for WW-5069:
- Force US Locale for two tests that use date strings of the form MM/DD/CCYY.
- When the tests/build are run in an environment with a non-US Locale and newer JDKs the tests may fail due to inability to parse the US date format.
Note: Was noticed on Windows 10 with JDK11, but could affect other environments when run in a non-US Locale.
=> Initial fix for WW-5069 (improve build behaviour JDK9+)

plugins/cdi/pom.xml, pom.xml
WW-5067-Fix1
- Accidental change of artifactId when groupId was changed for weld-se in original PR.  This commit restores the originally intended artifactId.
=> WW-5067-Fix1 (correct accidental artifactId change)

core/src/main/java/com/opensymphony/xwork2/config/impl/AbstractMatcher.java, core/src/test/java/com/opensymphony/xwork2/config/impl/ActionConfigMatcherTest.java
For [WW-5065] fixing the bug in the AbstractMatcher#replaceParameters method and adding a test case for it.
=> [WW-5065] Removing unnecessary part of AbstractMatcher#replaceParameters

core/src/test/java/com/opensymphony/xwork2/validator/DateRangeValidatorTest.java, core/src/test/java/com/opensymphony/xwork2/validator/VisitorFieldValidatorTest.java
Cherry-Pick PR#404 change into master.
Merge pull request #404 from JCgH4164838Gh792C124B5/WW-5069
Initial fix for WW-5069 (improve build behaviour JDK9+)
(cherry picked from commit 1526b36dd623164d671ec1f03ecf832b6b71f313)
=> Cherry-Pick PR#404 into master

plugins/portlet/pom.xml, pom.xml
Proposed WW-5074 Fix:
- Exclude ASM 3.3.1 from inclusion as a dependency for commons-digester3 (also mark commons-digester3 as optional dependency since it is only listed to allow the exclusion).
- Provide explicit test dependency of ASM 3.3.1 for portlet-plugin (otherwise its jmock tests are unable to execute).
=> Proposed WW-5074 Fix

plugins/portlet-mocks/src/test/java/org/apache/struts2/StrutsSpringPortletMockObjectsTest.java
Minor post WW-5030 Cleanup:
- Correction/fix for test within testMockPortletSession(), following recent changes to 2.6.x.
- Fix TestMockMultipartFile.isEmpty() bug in both original logic and recent changes to 2.6.x.
=> Minor post WW-5030 Cleanup for 2.6.x

core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java
Partial backport of L. Lenart's PR#414 to 2.5.x:
- Improve `Dispatcher` `getLocale()` handling if running in AppEngine.
- Implemented the same improvement to the `defaultLocale` logic path within `getLocale()`.
=> Partial backport of Tiny improvements PR#414 to 2.5.x:

core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java, core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java
Straightforward cherry-pick of PR #416 and PR #417 into 2.6.x.
The 1st cherry-pick required a manual merge-conflict resolution, the 2nd was clean.
=> Cherry-pick PR#416 and PR#417 from 2.5.x into 2.6.x

core/src/main/java/com/opensymphony/xwork2/security/DefaultAcceptedPatternsChecker.java, core/src/main/java/com/opensymphony/xwork2/security/DefaultExcludedPatternsChecker.java, core/src/test/java/com/opensymphony/xwork2/security/DefaultAcceptedPatternsCheckerTest.java
Refs [WW-5077](https://issues.apache.org/jira/browse/WW-5077)
=> [WW-5077] DMI aware pattern

core/src/main/java/org/apache/struts2/interceptor/DefaultResourceIsolationPolicy.java, core/src/main/java/org/apache/struts2/interceptor/FetchMetadataInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/ResourceIsolationPolicy.java, core/src/main/java/org/apache/struts2/interceptor/StrutsResourceIsolationPolicy.java, core/src/main/resources/struts-default.xml, core/src/test/java/org/apache/struts2/interceptor/FetchMetadataInterceptorTest.java
Hello Struts devs,
This PR builds Fetch Metadata support for Struts2, namely:
- If a request has `Sec-Fetch-*` headers (i.e. comes from a modern browser), the Fetch Metadata Interceptor will reject the request if it is requested cross-site (a potential CSRF attack).
- One default Resource Isolation Policy is provided based on https://web.dev/fetch-metadata/, which prevents all major cross-site request forgery attacks.
- This Interceptor gives the ability to add exemptions to this security mitigation, that is: URLs that are meant to be accessed cross-site.
- The Fetch Metadata Interceptor has been added to the default interceptor stack.
- The `Vary` header has been added to responses to ensure that any cached responses include Fetch Metadata headers in their key. This is an added layer of …
=> WW-5083: Adds support for Fetch Metadata in Struts2.

core/src/main/java/org/apache/struts2/interceptor/FetchMetadataInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/ResourceIsolationPolicy.java, core/src/main/java/org/apache/struts2/interceptor/StrutsResourceIsolationPolicy.java, core/src/test/java/org/apache/struts2/interceptor/FetchMetadataInterceptorTest.java, core/src/test/resources/struts-testing.xml
WW-5083 PR#426 follow-up.
- Updated ResourceIsolationPolicy Sec-Fetch* header cases to match spec.
- Added the Sec-Fetch-User header, plus additional dest/site/mode values  from the spec.
- Renamed ResourceIsolationPolicy interface constants to follow the naming convention that was already present.
- Made StrutsResourceIsolationPolicy checks case-insensitive (even if specification says things should be case-sensitive) to better handle client bugs that will likely occur in the future.
- Updated FetchMetaDataInterceport to use more standard LOG reference name, parameterization and call forms seen in other Struts 2 Interceptors.
- Including the Sec-Fetch-User in the Vary resonse header.
- Make setExemptedPaths an injectable method (but not required).
- Updated unit test to use more of the …
=> WW-5083 PR#426 follow-up.

core/src/main/java/org/apache/struts2/action/CspReportAction.java, core/src/main/java/org/apache/struts2/action/DefaultCspReportAction.java, core/src/main/java/org/apache/struts2/components/Link.java, core/src/main/java/org/apache/struts2/components/Script.java, core/src/main/java/org/apache/struts2/interceptor/csp/CspInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/csp/CspSettings.java, core/src/main/java/org/apache/struts2/interceptor/csp/DefaultCspSettings.java, core/src/main/java/org/apache/struts2/views/jsp/ui/LinkTag.java, core/src/main/java/org/apache/struts2/views/jsp/ui/ScriptTag.java, core/src/main/resources/struts-default.xml, core/src/main/resources/template/simple/link.ftl, core/src/main/resources/template/simple/script-close.ftl, core/src/main/resources/template/simple/script.ftl, core/src/main/resources/template/xhtml/link.ftl, core/src/main/resources/template/xhtml/script.ftl, core/src/site/resources/tags/link-attributes.html, core/src/site/resources/tags/link-description.html, core/src/site/resources/tags/script-attributes.html, core/src/site/resources/tags/script-description.html, core/src/test/java/org/apache/struts2/action/CspReportActionTest.java, core/src/test/java/org/apache/struts2/interceptor/CspInterceptorTest.java, core/src/test/java/org/apache/struts2/views/jsp/ui/LinkTagTest.java, core/src/test/java/org/apache/struts2/views/jsp/ui/ScriptTagTest.java, plugins/javatemplates/src/main/java/org/apache/struts2/views/java/simple/LinkHandler.java, plugins/javatemplates/src/main/java/org/apache/struts2/views/java/simple/ScriptHandler.java, plugins/javatemplates/src/main/java/org/apache/struts2/views/java/simple/SimpleTheme.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/LinkTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/ScriptTest.java
Hello Struts Devs!
This PR adds Content Security Policy support for Struts 2. A very popular security mitigation against XSS and other injection vulnerabilities. CSP comes in many flavours, but we've chosen to add support for the most robust of them: nonce-based, strict-dynamic CSP.
Here's a summary of these changes:
- Allows users to configure whether CSP is enabled in **reporting or enforcement modes** and lets them set a report URI, where violation reports will be sent by the browser.
- Implements a CSP Interceptor that generates a **nonce-based, strict-dynamic policy** and adds it to HTTP responses according to the user's configuration.
- Implements custom `<script>` and `<link>` JSP and FTL tags. These (<s:script> in taglib, for instance) **set the nonce attribute on script and link …
=> WW-5084: Add Content Security Policy support to Struts

core/src/main/java/org/apache/struts2/interceptor/FileUploadInterceptor.java
On an empty file upload the storeLocation is null, so adds a file new StrutsUploadedFile(null)
JakartaMultiPartRequest
List fileList = new ArrayList<>(items.size());
for (FileItem fileItem : items) {
File storeLocation = ((DiskFileItem) fileItem).getStoreLocation();
if (fileItem.isInMemory() && storeLocation != null && !storeLocation.exists()) {
try {
storeLocation.createNewFile();
} catch (IOException e) {
LOG.error("Cannot write uploaded empty file to disk: {}", storeLocation.getAbsolutePath(), e);
}
}
fileList.add(new StrutsUploadedFile(storeLocation));
}
The FileUploadInterceptor checks for a null file but not null content from the new StrutsUploadedFile(null).
eg for an empty file main.js
Error message should be:
Error uploading: main.js
but gives:
Error setting expression …
=> [WW-5088] Empty file upload, storeLocation null gives wrong error message.

bundles/admin/src/main/resources/static/js/shell.js, bundles/demo/pom.xml, bundles/demo/src/main/java/actions/osgi/HelloWorldAction.java, bundles/demo/src/main/resources/content/osgi/hello.ftl, bundles/demo/src/main/resources/content/osgi/hello.vm, bundles/demo/src/main/resources/struts.xml, plugins/osgi/src/main/java/org/apache/struts2/osgi/BundlePackageLoader.java
Backport a few PR#433 OSGi plugin-related changes from 2.6 to 2.5.
- Fix to allow the OSGi plugin to initialize with no internet connection.
- Fix an unintended JS change for the admin bundle.
- Fix the OSGi Demo bundle so it works under 2.5.x as well.
=> Backport a few PR#433 OSGi plugin-related changes from 2.6 to 2.5.

core/src/main/java/com/opensymphony/xwork2/interceptor/AliasInterceptor.java, core/src/test/java/com/opensymphony/xwork2/interceptor/AliasInterceptorTest.java, core/src/test/resources/xwork-sample.xml
There was a bug with AliasInterceptor not handling the Parameter.Empty that is returned from HttpParameters.get(). Since HttpParameters.get() always returns a non-null value, the Evaluated object is treated as always being defined, which results in the empty value being set incorrectly on the stack.
=> WW-5087 handle Parameter.Empty properly

apps/showcase/src/test/java/it/org/apache/struts2/showcase/FileUploadTest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java
Add integration test to detect regressions if commons-fileupload behavior changes in the future.
DiskFileItemFactory#setSizeThreshold should be set to -1 because org.apache.commons.io.output.ThresholdingOutputStream#checkThreshold checks if the current file size is strictly greater than the threshold.
=> WW-5088: Integration test for empty file upload.

plugins/embeddedjsp/src/main/java/org/apache/struts2/jasper/compiler/JspReader.java, plugins/embeddedjsp/src/main/java/org/apache/struts2/jasper/compiler/Parser.java
Meaningless Close: In several classes, close(), specified in Closeable interface, has no effect and other methods in those classes can be called after close() without IOException.
=> Fix meaningless close

pom.xml
with JDK 16 support (sealed classes)
according to https://asm.ow2.io/versions.html
=> [WW-5098] Upgrade asm to 9.0

plugins/json/src/main/java/org/apache/struts2/json/JSONUtil.java
The tests `org.apache.struts2.json.SMDMethodInterfaceTest#testBaseClassOnly` and `org.apache.struts2.json.SMDMethodInterfaceTest#testInterfaces` can fail due to a different iteration order of `Object.getMethods()`. The failures are as follows:
```
[ERROR] org.apache.struts2.json.SMDMethodInterfaceTest.testBaseClassOnly  Time elapsed: 0.008 s  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<get[Z]> but was:<get[X]>
at org.apache.struts2.json.SMDMethodInterfaceTest.testBaseClassOnly(SMDMethodInterfaceTest.java:136)
[ERROR] org.apache.struts2.json.SMDMethodInterfaceTest.testInterfaces  Time elapsed: 0 s  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<get[Z]> but was:<get[X]>
at org.apache.struts2.json.SMDMethodInterfaceTest.testInterfaces(SMDMethodInterfaceTest.java:155) …
```
=> sort getMethods for deterministic iteration order

core/src/main/java/com/opensymphony/xwork2/util/AbstractLocalizedTextProvider.java, core/src/test/java/com/opensymphony/xwork2/util/StrutsLocalizedTextProviderTest.java
Initial attempt to address WW-5101
- Add comments to methods related to ResourceBundle cache clearing.
- Correct clearTomcatCache() so that it acts as intended for Tomcat 7-10.
- Add clearResourceBundleClassloaderCaches() method that uses standard Java API calls to perform the cache clearing.
- Adjust clearMap() logic to only change accessiblity when required.
=> Initial attempt to address WW-5101

core/src/main/java/com/opensymphony/xwork2/util/AbstractLocalizedTextProvider.java, core/src/main/java/com/opensymphony/xwork2/util/GlobalLocalizedTextProvider.java, core/src/main/java/com/opensymphony/xwork2/util/StrutsLocalizedTextProvider.java, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/main/resources/org/apache/struts2/default.properties, core/src/test/java/com/opensymphony/xwork2/util/StrutsLocalizedTextProviderTest.java, core/src/test/resources/com/opensymphony/xwork2/util/Bar.properties, core/src/test/resources/com/opensymphony/xwork2/util/LocalizedTextUtilTest.properties
TextProvider feature addition and cleanup:
- Introduce (optional) control flag STRUTS_I18N_SEARCH_DEFAULTBUNDLES_FIRST to request TextProviders read from default resource bundles first, instead of their standard lookup ordering.  Defaults to false.
- Minor refactor of AbstractLocalizedTextProvider hierarchy to introduce getDefaultMessageWithAlternateKey() method that repackages existing logic used by the SrutsLocalizedTextProvider and GlobalLocalizedTextProvider.
- Update GlobalLocalizedTextProvider method comments to properly reflect the actual logic of some of its methods.
- New unit tests to confirm standard and default bundle first lookup ordering.
- Cleanup of some unused imports, a few typos, and code formatting items.
- Cleanup of default.properties comments to make them more …
=> Proposed TextProvider feature addition (and cleanup)

core/src/main/java/com/opensymphony/xwork2/TextProvider.java, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/main/java/org/apache/struts2/config/StrutsBeanSelectionProvider.java, core/src/main/java/org/apache/struts2/config/entities/ConstantConfig.java, plugins/config-browser/src/main/java/org/apache/struts2/config_browser/ShowBeansAction.java
Drops deprecated `struts.xworkTextProvider` and `struts.localeProvider` config options.
Refs [WW-5113](https://issues.apache.org/jira/browse/WW-5113)
Refs [WW-5114](https://issues.apache.org/jira/browse/WW-5114)
=> [WW-5113] [WW-5114] Drops deprecated config options

core/src/main/java/org/apache/struts2/result/PostbackResult.java
I assume `A-z` is a typo (and should be `A-Z`) because it matches:
- `A-Z`
- `[`, `\`, `]`, `^`, `_`, <code>`</code>
- `a-z`
=> WW-5116: Fix wrong regex range

core/src/main/java/com/opensymphony/xwork2/util/AbstractLocalizedTextProvider.java
The localized resources lookup shows high contention during significant stress in an enterprise application delivering the UI using Struts 2.5.20.
Profiling the app while under load stress using the excellent https://github.com/jvm-profiling-tools/async-profiler (using the `lock` mode and `--reverse` option to aggregate on the various contention code locations) shows the following picture:
No other high contention code paths was detected (profiler obviously shows high lock wait times on EPoll and other `java.util.concurrent`-related waits, which are irrelevant here): this code path is the main contention culprit.
Switching to the concurrent version of `Set` fixes entirely the issue: no more contention detected in this area after applying the fix.
Fixes …
=> [WW-5119] Fix: remove contention during localized text lookup (JDK 1.8+)

core/src/main/java/com/opensymphony/xwork2/util/AbstractLocalizedTextProvider.java
Backport of pull request #476 for Struts 2.5.x (JDK 1.7 still supported in this branch).
The `ConcurrentHashMap.newKeySet()` usage (available only in JDK 1.8+) is replaced by a `ConcurrentHashMap<String,Boolean>` to guarantee JDK 1.7 compatibility.
Fixes [WW-5119](https://issues.apache.org/jira/browse/WW-5119)
=> [WW-5119] Fix: remove contention during localized text lookup (JDK 1.7+)

core/src/main/java/com/opensymphony/xwork2/inject/Scope.java
Fixes the contention issue described in WW-5121 by applying a double-null-check-with-volatile pattern to avoid the `synchronized` cost on each and every injection of the singleton.
This pull request applies to branch master (Struts 2.6.x).
=> [WW-5121] Fix: remove contention during Scope.SINGLETON injection

apps/showcase/src/main/resources/template/ajaxErrorContainers/controlfooter.ftl, apps/showcase/src/main/resources/template/ajaxErrorContainers/controlheader-core.ftl, core/src/main/resources/template/css_xhtml/checkbox.ftl, core/src/main/resources/template/css_xhtml/controlfooter.ftl, core/src/main/resources/template/css_xhtml/controlheader-core.ftl, core/src/main/resources/template/simple/css.ftl, core/src/main/resources/template/simple/fielderror.ftl, core/src/main/resources/template/xhtml/checkbox.ftl, core/src/main/resources/template/xhtml/controlfooter.ftl, core/src/main/resources/template/xhtml/controlheader-core.ftl, core/src/test/java/org/apache/struts2/views/jsp/ui/TextfieldTest.java, core/src/test/resources/org/apache/struts2/views/jsp/ui/Textfield-WW-5125.txt
All [ occurrences in all ftl files reviewed. Only fieldErrors had used [...] which replaced by .get(...) to fix WW-5125 as well as aligning with other ftl files conduct.
=> [WW-5125] use .get(...) instead of [...] for fieldErrors

core/src/main/java/com/opensymphony/xwork2/interceptor/ModelDrivenInterceptor.java, core/src/test/java/com/opensymphony/xwork2/interceptor/ModelDrivenInterceptorTest.java
due to refreshing model regardless of potential overridden Object.equals
=> [WW-5126] use == instead of .equals in ModelDrivenInterceptor

core/src/main/java/com/opensymphony/xwork2/config/providers/XmlConfigurationProvider.java
Hello,
Our static analyzer found a following potential NPE. We have checked the feasibility of this execution trace. It is necessary to defend this vulnerability to improve the code quality.
Here is the bug trace.
1. Return **null** to caller
https://github.com/apache/struts/blob/cb318cdc749f40a06eaaeed789a047f385a55480/core/src/main/java/com/opensymphony/xwork2/util/DomHelper.java#L226
2. Function **getDocument** executes and the return value can be **null**
https://github.com/apache/struts/blob/cb318cdc749f40a06eaaeed789a047f385a55480/core/src/main/java/com/opensymphony/xwork2/util/DomHelper.java#L123
3. Function **parse** executes and pass the return value as the parameter of **add**, which can be **null**
https://github.com/apache/struts/blob/cb318cdc749f40a06eaaeed789a047f385a55480/co …
=> Fix NPE in XmlConfigurationProvider.java

plugins/rest/src/test/java/org/apache/struts2/rest/handler/JacksonXmlHandlerTest.java
Hi,
By running the following command:
`mvn -pl plugins/rest/ edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.struts2.rest.handler.JacksonXmlHandlerTest `,
`testObjectToXml` method will fail sometimes. This is because `fromObject()` method of `JacksonXmlHandler` uses `com.fasterxml.jackson.dataformat.xml.XmlMapper`, whose marshal strategy that serializes the object is non-deterministic. Thus, the output of `toString()` method of the serialized xml object is non-deterministic. I fixed the bug by checking the output contains all components of the xml object and the expected length.
=> fixed flakiness in JacksonXmlHandlerTest.java

core/src/main/resources/template/simple/doubleselect.ftl, core/src/main/resources/template/simple/dynamic-attributes.ftl, core/src/main/resources/template/simple/inputtransferselect.ftl, core/src/main/resources/template/simple/optiontransferselect.ftl, core/src/main/resources/template/simple/prefixed-dynamic-attributes.ftl, core/src/main/resources/template/simple/select.ftl, core/src/test/java/org/apache/struts2/views/freemarker/FreemarkerResultMockedTest.java, core/src/test/java/org/apache/struts2/views/jsp/ui/DoubleSelectTest.java, core/src/test/java/org/apache/struts2/views/jsp/ui/InputTransferSelectTagTest.java, core/src/test/java/org/apache/struts2/views/jsp/ui/OptionTransferSelectTagTest.java, core/src/test/resources/org/apache/struts2/views/jsp/ui/DoubleSelect-5.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/inputtransferselect-2.txt, core/src/test/resources/org/apache/struts2/views/jsp/ui/optiontransferselect-8.txt
Implements [WW-5129](https://issues.apache.org/jira/browse/WW-5129)
Follows up of #495
=> [WW-5129] Supports dynamic attributes in second control

core/src/test/java/org/apache/struts2/views/freemarker/FreemarkerResultMockedTest.java
Fixed the flaky test testDynamicAttributesSupport due to non-deterministic order of two attributes.
This flaky test is found by using [Nondex](https://github.com/TestingResearchIllinois/NonDex), a tool used to find flaky tests in Java projects. In the first two elements of the expected string, the order of the two attributes, ```foo``` and ```placeholder```, is non-deterministic, which means ```foo``` can be either before or after ```placeholder```. To make the test pass every time, all 4 possible orders are covered in the assertion.
=> Fix flaky test testDynamicAttributesSupport.

pom.xml
Hello,
It seems Apache struts is affected by the [log4j vulnerability](https://www.lunasec.io/docs/blog/log4j-zero-day/). I've shared my findings with the security team privately where you could review the vulnerable code paths. 
Fixes [WW-5151](https://issues.apache.org/jira/browse/WW-5151)
=> [WW-5151] Bump to 2.15.0 to fix log4j vulnerability

apps/rest-showcase/src/main/webapp/WEB-INF/content/orders-deleteConfirm.jsp, apps/rest-showcase/src/main/webapp/WEB-INF/content/orders-edit.jsp, apps/rest-showcase/src/main/webapp/WEB-INF/content/orders-editNew.jsp, apps/rest-showcase/src/main/webapp/WEB-INF/content/orders-index.jsp, apps/rest-showcase/src/main/webapp/WEB-INF/content/orders-show.jsp
Update:
- Fix REST Showcase JSP issue for s:link tags that replaced HTML link tags.
- s:link tags cannot use JSP EL in them.  Modified JSPs to use scriptlet, JSP expression, and OGNL expression to work with s:link tag.
=> REST Showcase fix for broken JSPs using S2 link tags

core/src/main/java/org/apache/struts2/components/CheckboxList.java, core/src/main/java/org/apache/struts2/components/ListUIBean.java, core/src/main/java/org/apache/struts2/components/Radio.java, core/src/main/java/org/apache/struts2/components/UIBean.java, core/src/main/java/org/apache/struts2/components/template/FreemarkerTemplateEngine.java, core/src/main/resources/template/simple/checkboxlist.ftl, core/src/main/resources/template/simple/dynamic-attributes.ftl, core/src/main/resources/template/simple/radiomap.ftl, core/src/test/java/org/apache/struts2/views/jsp/ui/TextfieldTest.java, core/src/test/resources/org/apache/struts2/views/jsp/ui/Textfield-5.txt
This PR introduces conditional lazy evaluation of some tag's attributes (e.g.: _dynamic attributes_) to avoid double evaluation vulnerability.
Reverts changes in #475 and fixes [WW-5117](https://issues.apache.org/jira/browse/WW-5117)
=> [WW-5117] Evaluates dynamic attributes

core/src/main/java/org/apache/struts2/components/Checkbox.java, core/src/main/java/org/apache/struts2/components/Component.java, core/src/main/java/org/apache/struts2/components/UIBean.java, plugins/javatemplates/src/main/java/org/apache/struts2/views/java/Attributes.java, plugins/javatemplates/src/main/java/org/apache/struts2/views/java/simple/AnchorHandler.java, plugins/javatemplates/src/main/java/org/apache/struts2/views/java/simple/CheckboxHandler.java, plugins/javatemplates/src/main/java/org/apache/struts2/views/java/simple/LinkHandler.java, plugins/javatemplates/src/main/java/org/apache/struts2/views/java/simple/ResetHandler.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/AnchorTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/CheckboxTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/FileTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/HiddenTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/LinkTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/PasswordTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/SelectTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/SubmitTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/TextAreaTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/TextFieldTest.java
Fixes [WW-5168](https://issues.apache.org/jira/browse/WW-5168)
Closes #530
=> [WW-5168] Support submit unchecked in Javatemplates and fixes logic for FTL template

core/src/main/java/com/opensymphony/xwork2/config/providers/StrutsDefaultConfigurationProvider.java, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/main/java/org/apache/struts2/components/Date.java, core/src/main/java/org/apache/struts2/components/date/DateFormatter.java, core/src/main/java/org/apache/struts2/components/date/DateTimeFormatterAdapter.java, core/src/main/java/org/apache/struts2/components/date/SimpleDateFormatAdapter.java, core/src/main/java/org/apache/struts2/config/StrutsBeanSelectionProvider.java, core/src/main/resources/org/apache/struts2/default.properties, core/src/main/resources/struts-default.xml, core/src/test/java/org/apache/struts2/components/DateTest.java, core/src/test/java/org/apache/struts2/views/jsp/ui/DateTagTest.java
Relates to [WW-5016](https://issues.apache.org/jira/browse/WW-5016)
=> [WW-5016] Adds support for LocalDate and adjusts tests to use the new Java 8 API

core/src/main/java/com/opensymphony/xwork2/conversion/impl/DateConverter.java, core/src/main/java/com/opensymphony/xwork2/conversion/impl/XWorkBasicConverter.java, core/src/main/java/com/opensymphony/xwork2/interceptor/ParametersInterceptor.java, core/src/test/java/com/opensymphony/xwork2/conversion/impl/DateConverterTest.java
Add support for LocalDateTime for the LocalDateTime.now() variant. DateTimeFormatter.ISO_LOCAL_DATE_TIME.
See [WW-5175](https://issues.apache.org/jira/browse/WW-5175)
=> Basic LocalDateTime support

core/src/main/resources/org/apache/struts2/default.properties, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java
Refs [WW-5179](https://issues.apache.org/jira/browse/WW-5179)
=> [WW-5179] Set default value of struts.ognl.expressionMaxLength to 256

core/src/main/java/org/apache/struts2/views/jsp/ui/TextareaTag.java, core/src/main/resources/template/simple/textarea.ftl, core/src/test/java/org/apache/struts2/views/jsp/ui/TextareaTest.java, core/src/test/resources/org/apache/struts2/views/jsp/ui/Textarea-1.txt
Fixes [WW-5191](https://issues.apache.org/jira/browse/WW-5191)
=> [WW-5191] Fixes placement of maxLength and minLength attributes in <s:textarea/> tag

apps/showcase/pom.xml, apps/showcase/src/main/java/org/apache/struts2/showcase/source/ViewSourceAction.java, apps/showcase/src/main/resources/log4j2.xml, apps/showcase/src/main/resources/struts-dispatcher.xml, apps/showcase/src/main/resources/struts.xml, apps/showcase/src/main/webapp/WEB-INF/decorators/main.jsp, apps/showcase/src/main/webapp/WEB-INF/dispatcher/dispatch-result.jsp, apps/showcase/src/main/webapp/WEB-INF/viewSource.jsp, apps/showcase/src/main/webapp/WEB-INF/web.xml, apps/showcase/src/test/java/it/org/apache/struts2/showcase/DispatcherResultTest.java, core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java, core/src/main/java/org/apache/struts2/dispatcher/filter/StrutsPrepareAndExecuteFilter.java, core/src/main/java/org/apache/struts2/dispatcher/mapper/DefaultActionMapper.java, core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java
This PR addresses a problem with forwarding to another JSP or action, but only in case if `StrutsExecuteAndPrepareFilter` is used - when combination of `StrutsPrepareFilter` & `StrutsExecuteFilter` is used; forwarding to actions won't work - it's a large problem and will be [addressed](https://issues.apache.org/jira/browse/WW-5199) separately, this never worked tbh. 
Fixes [WW-5190](https://issues.apache.org/jira/browse/WW-5190)
=> [WW-5190] Fixes StackOverflowException when dispatching request

pom.xml
b/c 6.1 has reached its end-of-life according to
https://hibernate.org/validator/releases/6.1/
6.2 is compatible with the given Java and Jakarta
versions and supports `javax.validation.*` according to
https://hibernate.org/validator/releases/6.2/
=> WW-5208 Update hibernate-validator to 6.2.4

plugins/rest/src/main/java/org/apache/struts2/rest/ContentTypeInterceptor.java
In commit e9d0a5518cd0671d9ad0353a2c87246ef0d2061b ContentTypeHandlerManager has been changed from setter-injected to constructor-injected.
However, at least with spring as the object factory, that bean was an internal bean not available from the factory, injected post construction.
In the 6.0.0 implementation ContentTypeInterceptor cannot be instantiated since its dependency cannot be resolved:
```
org.springframework.beans.factory.UnsatisfiedDependencyException
Error creating bean with name 'org.apache.struts2.rest.ContentTypeInterceptor': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apache.struts2.rest.ContentTypeHandlerManager' available: expected …
```
=> [WW-5205] - Reverting injection refactor of internal bean

core/src/main/java/org/apache/struts2/interceptor/csp/DefaultCspSettings.java
Fixes [WW-5203](https://issues.apache.org/jira/browse/WW-5203)
=> [WW-5203] Re-builds policy string on each call

core/src/main/java/com/opensymphony/xwork2/config/impl/DefaultConfiguration.java, core/src/main/java/com/opensymphony/xwork2/config/providers/StrutsDefaultConfigurationProvider.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/resources/org/apache/struts2/default.properties, core/src/main/resources/struts-default.xml, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java, core/src/test/java/org/apache/struts2/config/StrutsJavaConfigurationProviderTest.java, core/src/test/java/org/apache/struts2/config/TestBeanSelectionProvider.java
Hello Apache Struts Team.
This is an initial attempt to fix the dependency-injection behaviour for the custom expression and BeanInfo cache factory mechanism introduced in 6.0.0 (was 2.6).  It took a fair amount of debugging and playing with configuration values to arrive at a small number of changes.
With these changes, and a custom implementation, it seems that `Container` `getInstance(type, name)` will now return the custom implementation.  That is an improvement, but the default container instance construction of `OgnlUtil` still seems to use the default implementations (so it seems something is still missing at this point).
Please advise if anyone can see additional changes that might resolve the remaining issue(s) for custom cache factory assignment.
=> [WW-5173] - Attempt to fix DI behaviour for custom cache factories

core/src/main/java/com/opensymphony/xwork2/interceptor/ParameterValueAware.java, core/src/main/java/com/opensymphony/xwork2/interceptor/ParametersInterceptor.java, core/src/test/java/com/opensymphony/xwork2/interceptor/ParametersInterceptorTest.java
Implements [WW-5184](https://issues.apache.org/jira/browse/WW-5184)
* Add optional parameter value check to ParametersInterceptor
* Add Unit Tests
=> WW-5184 - Add optional parameter value check to ParametersInterceptor

core/src/main/java/org/apache/struts2/dispatcher/mapper/DefaultActionMapper.java
Fixes [WW-5242](https://issues.apache.org/jira/browse/WW-5242)
=> [WW-5242] Marks struts.mapper.action.prefix.crossNamespaces as deprecated

core/src/main/java/com/opensymphony/xwork2/config/providers/StrutsDefaultConfigurationProvider.java, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/main/java/org/apache/struts2/config/StrutsBeanSelectionProvider.java, core/src/main/java/org/apache/struts2/url/ParametersStringBuilder.java, core/src/main/java/org/apache/struts2/url/StrutsParametersStringBuilder.java, core/src/main/java/org/apache/struts2/views/util/DefaultUrlHelper.java, core/src/main/resources/org/apache/struts2/default.properties, core/src/main/resources/struts-default.xml, core/src/test/java/org/apache/struts2/interceptor/exec/StrutsBackgroundProcessTest.java, core/src/test/java/org/apache/struts2/url/StrutsParametersStringBuilderTest.java, core/src/test/java/org/apache/struts2/url/StrutsUrlDecoderTest.java, core/src/test/java/org/apache/struts2/url/StrutsUrlEncoderTest.java, core/src/test/java/org/apache/struts2/views/util/DefaultUrlHelperTest.java, plugins/json/src/test/java/org/apache/struts2/json/JSONActionRedirectResultTest.java
This PR fixes the issue plus extracts logic related to building a query string into a new class and defines a new extension point which then can be used by users to provide their own implementations.
Closes [WW-4514](https://issues.apache.org/jira/browse/WW-4514)
=> [WW-4514] Fixes building query string with empty parameters

core/src/main/resources/template/simple/doubleselect.ftl, core/src/main/resources/template/simple/select.ftl, core/src/test/java/org/apache/struts2/views/jsp/ui/DoubleSelectTest.java, core/src/test/resources/org/apache/struts2/views/jsp/ui/DoubleSelect-6.txt
This allows assign custom JS event handlers to the second select box
Closes [WW-5240](https://issues.apache.org/jira/browse/WW-5240)
=> [WW-5240] Uses doubleOn* attributes in the template

plugins/pell-multipart/pom.xml
Closes [WW-5274](https://issues.apache.org/jira/browse/WW-5274)
=> [WW-5274] Marks the Pell multipart plugin as deprecated

apps/showcase/src/main/java/org/apache/struts2/showcase/servlet/TestServlet.java, apps/showcase/src/main/resources/struts.xml, apps/showcase/src/main/webapp/WEB-INF/web.xml, apps/showcase/src/test/java/it/org/apache/struts2/showcase/ForwardTest.java, core/src/main/java/org/apache/struts2/dispatcher/PrepareOperations.java, core/src/main/java/org/apache/struts2/dispatcher/filter/StrutsExecuteFilter.java, core/src/main/java/org/apache/struts2/dispatcher/filter/StrutsPrepareAndExecuteFilter.java, core/src/main/java/org/apache/struts2/dispatcher/filter/StrutsPrepareFilter.java, core/src/main/java/org/apache/struts2/dispatcher/servlet/StrutsServlet.java, core/src/test/java/org/apache/struts2/dispatcher/PrepareOperationsTest.java
=> WW-5270 Fix forwarding from Struts excluded URL

core/src/main/java/com/opensymphony/xwork2/validator/AbstractActionValidatorManager.java, core/src/main/java/com/opensymphony/xwork2/validator/AnnotationActionValidatorManager.java, core/src/main/java/com/opensymphony/xwork2/validator/DefaultActionValidatorManager.java
=> WW-5278 Collect duplicated code into AbstractActionValidatorManager

core/src/main/java/com/opensymphony/xwork2/config/providers/XmlConfigurationProvider.java, core/src/main/java/com/opensymphony/xwork2/inject/Scope.java, core/src/main/java/org/apache/struts2/config/StrutsXmlConfigurationProvider.java
=> WW-5279 Improve readability of XmlConfigurationProvider class

core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/main/java/org/apache/struts2/config/entities/ConstantConfig.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java, core/src/main/resources/org/apache/struts2/default.properties, core/src/main/resources/org/apache/struts2/struts-messages.properties, core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java, plugins/pell-multipart/src/main/java/org/apache/struts2/dispatcher/multipart/PellMultiPartRequest.java, pom.xml
Upgrades commons-fileupload to ver. 1.5 and sets default limit to 256 files
Closes [WW-5285](https://issues.apache.org/jira/browse/WW-5285)
=> [WW-5285] Limits max number of files to upload at once

core/src/main/java/com/opensymphony/xwork2/config/ConfigurationManager.java, core/src/main/java/com/opensymphony/xwork2/config/ContainerProvider.java, core/src/test/java/com/opensymphony/xwork2/config/ConfigurationManagerTest.java, core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java
WW-5290
--
Apart from improving the readability and maintainability of this class, this refactor fixes some logic issues and prevents improper use. It enforces thread safety and also improves performance, specifically on initialisation. We no longer do 2 reloads unnecessarily in certain scenarios.
I've additionally ran these changes through the Confluence DC test suite and everything is passing. :)
=> WW-5290 Refactor ConfigurationManager

core/src/main/java/com/opensymphony/xwork2/config/ConfigurationManager.java, core/src/main/java/org/apache/struts2/dispatcher/PrepareOperations.java, core/src/main/java/org/apache/struts2/dispatcher/filter/StrutsExecuteFilter.java, core/src/main/java/org/apache/struts2/dispatcher/filter/StrutsPrepareAndExecuteFilter.java, core/src/main/java/org/apache/struts2/dispatcher/filter/StrutsPrepareFilter.java, core/src/test/java/org/apache/struts2/dispatcher/PrepareOperationsTest.java, core/src/test/java/org/apache/struts2/dispatcher/StrutsPrepareAndExecuteFilterIntegrationTest.java, core/src/test/java/org/apache/struts2/dispatcher/TwoFilterIntegrationTest.java
WW-5292
--
I copied this [existing commit](https://github.com/apache/struts/commit/6651089e823d2d2934f0597ab690ea9322f584e3) to the two filter setup.
I also included some assorted fixes in this PR, including cherry-picks from the rejected #663.
=> WW-5292 Allow overriding of Operations classes in two filter setup and assorted clean up

core/src/main/java/com/opensymphony/xwork2/config/providers/XmlConfigurationProvider.java, core/src/main/java/com/opensymphony/xwork2/config/providers/XmlDocConfigurationProvider.java, core/src/main/java/org/apache/struts2/config/StrutsXmlConfigurationProvider.java, core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java, core/src/test/java/com/opensymphony/xwork2/config/providers/XmlConfigurationProviderTest.java
WW-5293
--
I've split XmlConfigurationProvider into a superclass XmlDocsConfigurationProvider. The original XmlConfigurationProvider now extends XmlDocsConfigurationProvider to provide filesystem specific loading functionality. The new XmlDocsConfigurationProvider can be instantiated on its own by feeding in a parsed XML document directly.
Additionally:
- Deprecated some old constructors/methods so that they can be safely deleted in Struts 7.0
- Allowed greater flexibility in subclassing by splitting the build action/interceptor/result configs into their own methods
- Fixed a minor existing bug where `#registerBeanSelection` did not respect the ObjectFactory configured class loader
- Fixed a minor bug introduced in #657 where an unhandled exception is thrown when calling `#loadPackages` …
=> WW-5293 Allow loading XML configuration from other than filesystem

core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java, core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java, plugins/velocity/src/main/resources/struts-deferred.xml
=> WW-5301 Fix custom VelocityManager bean selection

core/src/main/java/org/apache/struts2/dispatcher/SessionMap.java, core/src/main/java/org/apache/struts2/interceptor/ExecuteAndWaitInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/exec/StrutsBackgroundProcess.java, core/src/test/java/org/apache/struts2/dispatcher/SessionMapTest.java
Update:
- Improve ExecuteAndWaitInterceptor state behaviour, added debug and trace logging.
- Ensure StrutsBackgroundProcess thread done state always set on completion.
- Fix SessionMap processing issue caused by divergence of method signatures, which can result in the ancestor methods getting called (bypassing actual session processing).
- Update SessionMapTest to correspond to changes, add tests to try and detect some (put/remove) method signature behaviour changes.
=> [WW-5312] Attempt to fix ExecuteAndWaitInterceptor inconsistent processing

core/src/main/java/org/apache/struts2/url/StrutsQueryStringParser.java, core/src/test/java/org/apache/struts2/url/StrutsQueryStringParserTest.java
Fixes [WW-5310](https://issues.apache.org/jira/browse/WW-5310)
=> [WW-5310] Properly parses param value with equal sign

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessTest.java
Update:
- Add a few additional tests to SecurityMemberAccessTest.
- Rename some existing tests involving non-static methods to more accurately reflect that.
- Add one minor optimization to SecurityMemberAccess.
=> WW-5288 follow-up test case updates

core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java
WW-5314
--
Bad requests from users or attackers can flood the logs with stack traces.
=> WW-5314 Do not log warnings for bad user input from JakartaMultiPartRequest

pom.xml
fixes last Reproducible Builds issue after #555
= https://issues.apache.org/jira/browse/FELIX-6602
see checks https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/struts/README.md
=> upgrade Felix Maven Bundle Plugin

core/src/main/java/com/opensymphony/xwork2/interceptor/ParametersInterceptor.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/main/java/com/opensymphony/xwork2/util/MemberAccessValueStack.java, core/src/main/resources/struts-excluded-classes.xml, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessTest.java, core/src/test/java/org/apache/struts2/util/SecurityMemberAccessInServletsTest.java, plugins/spring/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessProxyTest.java, plugins/spring/src/test/java/com/test/SecurityMemberAccessProxyTest.java
Closes [WW-5327](https://issues.apache.org/jira/browse/WW-5327)
Closes #567
=> [WW-5327] Stop using JavaBeans notation for setters in SecurityMemberAccess & MemberAccessValueStack

CODEOWNERS
[About code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
=> Defines a proper CODEOWNERS file

core/src/main/java/org/apache/struts2/util/StrutsUtil.java, core/src/main/java/org/apache/struts2/views/freemarker/FreemarkerManager.java, core/src/main/java/org/apache/struts2/views/jsp/ui/OgnlTool.java, core/src/main/java/org/apache/struts2/views/util/ContextUtil.java, core/src/main/resources/struts-beans.xml, core/src/main/resources/struts.vm, core/src/test/java/org/apache/struts2/util/StrutsUtilTest.java, plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityManager.java, plugins/velocity/src/test/java/org/apache/struts2/views/velocity/VelocityManagerTest.java
WW-5336
--
I couldn't see any value in retaining OgnlTool as its own class so I've deprecated it and merged the method into StrutsUtil.
=> WW-5336 Deprecate OgnlTool

plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityManager.java
WW-5334
--
Following #731, there are excessive log warnings arising from this. `Unable to instantiate chained VelocityContext`
=> WW-5334 Fix empty chained context names in VelocityManager

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilStrutsTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessTest.java, core/src/test/java/com/test/ExternalSecurityMemberAccess.java
WW-5341
--
In applications where there are multiple classloaders, it may be possible for `SecurityMemberAccess` to obtain a false negative if the classloader used to load the target object was different to the one used to load the exclusion list.
To rectify this, we use String comparison of the class name instead. We still use the default classloader to validate the exclusion list on application start. A future enhancement might be to make the validating classloader configurable.
=> WW-5341 Ensure exclusion list applies to objects from all ClassLoaders

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessTest.java
=> WW-5342 Add option to block use of default package

core/src/main/java/com/opensymphony/xwork2/ognl/accessor/CompoundRootAccessor.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java
=> WW-5339 Misc clean up in CompoundRootAccessor and OgnlValueStackTest

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlReflectionProvider.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java
WW-5340
--
I've refactored this class to improve both readability and maintainability.
My primary goal was to consolidate calls to ognl.Ognl, specifically the following functions:
* `#getValue`: 5 calls to 1
* `#setValue`: 2 calls to 1
* `#parseExpression`: 4 calls to 1
Functionally, there are only 2 changes:
* Removed redundant tree validation from `OgnlUtil#setValue`
* Cache expressions prior to tree validation (i.e. even if validation fails)
=> WW-5340 Preliminary refactor of OgnlUtil

plugins/cdi/src/main/java/org/apache/struts2/cdi/CdiObjectFactory.java
with the recommended alternative, because it was deprecated in CDI 1.1 and removed in [CDI 4.0](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html) (Jakarta EE 10).
This resolves the CDI plugin's only hard incompatibility with Jakarta EE 10.
It can then be used in Jakarta EE 10 applications provided the package names are adapted (e.g. using [Eclipse Transformer](https://github.com/eclipse/transformer)).
=> [WW-5346] replace BeanManager::createInjectionTarget

.github/workflows/sonar.yml
Pull requests from forked repos cannot run the Sonar scan due to restricted secret access. To avoid a situation where we miss a failing test on JDK17, I've split the Sonar scan into its own job. It is also less confusing for contributors.
I've additionally replaced the `cache` step with the preset cache configuration in the `setup-java` step.
=> Split SonarCloud into separate action

core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java, core/src/main/java/org/apache/struts2/ognl/StrutsOgnlGuard.java
WW-5340
--
Quick follow-up to https://github.com/apache/struts/pull/747
See comments
=> WW-5340 Mild refactor StrutsOgnlGuard for easier subclassing

core/src/main/java/org/apache/struts2/components/UIBean.java, core/src/test/java/org/apache/struts2/components/UIBeanTest.java
WW-5349
--
For applications that don't use components such as Action and Set, or templates which leverage OGNL variable references, `#attr.templateDir` and `#attr.theme` are the only 2 dependencies on this OGNL capability.
By removing this functionality, applications can block `ognl.ASTVarRef` using `struts.ognl.excludedNodeTypes` for strengthened security. This is a commonly used gadget by attackers.
=> WW-5349 Remove Struts core dependency on OGNL VarRefs

apps/rest-showcase/pom.xml, apps/showcase/pom.xml, plugins/portlet/pom.xml, pom.xml
I'm unable to build the project locally due to `asm:asm` being on the classpath. I've cleaned up some other stuff in the process.
=> Fix conflicting dependencies

core/src/main/java/org/apache/struts2/url/StrutsUrlDecoder.java
- StutsUrlDecoder has performance problems when run from multiple threads, because [Charset#availavleCharts(...)](https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/java.base/share/classes/java/nio/charset/Charset.java#L569-L588) called `StrutsUrlDecoder#getCharset(...)` is synchronized blocked.
- Root causes is synchronized blocked at [AbstractCharsetProvider#charsets()](https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/jdk.charsets/share/classes/sun/nio/cs/ext/AbstractCharsetProvider.java#L174-L177) .
- StutsUrlDecoder is used to evaluate custom tag [<s:url>](https://struts.apache.org/tag-developers/url-tag), it will have performance problems if it receives too many requests.
- Therefore, `Charset#availavleCharts(...)` to be executed only once during the StrutsUrlDecoder …
=> Improved the StrutsUrlDecoder so that charset retrieval is performed only once.

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/test/java/com/opensymphony/xwork2/interceptor/ParametersInterceptorTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessTest.java
WW-5350
--
See comments.
I didn't deprecate methods for which I've changed the signature as from what I can tell `SecurityMemberAccess` is not considered public API (no reasonable situation in which a Struts applications would need to override or instantiate the class themselves, nor is it a defined extensible bean) (WW-5343 aims to make it a configurable bean and thus public API).
=> WW-5350 Refactor SecurityMemberAccess

core/src/main/java/org/apache/struts2/components/Set.java, core/src/main/java/org/apache/struts2/dispatcher/AttributeMap.java, core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java, core/src/main/java/org/apache/struts2/dispatcher/DispatcherConstants.java, core/src/main/java/org/apache/struts2/dispatcher/RequestMap.java, core/src/main/java/org/apache/struts2/interceptor/debugging/DebuggingInterceptor.java, core/src/main/java/org/apache/struts2/views/jsp/TagUtils.java, core/src/main/java/org/apache/struts2/views/util/ContextUtil.java, core/src/test/java/org/apache/struts2/dispatcher/AttributeMapTest.java, plugins/portlet/src/main/java/org/apache/struts2/portlet/dispatcher/Jsr168Dispatcher.java
Closes [WW-5333](https://issues.apache.org/jira/browse/WW-5333)
=> [WW-5333] Refactors AttributeMap

.github/workflows/scorecards-analysis.yaml
Only the main branch is supported by this action, partially reverts changes introduced in #785 
Refs [WW-5335](https://issues.apache.org/jira/browse/WW-5335)
=> [WW-5335] Reverts adding release/struts-7-0-x branch to scorecards analysis

plugins/velocity/src/main/java/org/apache/struts2/views/velocity/StrutsVelocityContext.java, plugins/velocity/src/test/java/org/apache/struts2/views/velocity/StrutsVelocityContextTest.java
WW-5363
--
This method is redundant because `com.opensymphony.xwork2.ognl.OgnlValueStack#tryFindValue(java.lang.String)` already falls back to looking in the context.
=> WW-5363 Remove redundant method from VelocityManager

core/src/main/java/com/opensymphony/xwork2/config/impl/DefaultConfiguration.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStackFactory.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/CompoundRootAccessor.java, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/main/resources/struts-beans.xml, core/src/test/java/com/opensymphony/xwork2/ognl/MyCustomMap.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java
WW-5339
--
Having consulted with a security researcher - there is still some risk here if there exists a custom map implementation whose `java.util.Map` methods pose some risk. This is because `ognl.MapPropertyAccessor#getProperty` does not consult the `MemberAccess` policy for the inherent `java.util.Map` methods.
Given Struts does not rely on custom OGNL Map implementations, we should add an option to block this capability.
=> WW-5339 Add option to block custom OGNL maps

core/src/main/java/org/apache/struts2/dispatcher/HttpParameters.java, core/src/main/java/org/apache/struts2/dispatcher/Parameter.java, core/src/test/java/org/apache/struts2/dispatcher/HttpParametersTest.java
Closes [WW-5370](https://issues.apache.org/jira/browse/WW-5370)
=> [WW-5370] Makes HttpParameters case-insensitive

apps/showcase/src/main/java/org/apache/struts2/showcase/fileupload/FileUploadAction.java, apps/showcase/src/main/webapp/WEB-INF/fileupload/upload-success.jsp, core/src/main/java/org/apache/struts2/action/UploadedFilesAware.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/StrutsUploadedFile.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/UploadedFile.java, core/src/main/java/org/apache/struts2/interceptor/AbstractFileUploadInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/ActionFileUploadInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/FileUploadInterceptor.java, core/src/main/resources/org/apache/struts2/struts-messages_en.properties, core/src/main/resources/struts-default.xml, core/src/test/java/org/apache/struts2/conversion/UploadedFileConverterTest.java, core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java, core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java, plugins/pell-multipart/src/main/java/org/apache/struts2/dispatcher/multipart/PellMultiPartRequest.java
This PR implements a new upload mechanism which uses a dedicated callback interface to pass info about uploaded files.
Closes [WW-5371](https://issues.apache.org/jira/browse/WW-5371)
=> [WW-5371] Modern upload

.mvn/wrapper/maven-wrapper.properties, Jenkinsfile, apps/showcase/pom.xml, apps/showcase/src/test/java/it/org/apache/struts2/showcase/FileUploadTest.java, core/src/main/java/org/apache/struts2/action/UploadedFilesAware.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/MultiPartRequestWrapper.java, core/src/main/java/org/apache/struts2/interceptor/ActionFileUploadInterceptor.java, core/src/main/resources/org/apache/struts2/struts-messages.properties, core/src/test/java/com/opensymphony/xwork2/config/providers/ConfigurationProviderOgnlAllowlistTest.java, core/src/test/java/com/opensymphony/xwork2/ognl/MyCustomMap.java, core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java, core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java, core/src/test/java/org/apache/struts2/util/SecurityMemberAccessInServletsTest.java, core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowlist-2.xml, core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowlist.xml, plugins/junit/src/main/java/org/apache/struts2/junit/StrutsTestCase.java
Rebases struts-7-0-x branch to be up to date with the master branch.
=> Rebase struts-7-0-x branch

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java
WW-5364
--
Fix for the following in the showcase app - thanks @lukaszlenart for noticing
```
[WARN ] ognl.SecurityMemberAccess (SecurityMemberAccess.java:205) - Declaring class [interface java.util.Map$Entry] of member type [public abstract java.lang.Object java.util.Map$Entry.getKey()] is not allowlisted!
```
=> WW-5364 Add missing system allowlist classes

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStackFactory.java, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java
WW-5378
--
The Struts OGNL context is powerful but also a security nightmare - this option allows applications to disable its access completely when used alongside OGNLGuard with `ognl.ASTVarRef,ognl.ASTThisVarRef` configured.
=> WW-5378 Add option to NOT fallback to context lookup when finding value on OgnlValueStack

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java
WW-5364
--
This class is often used in validation logic and is not dangerous so makes sense to add to the system allowlist.
=> WW-5364 Add String.class to system allowlist

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStackFactory.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/CompoundRootAccessor.java, core/src/main/java/com/opensymphony/xwork2/ognl/accessor/RootAccessor.java
WW-5381
--
Introducing a new interface prior to implementing an extension point for the CompoundRootAccessor
=> WW-5381 Introduce RootAccessor interface for extension point

core/src/main/java/org/apache/struts2/util/ValueStackProvider.java, plugins/velocity/src/main/java/org/apache/struts2/views/velocity/StrutsVelocityContext.java, plugins/velocity/src/main/java/org/apache/struts2/views/velocity/components/AbstractDirective.java, plugins/velocity/src/test/java/org/apache/struts2/views/velocity/StrutsVelocityContextTest.java
WW-5379
--
This affords applications the ability to not include the ValueStack as `$stack` in the Velocity context and reduce risk of SSTI escalation.
=> WW-5379 Implement alternative mechanism for Velocity directives to obtain ValueStack

plugins/convention/src/main/java/org/apache/struts2/convention/PackageBasedActionConfigBuilder.java
Closes [WW-5383](https://issues.apache.org/jira/browse/WW-5383)
=> [WW-5383] Updates RegEx to excludes JARs by default

core/src/main/java/com/opensymphony/xwork2/security/AcceptedPatternsChecker.java, core/src/main/java/com/opensymphony/xwork2/security/ExcludedPatternsChecker.java, core/src/main/java/org/apache/struts2/dispatcher/Parameter.java, core/src/main/java/org/apache/struts2/interceptor/ActionMappingParametersInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/parameter/ParametersInterceptor.java, core/src/test/java/org/apache/struts2/interceptor/parameter/ParametersInterceptorTest.java
WW-5352
--
General clean up in preparation for #832
=> WW-5352 Refactor ParametersInterceptor

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStackFactory.java
See an [example PR run](https://github.com/apache/struts/actions/runs/7442031148/job/20244935590?pr=836) to notice enormous number of the log entries as this is happening for each unit test.
=> Reduces log level to debug to reduce noise in the logs

core/src/main/java/com/opensymphony/xwork2/XWorkTestCase.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java
WW-5352
--
Made these tests more consistent and maintainable.
=> WW-5352 Clean up OgnlValueStackTest

core/src/main/java/org/apache/struts2/dispatcher/ApplicationMap.java, core/src/main/java/org/apache/struts2/dispatcher/RequestMap.java, plugins/portlet/src/main/java/org/apache/struts2/portlet/PortletApplicationMap.java
Fixes [WW-5387](https://issues.apache.org/jira/browse/WW-5387)
=> [WW-5387] Fixes remove() signature

assembly/src/main/assembly/min-lib.xml
This PR adds missing `caffeine-x.x.x.jar` &  `javassist-x.x.x.jar`
[WW-5369](https://issues.apache.org/jira/browse/WW-5369)
=> [WW-5369] Re-define minimal library set

core/src/main/java/org/apache/struts2/interceptor/csp/CspInterceptor.java, core/src/test/java/org/apache/struts2/interceptor/CspInterceptorTest.java
Prepends `reportUri` with servlet context by default
Closes [WW-5374](https://issues.apache.org/jira/browse/WW-5374)
=> [WW-5374] Allows to prepend reportUri with Servlet context

core/src/test/java/org/apache/struts2/interceptor/exec/StrutsBackgroundProcessTest.java
This test quite often breaks the [builds](https://ci-builds.apache.org/job/Struts/job/Struts%20Core/job/master/342/console)
```
[ERROR] Failures: 
[ERROR]   StrutsBackgroundProcessTest.testMultipleProcesses:118 Process is still active: StrutsBackgroundProcess { name = Order: 17 }
```
=> Extends sleep period to avoid breaking a build

core/src/main/resources/template/simple/a-close.ftl, core/src/test/java/org/apache/struts2/views/jsp/ui/AnchorTest.java, core/src/test/resources/org/apache/struts2/views/jsp/ui/href-6.txt
PR adds missing support for the `disabled` attribute to the Anchor tag.
[WW-5357](https://issues.apache.org/jira/browse/WW-5357)
=> [WW-5357] Adds support for disabled attribute to anchor tag

src/etc/project-suppression.xml
Uses proper exclusion definition of plexus container which is already deprecated.
=> Fixes excluding Plexus container in OWASP scan

apps/showcase/src/main/java/org/apache/struts2/showcase/UITagExample.java, apps/showcase/src/main/java/org/apache/struts2/showcase/action/ParamsAnnotationAction.java, apps/showcase/src/main/java/org/apache/struts2/showcase/action/SkillAction.java, apps/showcase/src/main/java/org/apache/struts2/showcase/async/ChatRoomAction.java, apps/showcase/src/main/java/org/apache/struts2/showcase/conversion/AddressAction.java, apps/showcase/src/main/java/org/apache/struts2/showcase/conversion/OperationsEnumAction.java, apps/showcase/src/main/java/org/apache/struts2/showcase/conversion/PersonAction.java, apps/showcase/src/main/java/org/apache/struts2/showcase/filedownload/FileDownloadAction.java, apps/showcase/src/main/java/org/apache/struts2/showcase/fileupload/FileUploadAction.java, apps/showcase/src/main/java/org/apache/struts2/showcase/model/MyDto.java, apps/showcase/src/main/java/org/apache/struts2/showcase/validation/FieldValidatorsExampleAction.java, apps/showcase/src/main/java/org/apache/struts2/showcase/wait/LongProcessAction.java, apps/showcase/src/main/resources/struts-params-annotation.xml, apps/showcase/src/main/resources/struts.xml, apps/showcase/src/main/webapp/WEB-INF/paramsannotation.vm, apps/showcase/src/test/java/it/org/apache/struts2/showcase/StrutsParametersTest.java, core/src/main/java/com/opensymphony/xwork2/config/impl/DefaultConfiguration.java, core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/main/java/com/opensymphony/xwork2/security/DefaultAcceptedPatternsChecker.java, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/main/java/org/apache/struts2/components/IteratorComponent.java, core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java, core/src/main/java/org/apache/struts2/interceptor/parameter/ParametersInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/parameter/StrutsParameter.java, core/src/main/java/org/apache/struts2/ognl/ThreadAllowlist.java, core/src/main/java/org/apache/struts2/views/jsp/ComponentTagSupport.java, core/src/main/resources/struts-beans.xml, core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessTest.java, core/src/test/java/org/apache/struts2/components/IteratorComponentTest.java, core/src/test/java/org/apache/struts2/interceptor/parameter/StrutsParameterAnnotationTest.java
WW-5352
--
The final piece of the Struts 6.4 security overhaul. When this capability is enabled alongside the OGNL allowlist, security is greatly heightened with no additional complex configuration.
In addition to assisting OGNL allowlist configuration, the primary benefit of this new annotation is that it prevents inexperienced Struts developers from inadvertently introducing parameter injection points - as they often do not realise any public members on an Action class are parameter injectable. All parameter injection points will need to be explicitly annotated.
The OGNL allowlist capability can already be enabled using `struts.allowlist.enable`. It was introduced (#781) alongside the configuration options `struts.allowlist.classes` and `struts.allowlist.packageNames` using which you …
=> WW-5352 Introducing the StrutsParameter annotation

core/src/main/java/org/apache/struts2/views/jsp/IteratorStatus.java, core/src/test/java/com/opensymphony/xwork2/test/User.java, core/src/test/java/org/apache/struts2/TestAction.java, core/src/test/java/org/apache/struts2/components/IteratorComponentTest.java, core/src/test/java/org/apache/struts2/views/jsp/IteratorTagTest.java
Direct output of `<s:iterator/>` tag is automatically converted from Integer to String by the internal conversion mechanism. In some languages this isn't a desired behaviour as you still want to use a proper european numbers when generating HTML tags. To overcome this problem you can use `countStr` and `indexStr` (**hint**: propose a better naming) to avoid the conversion.
This will allow to produce a proper form:
```jsp
<s:iterator begin="1" end="3" status="status">
<s:property/>
<s:textfield id="text_%{#status.countStr}" name="test[%{#status.indexStr}]"/>
</s:iterator>
```
```html
۰
<input type="text" name="test[0]" value="" id="text_1">
۱
<input type="text" name="test[1]" value="" id="text_2">
۲
<input type="text" name="test[2]" value="" id="text_3">
```
Closes …
=> [WW-5360] Introduces additional countStr & indexStr to allow to ignore conversion

apps/showcase/src/main/java/org/apache/struts2/showcase/fileupload/FileUploadAction.java, apps/showcase/src/main/resources/struts-fileupload.xml, apps/showcase/src/main/webapp/WEB-INF/fileupload/upload-success.jsp, apps/showcase/src/test/java/it/org/apache/struts2/showcase/FileUploadTest.java, core/pom.xml, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/main/java/org/apache/struts2/action/UploadedFilesAware.java, core/src/main/java/org/apache/struts2/config/entities/ConstantConfig.java, core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/MultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/MultiPartRequestWrapper.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/StrutsUploadedFile.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/UploadedFile.java, core/src/main/java/org/apache/struts2/interceptor/ActionFileUploadInterceptor.java, core/src/test/java/org/apache/struts2/config/SettingsTest.java, core/src/test/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequestTest.java, core/src/test/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequestTest.java, core/src/test/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequestTest.java, core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java, core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java, core/src/test/resources/log4j2.xml, pom.xml
Closes [WW-5388](https://issues.apache.org/jira/browse/WW-5388)
=> [WW-5388] Uses the latest JakartaEE FileUpload Servlet 6 package

plugins/config-browser/src/main/java/org/apache/struts2/config_browser/ShowBeansAction.java, plugins/osgi/src/main/java/org/apache/struts2/osgi/OsgiConfigurationProvider.java, plugins/portlet/src/main/java/org/apache/struts2/portlet/result/PortletVelocityResult.java, plugins/sitemesh/src/main/java/org/apache/struts2/sitemesh/OldDecorator2NewStrutsVelocityDecorator.java, plugins/sitemesh/src/main/java/org/apache/struts2/sitemesh/VelocityDecoratorServlet.java, plugins/sitemesh/src/main/java/org/apache/struts2/sitemesh/VelocityPageFilter.java, plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityBeanSelectionProvider.java, plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityManager.java, plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityManagerInterface.java, plugins/velocity/src/main/java/org/apache/struts2/views/velocity/result/VelocityResult.java, plugins/velocity/src/main/java/org/apache/struts2/views/velocity/template/VelocityTemplateEngine.java, plugins/velocity/src/main/resources/struts-plugin.xml
WW-5391
--
Allows applications to provide a completely custom VelocityManager
=> WW-5391 Add interface for VelocityManager extension point

core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java, core/src/main/java/org/apache/struts2/interceptor/AbstractFileUploadInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/FileUploadInterceptor.java, core/src/main/resources/org/apache/struts2/struts-messages.properties, core/src/test/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequestTest.java, core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java, core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java
- removes duplicated validation messages where both interceptors have been used
- defines a proper error message on a general file upload exception
- removes generic definition in tests
Follow ups #861
Refs [WW-5388](https://issues.apache.org/jira/browse/WW-5388)
=> [WW-5388] Fixes a few issues in Servlet 6 file upload usage

core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java
Testing the original file upload and it now does not work.
I get an error where its using the wrong file name ie upload5549a568d9794ef5b654da83d079613500000045.tmp rather than the
actual file name.  This fixes the original upload.
I also modified one of my uploads to use the UploadedFilesAware.  To get the original file name to save on the server I use
```
for (int i = 0; i < uploads.size(); i++) {
String fileName = uploads.get(i).getOriginalName();
....
}
```
The method getOriginalName() text says "original file name from upload source" so it looks correct.
=> Fix original file upload to use actual file name rather than uploadxxx.tmp

core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java
Closes [WW-5401](https://issues.apache.org/jira/browse/WW-5401)
=> [WW-5401] Improves logging around wrapping request and detecting multipart request

core/src/main/java/org/apache/struts2/interceptor/ApplicationAware.java, core/src/main/java/org/apache/struts2/interceptor/HttpParametersAware.java, core/src/main/java/org/apache/struts2/interceptor/ParameterAware.java, core/src/main/java/org/apache/struts2/interceptor/PrincipalAware.java, core/src/main/java/org/apache/struts2/interceptor/RequestAware.java, core/src/main/java/org/apache/struts2/interceptor/ServletRequestAware.java, core/src/main/java/org/apache/struts2/interceptor/ServletResponseAware.java, core/src/main/java/org/apache/struts2/interceptor/SessionAware.java, core/src/main/java/org/apache/struts2/util/ServletContextAware.java, plugins/portlet/src/main/java/org/apache/struts2/portlet/interceptor/PortletContextAware.java, plugins/portlet/src/main/java/org/apache/struts2/portlet/interceptor/PortletPreferencesAware.java, plugins/portlet/src/main/java/org/apache/struts2/portlet/interceptor/PortletRequestAware.java, plugins/portlet/src/main/java/org/apache/struts2/portlet/interceptor/PortletResponseAware.java
Partially reverts https://github.com/apache/struts/pull/670 to restore compatibility with deprecated interfaces
Refs [WW-5251](https://issues.apache.org/jira/browse/WW-5251)
=> WW-5251 Reinstate deleted interfaces with transparent compat

core/pom.xml, core/src/main/java/com/opensymphony/xwork2/ognl/DefaultOgnlCacheFactory.java, core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/main/java/com/opensymphony/xwork2/util/ProxyUtil.java, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/main/java/org/apache/struts2/config/entities/ConstantConfig.java, plugins/spring/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessProxyTest.java
WW-5407 
--
**Reason**
Currently `SecurityMemberAccess#isAccessible` return true for a method of a proxy object, which expose the beans at risk of being changed. We need to have the ability to detect proxy object and reject the access if required.
See Jira card above for more details.
&nbsp;
**Changes/ Solution**
currently in  `isAccessible -> checkProxyMemberAccess` , it use `disallowProxyMemberAccess && ProxyUtil.isProxyMember(member, target)`  which is not enough, as `isProxyMember` only matches the member **directly** from proxy class, and does not match those ones **original** from the target class.
&nbsp;
So we update the `isAccessible`:
* add one extra checking `checkProxyAccess` before `checkProxyMemberAccess` which is controlled by:
* `struts.disallowProxyObjectAccess` : an new …
=> WW-5407 Extend SecurityMemberAccess proxy detection to other proxies

core/src/main/java/com/opensymphony/xwork2/XWorkTestCase.java, core/src/main/java/com/opensymphony/xwork2/config/impl/DefaultConfiguration.java, core/src/main/java/org/apache/struts2/StrutsConstants.java, core/src/main/java/org/apache/struts2/config/entities/ConstantConfig.java, core/src/main/resources/org/apache/struts2/default.properties, core/src/test/java/com/opensymphony/xwork2/config/ConfigurationTest.java, core/src/test/java/org/apache/struts2/views/jsp/ui/DebugTagTest.java
WW-5408
**Reason**
There is a case we want to enhance to improve security for struts url mapping: Be able to prevent arbitrary namespace fallback to empty (root) namespace when not match
&nbsp;
**Changes/ Solution**
*  introduce new Struts constant ` STRUTS_DISABLE_EMPTY_NAMESPACE_FALLBACK [struts.disableActionConfigFallbackToEmptyNamespace]` to disable fallback to empty namespace when not match
*  default as null which means does not disable (Need to manually set as true in confluence struts.xml)
&nbsp;
**Result & Impact**
* By default `struts.disableActionConfigFallbackToEmptyNamespace` is `null`, no difference.
* Set `struts.disableActionConfigFallbackToEmptyNamespace`  as `true`, not matched namepsace **WILL NOT** fallback to empty namespace anymore, and struts will threw …
=> WW-5408 add option to not fallback to empty namespace when unresolved

core/src/test/java/org/apache/struts2/ognl/OgnlSetPossiblePropertyTest.java, pom.xml
WW-5417
bump the Ognl version to fix the security issue that `ObjectPropertyAccessor#setPossibleProperty` bypass SecurityMemberAccess right check. 
&nbsp;
*********************** From [Ognl PR](https://github.com/orphan-oss/ognl/pull/264) ***********************
`OgnlRuntime.setFieldValue` doesn't check member access rights via `MemberAccess` interface
&nbsp;
**Reason**
* Investigation shows that `getMethodValue`/ `setMethodValue` / `getFieldValue` are all updated with member access rights check but not `setFieldValue`, which cause `ObjectPropertyAccessor#setPossibleProperty` expose to security vuln.
* `ObjectPropertyAccessor#setPossibleProperty` has a fallback mechanism using `getWriteMethod` which also lack member access rights check
&nbsp;
**Changes/ Solution**
* add field member …
=> WW-5417 bump ognl version to fix security issue

plugins/tiles/pom.xml, plugins/tiles/src/main/java/org/apache/struts2/tiles/StrutsTilesContainerFactory.java, plugins/tiles/src/main/java/org/apache/struts2/tiles/StrutsWildcardServletApplicationContext.java, plugins/tiles/src/test/java/org/apache/struts2/tiles/StrutsTilesContainerFactoryTest.java, plugins/tiles/src/test/java/org/apache/struts2/tiles/StrutsWildcardServletApplicationContextTest.java, plugins/tiles/src/test/resources/WEB-INF/tiles.xml, plugins/tiles/src/test/resources/org/apache/tiles/core/config/tiles_defs1.xml
Closes [WW-5419](https://issues.apache.org/jira/browse/WW-5419)
=> [WW-5419] Fixes support for loading Tiles definitions

core/src/main/java/org/apache/struts2/interceptor/csp/CspInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/csp/CspSettings.java, core/src/main/java/org/apache/struts2/interceptor/csp/DefaultCspSettings.java, core/src/test/java/org/apache/struts2/interceptor/CspInterceptorTest.java
Previously, it was impossible to set global options for the CSP interceptor. The only option was to have every action individually implement CspSettingsAware.
To fix this, we add an interceptor parameter of defaultCspSettingsClassName. Values from this class will be used in the CSP header instead of DefaultCspSettings. Users may define their own custom class which implements CspSettings, and that will be the default for all actions that do not implement the CspSettingsAware interface. It is now possible to create this custom class by simply extending DefaultCspSettings.
I have fixed a spelling error in DefaultCspSettings.java -- cratePolicyFormat renamed to createPolicyFormat.
Closes [WW-5400](https://issues.apache.org/jira/browse/WW-5400)
=> WW-5400 Extend default configuration options for the CSP interceptor.

core/pom.xml, core/src/main/java/org/apache/struts2/interceptor/exec/StrutsBackgroundProcess.java, core/src/test/java/org/apache/struts2/interceptor/exec/StrutsBackgroundProcessTest.java, pom.xml
Close [WW-5414](https://issues.apache.org/jira/browse/WW-5414)
=> WW-5414 Always call afterInvocation even in case of exception

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/test/java/com/opensymphony/xwork2/validator/VisitorFieldValidatorTest.java, core/src/test/java/com/opensymphony/xwork2/validator/VisitorValidatorTestAction.java, core/src/test/resources/com/opensymphony/xwork2/validator/VisitorValidatorTestAction-validation.xml
This PR fixes creating instances via OGNL expressions. The breaking change was introduced in #780
Closes [WW-5415](https://issues.apache.org/jira/browse/WW-5415)
=> WW-5415 Fixes accessing public constructors via expression

.asf.yaml
* this functionality requires to have public teams
* currently all ASF teams are private
You can find more info in the ticket [INFRA-25666](https://issues.apache.org/jira/browse/INFRA-25666)
=> INFRA-25666 Disables review by code owners

core/src/main/java/org/apache/struts2/components/Set.java, core/src/test/java/org/apache/struts2/views/jsp/SetTagTest.java
Closes [WW-5424](https://issues.apache.org/jira/browse/WW-5424)
=> [WW-5424] Fixes ClassCastException when using short var name in s:set tag

core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/MultiPartRequest.java, core/src/test/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequestTest.java
Fixes [WW-5423](https://issues.apache.org/jira/browse/WW-5423)
=> [WW-5423] Fixes returning null instead of empty array in case of non-existing param

core/src/main/java/org/apache/struts2/interceptor/csp/CspInterceptor.java, core/src/test/java/org/apache/struts2/interceptor/CspInterceptorTest.java
Small refactoring of how `CspSettings` class is created plus additional tests. See #913 for more details.
Closes [WW-5400](https://issues.apache.org/jira/browse/WW-5400)
=> WW-5400 Simplifies how CspSettings is created

core/src/main/java/com/opensymphony/xwork2/validator/ActionValidatorManager.java, core/src/main/java/com/opensymphony/xwork2/validator/DefaultActionValidatorManager.java, core/src/test/java/com/opensymphony/xwork2/validator/DefaultActionValidatorManagerTest.java
Closes [WW-5250](https://issues.apache.org/jira/browse/WW-5250)
=> WW-5250 Addresses TODO in test and stops using Mock Objects

core/src/main/java/org/apache/struts2/views/freemarker/FreemarkerManager.java
To be removed in Struts 7
Closes [WW-5431](https://issues.apache.org/jira/browse/WW-5431)
=> WW-5431 Marks unused constants as deprecated

core/src/main/java/com/opensymphony/xwork2/config/providers/EnvsValueSubstitutor.java
According to the documentation at https://struts.apache.org/core-developers/constant-configuration it should be possible to use both system and environment variables in the constants section. Currently environment variables are ignored if a default value is defined.
The sysStrSubstitutor has a less specific prefix which also includes and replaces those, which should be passed to the envStrSubstitutor later.
Given
`<constant name="struts.devMode" value="${env.STRUTS_DEV_MODE:false}"/>`
and System.getenv('STRUTS_DEV_MODE') is "true"
The old code:
```
String substituted = sysStrSubstitutor.replace(value);
return envStrSubstitutor.replace(substituted);
```
The sysStrSubstitutor checks, if there is a system property with the key "env.STRUTS_DEV_MODE" which is unset. It then replaces the …
=> WW-5437 Swap order of sysStrSubstitutor and envStrSubstitutor in substitute method

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/main/java/com/opensymphony/xwork2/util/ProxyUtil.java, core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessTest.java, plugins/spring/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessProxyTest.java
WW-5428
--
The OGNL allowlist capability cannot resolve proxy objects and thus will not work in applications where proxy objects such as Spring beans and Hibernate entities are accessed via OGNL.
Allowing access to such objects via OGNL is not recommended anyway as such access can be used to escalate an SSTI vulnerability.
However, given there seem to be many applications that still rely on accessing Hibernate entities directly, it would still offer much greater security in these cases, if the allowlist were enabled with exemptions for Hibernate proxies, rather than disabled altogether.
As such, in this PR, if an application is configured with `struts.disallowProxyObjectAccess=false`, the allowlist capability will resolve the underlying class of any Hibernate proxies and enforce the …
=> WW-5428 Allowlist capability should resolve Hibernate proxies when disableProxyObjects is not set

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java
WW-5428
--
As per title, this is too much logging, even in DevMode.
I can't think of a better place to put this right now so am deleting it. I considered the allowlist-enabled injection method but that also causes issues as we override that as false from OgnlUtil and that causes a false-positive warning.
=> WW-5428 Stop excessive logging in DevMode

core/src/main/java/com/opensymphony/xwork2/config/providers/XmlDocConfigurationProvider.java, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java
WW-5442
--
Previously, I had exempted the `OgnlReflectionProvider` from the allowlist due to some initialisation issues but I've fixed this now by updating the allowlist as each class is loaded when XML configuration is being read.
=> WW-5442 Enforce allowlist for OgnlReflectionProvider

apps/showcase/pom.xml, plugins/sitemesh/pom.xml, plugins/velocity/pom.xml, plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityManager.java, plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityTools.java, plugins/velocity/src/test/java/org/apache/struts2/views/velocity/VelocityManagerTest.java, plugins/velocity/src/test/resources/WEB-INF/webinf-velocity.properties, plugins/velocity/src/test/resources/test-velocity.properties
WW-5449
--
I suspect many applications that use the Velocity plugin don't need the Velocity Tools dependency. By extracting the Velocity Tools related functionality into a separate class `VelocityTools.java`, we give applications the ability to opt out. This class will only be initialised if `struts.velocity.toolboxlocation` is set.
Velocity Tools is also still needed if using certain SiteMesh or Tiles plugin functionality. This is the case for the Showcase app so I've added Velocity Tools as an explicit dependency in that pom.
I've also refactored `VelocityManager` to be more readable.
=> WW-5449 Make Velocity Tools dependency optional for Velocity plugin

core/src/main/java/org/apache/struts2/components/IteratorComponent.java, core/src/test/java/org/apache/struts2/components/IteratorComponentTest.java, core/src/test/java/org/apache/struts2/views/jsp/IteratorTagTest.java
PR fixes NPE
```
ERROR org.apache.struts2.dispatcher.DefaultDispatcherErrorHandler - Exception occurred during processing request: null
java.lang.NullPointerException: null
at org.apache.struts2.components.IteratorComponent.start(IteratorComponent.java:309) ~[struts2-core-6.4.0.jar:6.4.0]
...
```
Fixes [WW-5451](https://issues.apache.org/jira/browse/WW-5451)
=> WW-5451 Fixes NPE when iterator starts with null

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/main/java/com/opensymphony/xwork2/util/DebugUtils.java, core/src/main/java/org/apache/struts2/interceptor/parameter/ParametersInterceptor.java
WW-5454
--
This PR adds startup log warnings for disabling the following capabilities:
* OGNL class allowlist
* @StrutsParameter annotation requirement
=> WW-5454 Log warnings on startup for disabled critical security features

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java
WW-4062
--
Came across this old bug report - I tested this locally and it seems it is a valid concern. Now that we are using Caffeine, a potential cache attack should be less of a concern. In any case, that is probably preferable to repeated failed compilations.
=> WW-4062 Cache OgnlException thrown on compilation

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java
WW-4062
--
Follow-up for #1013 - I was looking at the flame graph for this particular code flow (this is before the previous PR was merged) and observed that filling the stack trace is the largest contributor. Thus, we can gain more performance here by not refreshing the stack trace for cached exceptions. Given most of these exceptions are caught silently I don't expect the lack of stack trace to be an issue. If the stack trace is necessary for debugging purposes, then we can temporarily disable caching using `struts.ognl.enableExpressionCache=false`.
As the Jira issue suggests - this is primarily an issue for applications using the Velocity integration where the `null` fallback behaviour results in these invalid OGNL expressions attempting to be compiled repeatedly.
=> WW-4062 Further optimisation of OgnlException caching

core/src/main/java/org/apache/struts2/RequestUtils.java, core/src/main/java/org/apache/struts2/components/Include.java, core/src/main/java/org/apache/struts2/components/ServletUrlRenderer.java, core/src/main/java/org/apache/struts2/dispatcher/DefaultDispatcherErrorHandler.java, core/src/main/java/org/apache/struts2/result/ServletDispatcherResult.java, core/src/main/java/org/apache/struts2/views/freemarker/FreemarkerManager.java, core/src/main/java/org/apache/struts2/views/util/DefaultUrlHelper.java, core/src/test/java/org/apache/struts2/result/ServletDispatcherResultTest.java, plugins/tiles/src/main/java/org/apache/tiles/web/util/TilesDispatchServlet.java
Uses already existing constants instead of string literals
Refs [WW-5450](https://issues.apache.org/jira/browse/WW-5450)
=> WW-5450 Uses existing Jakarta constants instead of free hand strings

.github/workflows/codeql.yml, .github/workflows/scorecards-analysis.yaml, apps/showcase/pom.xml, core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java, core/src/main/java/org/apache/struts2/components/IteratorComponent.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java, core/src/test/java/org/apache/struts2/components/IteratorComponentTest.java, core/src/test/java/org/apache/struts2/views/jsp/IteratorTagTest.java, pom.xml
Reverse merge all changes from the master branch
=> Merge master

apps/showcase/src/main/java/org/apache/struts2/showcase/fileupload/FileUploadAction.java, apps/showcase/src/main/webapp/WEB-INF/fileupload/upload-success.jsp, apps/showcase/src/test/java/it/org/apache/struts2/showcase/FileUploadTest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/StrutsUploadedFile.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/UploadedFile.java, core/src/test/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequestTest.java, core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java
Cherry-picked from #1040 plus some modifications
Closes [WW-5461](https://issues.apache.org/jira/browse/WW-5461)
=> WW-5461 Extends UploadedFile with inputName field

core/src/main/java/com/opensymphony/xwork2/mock/MockObjectTypeDeterminer.java, core/src/main/java/com/opensymphony/xwork2/util/ClassPathFinder.java, core/src/main/java/com/opensymphony/xwork2/util/PropertiesReader.java, core/src/main/java/org/apache/struts2/interceptor/debugging/DebuggingInterceptor.java
Closes [WW-5458](https://issues.apache.org/jira/browse/WW-5458)
=> WW-5458 Replaces e.printStackTrace() with proper logger

core/src/main/java/org/apache/struts2/components/UIBean.java, core/src/test/java/org/apache/struts2/components/UIBeanTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/AbstractTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/HeadTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/LinkTest.java, plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/ScriptTest.java
Closes [WW-5297](https://issues.apache.org/jira/browse/WW-5297)
=> WW-5297 Fixes checking nonce of invalidated session

apps/showcase/src/main/java/org/apache/struts2/showcase/modelDriven/ModelDrivenAction.java, core/src/main/java/com/opensymphony/xwork2/ModelDriven.java, core/src/main/java/org/apache/struts2/interceptor/parameter/ParametersInterceptor.java, core/src/test/java/com/opensymphony/xwork2/ModelDrivenAction.java, core/src/test/java/com/opensymphony/xwork2/ModelDrivenAnnotationAction.java, core/src/test/java/com/opensymphony/xwork2/interceptor/ModelDrivenInterceptorTest.java, core/src/test/java/com/opensymphony/xwork2/test/ModelDrivenAction2.java, core/src/test/java/com/opensymphony/xwork2/test/ModelDrivenAnnotationAction2.java, core/src/test/java/com/opensymphony/xwork2/test/subtest/NullModelDrivenAction.java, core/src/test/java/com/opensymphony/xwork2/validator/VisitorValidatorModelAction.java, core/src/test/java/org/apache/struts2/interceptor/parameter/StrutsParameterAnnotationTest.java, core/src/test/java/org/apache/struts2/result/StreamResultTest.java, plugins/bean-validation/src/test/java/org/apache/struts/beanvalidation/actions/ModelDrivenAction.java, plugins/bean-validation/src/test/java/org/apache/struts/beanvalidation/actions/ValidateGroupAction.java, plugins/junit/src/main/java/org/apache/struts2/junit/StrutsRestTestCase.java, plugins/rest/src/test/java/org/apache/struts2/rest/RestActionInvocationTest.java, plugins/spring/src/test/java/com/opensymphony/xwork2/ModelDrivenAction.java
WW-5468
--
The `@StrutsParameter` requirement was designed to protect against arbitrary getters and setters on the Action class from being invoked by users and/or attackers. However, if an Action is using a dedicated model object alongside the `ModelDrivenInterceptor`  (which ensures the Action is not on the root of the value stack) much of this risk is mitigated. I suggest we exempt this specific scenario from requiring the `@StrutsParameter` annotation.
Closes #1071
=> WW-5468 Exempt ModelDriven Actions from @StrutsParameter requirement

plugins/sitemesh/pom.xml, plugins/sitemesh/src/main/java/org/apache/struts2/sitemesh/FreemarkerDecoratorServlet.java, plugins/sitemesh/src/main/java/org/apache/struts2/sitemesh/VelocityDecoratorServlet.java
WW-5471
--
Marks the Struts Sitemesh plugin as deprecated
=> WW-5471 Marks Sitemesh plugin as deprecated

core/src/main/java/org/apache/struts2/interceptor/ActionFileUploadInterceptor.java, core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java, core/src/test/resources/log4j2.xml
WW-5473
--
This PR fixes potential problem when using multiple HttpRequestWrappers (eg. Sitemesh 3 integration) with file upload support in Struts.
=> WW-5473 Fixes examining multiple HttpServletWrappers to find MultiPartRequestWrapper

core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java, core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java, core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java
Hello Apache Struts Team.
This is a proposed mitigation for WW-5466.  It is unlikely that many users will encounter it given the default configuration normally sets `struts.multipart.maxStringLength` .
The proposed change is a basic guard, combined with some additional unit tests to confirm that processing works both when the configuration values have not been set, as well as when they have been set.
Please advise if anyone thinks the change should be considered, or needs additional consideration.
=> Potential mitigation for WW-5466

apps/showcase/pom.xml, core/src/test/java/org/apache/struts2/components/UIBeanTest.java, plugins/bean-validation/pom.xml, pom.xml
WW-5209
--
Uses 
```xml
<dependency>
<groupId>jakarta.validation</groupId>
<artifactId>jakarta.validation-api</artifactId>
<version>3.1.0</version>
</dependency>
```
=> WW-5209 Upgrade to Jakarta Bean Validation 3.1.0

core/src/main/java/org/apache/struts2/views/freemarker/FreemarkerManager.java, core/src/test/java/org/apache/struts2/components/UIBeanTest.java, core/src/test/java/org/apache/struts2/views/freemarker/FreemarkerManagerTest.java
WW-5427
--
This change should improve performance of Freemarker based templates
=> WW-5427 Upgrades Freemarker incompatible_improvements to version 2.3.33

core/src/main/java/com/opensymphony/xwork2/ActionContext.java, core/src/main/java/com/opensymphony/xwork2/ActionInvocation.java, core/src/main/java/com/opensymphony/xwork2/Result.java, core/src/main/java/com/opensymphony/xwork2/interceptor/ConditionalInterceptor.java, core/src/main/java/com/opensymphony/xwork2/interceptor/Interceptor.java, core/src/main/java/com/opensymphony/xwork2/interceptor/PreResultListener.java, core/src/main/java/org/apache/struts2/ActionContext.java, core/src/main/java/org/apache/struts2/ActionInvocation.java, core/src/main/java/org/apache/struts2/Result.java, core/src/main/java/org/apache/struts2/interceptor/ConditionalInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/Interceptor.java, core/src/main/java/org/apache/struts2/interceptor/PreResultListener.java, core/src/test/java/org/apache/struts2/views/jsp/ActionTagTest.java
WW-3714
--
This PR deprecates and provides repackaged replacements for the following APIs, ahead of their permanent migration in Struts 7.0:
- `com.opensymphony.xwork2.ActionInvocation`
- `com.opensymphony.xwork2.interceptor.PreResultListener`
Full backwards compatibility with the deprecated types are retained - I achieved this by doing the following:
1. Move 'old' class to new package
1. Update any imports in this moved class to replacement types if applicable/available
1. Create a class in the old package (where the original class was) which extends the new updated one
1. Add back any APIs/methods which are not inherited due to updated imports from (2)
1. Provide default implementations for inherited APIs/methods which were not present in the 'old' class, delegating to the APIs added …
=> WW-3714 Deprecate and repackage common APIs part 2

core/src/main/java/com/opensymphony/xwork2/DefaultActionInvocation.java, core/src/main/java/com/opensymphony/xwork2/factory/DefaultInterceptorFactory.java, core/src/main/java/com/opensymphony/xwork2/factory/DefaultResultFactory.java, core/src/main/java/com/opensymphony/xwork2/interceptor/ConditionalInterceptor.java, core/src/main/java/com/opensymphony/xwork2/interceptor/Interceptor.java, core/src/main/java/com/opensymphony/xwork2/interceptor/WithLazyParams.java, core/src/main/java/org/apache/struts2/factory/StrutsResultFactory.java
WW-3714
--
Ensure factory support for new Interceptor, Result interfaces introduced in #1079.
When Results and Interfaces are parsed and instantiated from XML configuration they are expected to be of the deprecated `com.opensymphony.xwork2` types. We want to also ensure the new `org.apache.struts2` types are supported. We cannot easily change the factory interface signatures without breaking compatibility for the associated extension points. Thus, we ensure these types are adapted within the default factory implementations instead. Additional helper code was needed to ensure that the marker interfaces `ReflectionExceptionHandler`, `WithLazyParams`, `ParamNameAwareResult` are still respected. This helper code can of course be completely discarded in Struts 7.0.
=> WW-3714 Deprecate and repackage common APIs part 2.5

core/src/main/java/com/opensymphony/xwork2/ActionEventListener.java, core/src/main/java/com/opensymphony/xwork2/ActionInvocation.java, core/src/main/java/com/opensymphony/xwork2/ActionProxy.java, core/src/main/java/org/apache/struts2/ActionEventListener.java, core/src/main/java/org/apache/struts2/ActionInvocation.java, core/src/main/java/org/apache/struts2/ActionProxy.java
WW-3714
--
This PR deprecates and provides repackaged replacements for the following APIs, ahead of their permanent migration in Struts 7.0:
- `com.opensymphony.xwork2.ActionProxy`
- `com.opensymphony.xwork2.ActionEventListener`
Please refer to #1081 for the techniques and methodology employed in this PR.
=> WW-3714 Deprecate and repackage common APIs part 3

core/src/main/java/com/opensymphony/xwork2/interceptor/PrefixMethodInvocationUtil.java, core/src/main/java/org/apache/struts2/interceptor/AliasInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/ChainingInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/ConversionErrorInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/DefaultWorkflowInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/ExceptionMappingInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/LoggingInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/ModelDrivenInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/ParameterRemoverInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/PrepareInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/ScopedModelDrivenInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/StaticParametersInterceptor.java, core/src/main/java/org/apache/struts2/result/StrutsResultSupport.java
WW-3714
--
This PR deprecates and provides repackaged replacements for the following APIs, ahead of their permanent migration in Struts 7.0:
- `com.opensymphony.xwork2.interceptor.AliasInterceptor`
- `com.opensymphony.xwork2.interceptor.ChainingInterceptor`
- `com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor`
- `com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor`
- `com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor`
- `com.opensymphony.xwork2.interceptor.LoggingInterceptor`
- `com.opensymphony.xwork2.interceptor.ModelDrivenInterceptor`
- `com.opensymphony.xwork2.interceptor.ParameterRemoverInterceptor`
- `com.opensymphony.xwork2.interceptor.PrepareInterceptor`
- `com.opensymphony.xwork2.interceptor.ScopedModelDrivenInterceptor`
- …
=> WW-3714 Deprecate and repackage common APIs part 6

apps/showcase/src/main/java/org/apache/struts2/showcase/modelDriven/ModelDrivenAction.java, core/src/main/java/org/apache/struts2/ModelDriven.java, core/src/main/java/org/apache/struts2/interceptor/parameter/ParametersInterceptor.java, core/src/test/java/com/opensymphony/xwork2/ModelDrivenAction.java, core/src/test/java/com/opensymphony/xwork2/ModelDrivenAnnotationAction.java, core/src/test/java/com/opensymphony/xwork2/interceptor/ModelDrivenInterceptorTest.java, core/src/test/java/com/opensymphony/xwork2/test/ModelDrivenAction2.java, core/src/test/java/com/opensymphony/xwork2/test/ModelDrivenAnnotationAction2.java, core/src/test/java/com/opensymphony/xwork2/test/subtest/NullModelDrivenAction.java, core/src/test/java/com/opensymphony/xwork2/validator/VisitorValidatorModelAction.java, core/src/test/java/org/apache/struts2/interceptor/parameter/StrutsParameterAnnotationTest.java, core/src/test/java/org/apache/struts2/result/StreamResultTest.java, plugins/bean-validation/src/test/java/org/apache/struts/beanvalidation/actions/ModelDrivenAction.java, plugins/bean-validation/src/test/java/org/apache/struts/beanvalidation/actions/ValidateGroupAction.java, plugins/junit/src/main/java/org/apache/struts2/junit/StrutsRestTestCase.java, plugins/rest/src/test/java/org/apache/struts2/rest/RestActionInvocationTest.java, plugins/spring/src/test/java/com/opensymphony/xwork2/ModelDrivenAction.java
=> WW-5468 Backport @StrutsParameter fix for ModelDriven Actions

core/src/main/java/com/opensymphony/xwork2/config/entities/ResultConfig.java, core/src/main/java/com/opensymphony/xwork2/config/impl/DefaultConfiguration.java, core/src/main/java/com/opensymphony/xwork2/factory/DefaultResultFactory.java, core/src/main/java/org/apache/struts2/ActionContext.java, core/src/test/java/com/opensymphony/xwork2/interceptor/ChainingInterceptorWithConfigTest.java, plugins/convention/src/test/java/org/apache/struts2/convention/PackageBasedActionConfigBuilderTest.java
WW-5478
--
I can't see any value in maintaining this class as it does the same thing as `StrutsResultFactory` minus support for the marker `ParamNameAwareResult`.
=> WW-5478 Deprecate DefaultResultFactory

core/src/main/java/org/apache/struts2/components/UIBean.java, core/src/test/java/org/apache/struts2/components/UIBeanTest.java
=> WW-5480 Warn against potential templating bug

core/src/main/java/com/opensymphony/xwork2/DefaultActionInvocation.java, core/src/main/java/com/opensymphony/xwork2/interceptor/AbstractInterceptor.java, core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java, core/src/main/java/org/apache/struts2/interceptor/TokenSessionStoreInterceptor.java, plugins/rest/src/main/java/org/apache/struts2/rest/RestActionInvocation.java
WW-3714
--
Whilst working on #1116, I noticed a minor issue with how overriding of classes that implement the old/deprecated `Result`/`Interceptor` interfaces behave.
Currently, if an application extends for example, `org.apache.struts2.result.HttpHeaderResult` and overrides the new signature `void execute(org.apache.struts2.ActionInvocation invocation)` instead of the old one `void execute(com.opensymphony.xwork2.ActionInvocation invocation)` - this override will have no effect.
The changes in this PR ensure the override will function as expected irrespective of whether the old or new signature is overridden. This works because the default implementation for the new signature in the old/deprecated interfaces is to delegate to the old signature.
=> WW-3714 Ensure correct delegation of deprecated API methods

core/src/main/java/org/apache/struts2/ActionContext.java, core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java, core/src/test/java/org/apache/struts2/result/ServletDispatcherResultTest.java
=> WW-5486 Fixes exposing params added by ServletDispatcherResult

core/src/main/java/org/apache/struts2/result/ServletDispatcherResult.java, core/src/test/java/org/apache/struts2/result/ServletDispatcherResultTest.java
=> WW-5463 Exposes final location as request attribute FORWARD_SERVLET_PATH

core/src/main/java/org/apache/struts2/components/ActionComponent.java, core/src/main/java/org/apache/struts2/components/Component.java, core/src/main/java/org/apache/struts2/components/Form.java, core/src/main/java/org/apache/struts2/components/Include.java, core/src/main/java/org/apache/struts2/components/Label.java, core/src/main/java/org/apache/struts2/components/ListUIBean.java, core/src/main/java/org/apache/struts2/components/ServletUrlRenderer.java, core/src/main/java/org/apache/struts2/components/UIBean.java, core/src/main/java/org/apache/struts2/components/URL.java
Instead of using parameters field directly, this PR uses getAttributes() instead to avoid coupling with internal Component state
Fixes [WW-5493](https://issues.apache.org/jira/browse/WW-5493)
=> WW-5493 Restores parameters and uses getAttributes()

core/src/main/java/com/opensymphony/xwork2/security/DefaultExcludedPatternsChecker.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java, core/src/test/java/com/opensymphony/xwork2/security/DefaultExcludedPatternsCheckerTest.java, core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java, core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java
=> WW-5501 Exclude malicious names

README.md
Link directly to https://struts.apache.org/commercial-support.html on the readme in the relevant section.
=> [readme] add link to struts site commercial support page

.github/workflows/sonar.yml
Right now Sonar scans are [skipped](https://github.com/apache/struts/actions/runs/12479769638/job/34829469378), because branch ref is wrong and basically not needed as Sonar can detect branch name itself.
=> Removes checking branch ref and removes branch name as not needed

core/src/main/java/org/apache/struts2/util/DebugUtils.java, core/src/test/java/org/apache/struts2/interceptor/parameter/ParametersInterceptorTest.java
[WW-5498](https://issues.apache.org/jira/browse/WW-5498)
Cherry picks 9d07c3b4c37031ddfecddd44d0a5057c9e6964fa in Struts 7
=> WW-5498 Adds devMode errors as action messages to avoid breaking validation logic

core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java, core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java
[WW-5500](https://issues.apache.org/jira/browse/WW-5500)
Cherry picks 575e4e8c9b0be2c1add1597099b7c2b90d93e5fa into Struts 7
=> WW-5500 Extends pattern to validate multipart uploads

core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java, core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java, core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java
WW-5501
PR only excludes malicious file names accepting any other.
=> WW-5501 Only exclude malicious file names

core/src/main/java/com/opensymphony/xwork2/inject/ContainerImpl.java, core/src/test/java/com/opensymphony/xwork2/inject/ContainerImplTest.java
=> WW-5512 Extends the container to support injecting optional parameters into constructor

core/src/main/java/org/apache/struts2/components/Debug.java, core/src/main/java/org/apache/struts2/interceptor/ExceptionMappingInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/debugging/DebuggingInterceptor.java, core/src/main/java/org/apache/struts2/ognl/SecurityMemberAccess.java, core/src/main/resources/org/apache/struts2/interceptor/debugging/browser.ftl, core/src/main/resources/org/apache/struts2/interceptor/debugging/webconsole.html, core/src/test/java/org/apache/struts2/StrutsJUnit4InternalTestCase.java, core/src/test/java/org/apache/struts2/interceptor/ExceptionMappingInterceptorTest.java, core/src/test/java/org/apache/struts2/interceptor/debugging/DebuggingInterceptorTest.java, core/src/test/java/org/apache/struts2/views/jsp/ui/DebugTagTest.java
=> WW-5517 Fixes <s:debug/> to be compatible with allowlist capability

core/src/main/java/org/apache/struts2/components/UIBean.java, core/src/main/java/org/apache/struts2/views/jsp/TagUtils.java, core/src/test/java/org/apache/struts2/components/UIBeanTagTest.java
WW-5516
--
This is a fix for a functionality regression introduced in #763. Instead of re-introducing the dependency on an OGNL context expression, we instead access the required attributes directly through Java instead. This fixes the regression whilst still allowing applications to block OGNL context access (expressions beginning with `#`) using `OgnlGuard` if they desire.
=> WW-5516 Fix TemplateDir and Theme fallback to Request/Session/Application attributes

plugins/convention/src/main/java/org/apache/struts2/convention/DefaultResultMapBuilder.java, plugins/convention/src/test/java/org/apache/struts2/convention/DefaultResultMapBuilderTest.java
Uses existing function to split input using comma
=> Improves code quality

core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java, core/src/main/resources/org/apache/struts2/struts-messages.properties, core/src/test/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequestTest.java, core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java
WW-5528
--
We add an error message to be returned by `org.apache.struts2.dispatcher.multipart.MultiPartRequest#getErrors` so we can notify users of why their upload failed.
=> WW-5528 Ensure multipart upload illegal characters reported as error

core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java, core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java, core/src/main/resources/org/apache/struts2/struts-messages.properties, core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java, core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java, plugins/pell-multipart/src/main/java/org/apache/struts2/dispatcher/multipart/PellMultiPartRequest.java
=> 6.7: WW-5528 Ensure multipart upload illegal characters reported as error

core/src/main/java/org/apache/struts2/ognl/SecurityMemberAccess.java, core/src/main/java/org/apache/struts2/util/ProxyUtil.java, core/src/test/java/org/apache/struts2/ognl/OgnlValueStackTest.java, plugins/spring/src/test/java/org/apache/struts2/spring/SpringProxyUtilTest.java
=> WW-5525 Fix NPE in ProxyUtil for SecurityMemberAccess originating static members

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java, core/src/main/java/com/opensymphony/xwork2/util/ProxyUtil.java, core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java, plugins/spring/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessProxyTest.java, plugins/spring/src/test/java/com/opensymphony/xwork2/spring/SpringProxyUtilTest.java
WW-5525
--
Cherry-pick #1214 and  #1201
=> 6.7: WW-5525 Fix NPE in ProxyUtil for SecurityMemberAccess originating static members

core/src/main/java/org/apache/struts2/components/TextField.java
=> WW-5529 Drops unused misleading setter setMaxLength in favor of setMaxlength

apps/pom.xml, apps/showcase/src/test/java/it/org/apache/struts2/showcase/StrutsParametersTest.java, core/pom.xml, plugins/bean-validation/pom.xml, plugins/cdi/pom.xml, plugins/cdi/src/test/java/org/apache/struts2/cdi/CdiObjectFactoryTest.java, plugins/jfreechart/pom.xml, plugins/jfreechart/src/test/java/org/apache/struts2/dispatcher/ChartResultTest.java, plugins/junit/pom.xml, plugins/rest/pom.xml, plugins/testng/pom.xml, plugins/tiles/pom.xml, plugins/velocity/pom.xml, plugins/velocity/src/test/java/org/apache/struts2/views/velocity/template/VelocityTemplateEngineTest.java, pom.xml
WW-5532
--
Dependencies:
- Spring: `6.0.13` -> `6.2.3`
- Hibernate-Validator: `8.0.1.Final` -> `8.0.2.Final`
Adopt BOMs:
- `jakarta.platform:jakarta.jakartaee-bom`
- `org.glassfish.jaxb:jaxb-bom`
- `org.springframework:spring-framework-bom`
- `org.apache.logging.log4j:log4j-bom`
- `com.fasterxml.jackson:jackson-bom`
Test dependencies:
- ByteBuddy: `1.16.1` -> `1.17.1`
- Mockito: `5.8.0` -> `5.15.2`
- AssertJ: `3.26.3` -> `3.27.3`
- TestNG: `7.5.1` -> `7.11.0`
Remove or minimise usages of deprecated test dependencies:
- `org.springframework:spring-test:4.3.0.RELEASE` -> `com.github.h-thurow:simple-jndi`
- EasyMock
- Mockobjects
Removed usages of Java EE 8 dependencies.
=> WW-5532 Upgrade and align various dependencies

.github/workflows/maven.yml, core/src/test/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequestTest.java, plugins/tiles/src/main/java/org/apache/tiles/el/ScopeELResolver.java, plugins/tiles/src/main/java/org/apache/tiles/el/TilesContextBeanELResolver.java, plugins/tiles/src/main/java/org/apache/tiles/el/TilesContextELResolver.java, pom.xml
WW-5533
--
This PR adds an additional build job which ensures compilation compatibility with the upcoming Jakarta EE 11 and Spring 7. It ensures we do not make any code changes which may break forwards compatibility with those releases (e.g. using an API which no longer exists in Jakarta EE 11 or Spring 7).
By using a profile, we can continue to compile against both Jakarta EE 10 and 11, avoiding the need for separate release branches for as long as practical.
This change does NOT ensure compatibility with Tomcat 11.0. That will likely require a follow-up change where we update our Showcase app to use Tomcat 10.1 (and override to 11.0 when the Jakarta EE 11 profile is activated).
Open to feedback on this approach
=> WW-5533 Add compilation support for Jakarta EE 11

core/pom.xml, core/src/main/java/org/apache/struts2/interceptor/ChainingInterceptor.java, core/src/main/java/org/apache/struts2/ognl/OgnlCache.java, core/src/main/java/org/apache/struts2/ognl/OgnlCaffeineCache.java, core/src/main/java/org/apache/struts2/ognl/OgnlDefaultCache.java, core/src/main/java/org/apache/struts2/ognl/OgnlLRUCache.java, core/src/main/java/org/apache/struts2/ognl/OgnlUtil.java, core/src/main/java/org/apache/struts2/util/ProxyUtil.java, core/src/test/java/org/apache/struts2/ognl/OgnlUtilTest.java, plugins/json/src/main/java/org/apache/struts2/json/DefaultJSONWriter.java
WW-5534
--
These changes prepare us for introducing Spring proxy support for the OGNL allowlist and `@StrutsParameter` capabilities in a follow-up PR. Refer to PR comments for details on changes.
=> WW-5534 Simplify ProxyUtil, add OgnlCache#computeIfAbsent

core/src/main/java/org/apache/struts2/interceptor/parameter/ParametersInterceptor.java, core/src/main/java/org/apache/struts2/ognl/SecurityMemberAccess.java, core/src/test/java/org/apache/struts2/interceptor/parameter/StrutsParameterAnnotationTest.java, core/src/test/java/org/apache/struts2/ognl/SecurityMemberAccessTest.java, plugins/spring/src/test/java/org/apache/struts2/ognl/SecurityMemberAccessProxyTest.java
WW-5534
--
This change fixes `@StrutsParameter` detection for Spring proxied Actions. It additionally adds optional support for resolving Spring proxies when enforcing the OGNL allowlist, alongside the existing support for resolving Hibernate proxies.
=> WW-5534 Allow @StrutsParameter recognition and OGNL allowlist for Spring proxies

core/src/main/java/org/apache/struts2/conversion/impl/DateConverter.java, core/src/main/java/org/apache/struts2/conversion/impl/XWorkBasicConverter.java, core/src/test/java/org/apache/struts2/conversion/impl/XWorkConverterTest.java
WW-5538
--
These patches allow DateConverter to handle OffsetDateTime conversions using the standard patterns for that data type. Testing code is included.
=> WW-5538 Add conversion handling for java.time.OffsetDateTime

apps/showcase/src/test/java/it/org/apache/struts2/showcase/ModelDrivenTest.java, core/src/main/java/org/apache/struts2/ModelDriven.java, core/src/main/java/org/apache/struts2/components/Debug.java, core/src/main/java/org/apache/struts2/components/IteratorComponent.java, core/src/main/java/org/apache/struts2/interceptor/ExceptionMappingInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/ModelDrivenInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/debugging/DebuggingInterceptor.java, core/src/main/java/org/apache/struts2/interceptor/parameter/ParametersInterceptor.java, core/src/main/java/org/apache/struts2/ognl/ThreadAllowlist.java, core/src/test/java/org/apache/struts2/interceptor/ModelDrivenInterceptorTest.java, core/src/test/java/org/apache/struts2/interceptor/parameter/StrutsParameterAnnotationTest.java
WW-5534
--
Unfortunately, the previous fix (#1237) was not reliable as `Introspector#getBeanInfo` would return slightly different things depending on the visibility of the class hierarchy.
I decided to simplify the exemption logic for `ModelDriven` Actions by moving the allowlisting code into `ModelDrivenInterceptor`, and have `ParametersInterceptor` skip the validation logic entirely when a `ModelDriven` Action was detected.
I've additionally introduced a helper method `ThreadAllowlist#allowClassHierarchy`, extracting some repeated code.
=> WW-5534 Proper fix ModelDriven parameter injection and allowlisting

core/src/main/java/org/apache/struts2/interceptor/AbstractFileUploadInterceptor.java, core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java, core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java
=> WW-5546 Fixes NPE when uploaded file is empty

core/src/main/java/org/apache/struts2/result/ServletDispatcherResult.java, core/src/test/java/org/apache/struts2/result/ServletDispatcherResultTest.java
=> WW-5548 Defines proper request attributes when forwarding or including final path

core/src/main/java/org/apache/struts2/factory/StrutsConverterFactory.java
It should delegate back to ObjectFactory#buildBean instead of directly calling Container#inject, otherwise overrides of buildBean in subclasses of ObjectFactory e.g. SpringObjectFactory are skipped; meaning that TypeConverters cannot make use of Spring dependency injection
Fixes: https://issues.apache.org/jira/projects/WW/issues/WW-5524
=> WW-5524 Fixup StrutsConverterFactory

core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java
Closes [WW-5502](https://issues.apache.org/jira/browse/WW-5502)
=> WW-5502 Removes deprecated sanitizeNewlines method
