apache/struts

xwork-core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java
xwork-core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java

The previous fix was incomplete.

WW-4427 - Converters are no longer applied to values coming from the context on error path

---

core/src/main/java/org/apache/struts2/components/Checkbox.java
core/src/main/java/org/apache/struts2/components/CheckboxList.java
core/src/main/java/org/apache/struts2/components/Radio.java
core/src/main/resources/template/simple/checkbox.ftl
core/src/main/resources/template/simple/radiomap.ftl
core/src/site/resources/tags/checkbox.html
core/src/site/resources/tags/checkboxlist.html
core/src/site/resources/tags/radio.html

Readonly attribute is ignored in radio and checkbox inputs.

WW-4499 - Removed readonly attribute from radio, checkbox and checkboxlist tags.

---

plugins/json/src/main/java/org/apache/struts2/json/JSONResult.java
plugins/json/src/main/java/org/apache/struts2/json/JSONUtil.java
plugins/json/src/main/java/org/apache/struts2/json/JSONWriter.java
plugins/json/src/test/java/org/apache/struts2/json/JSONResultTest.java
plugins/json/src/test/java/org/apache/struts2/json/JSONUtilTest.java

Adds support for disabling bean cache on JSON plugin when devMode is enabled.

WW-4516: Allow JSON plug-in to skip bean cache when devMode is enabled.

---

core/src/main/java/org/apache/struts2/util/ContainUtil.java

Add more defense, like compare Enum to String or else.

Uniform comparison

---

core/src/main/java/com/opensymphony/xwork2/conversion/impl/DateConverter.java

RFC 3399 does not exist. RFC 3339 is the one used here: https://tools.ietf.org/html/rfc3339

Adding support for RFC3339 dates with only the date part

---

core/src/main/resources/template/xhtml/form-close-validate.ftl
core/src/test/java/com/opensymphony/xwork2/validator/EmailValidatorTest.java

Fix makes email validation regex case insensitive.

Email validation blocks upper case letters

---

core/pom.xml
plugins/json/src/main/java/org/apache/struts2/json/JSONReader.java
pom.xml

blank double results in NumberFormatException being thrown on sending
JSON in request body

fix for WW-4269, ww-4576, ww-4577

---

plugins/jasperreports/src/main/java/org/apache/struts2/views/jasperreports/JasperReportsResult.java

Now the connection is closed after been used.

Patch WW-3462 connection open after report generation

---

plugins/jasperreports/src/main/java/org/apache/struts2/views/jasperreports/JasperReportsResult.java
plugins/json/src/main/java/org/apache/struts2/json/JSONResult.java

Now the Json encoding by default is utf-8

WW-3945 Json default encoding UTF-8

---

plugins/jasperreports/pom.xml
plugins/jasperreports/src/main/java/org/apache/struts2/views/jasperreports/JasperReportsResult.java

Also I accidentally revert the Patch WW-3462 so here is the fix again

Patch WW-4381  upgrade to jasperreports 6.0

---

core/src/main/java/org/apache/struts2/components/IteratorComponent.java

Allow null values in the iterator tag

Patch WW-4312  A problem on Iterator tag

---

plugins/rest/src/main/java/org/apache/struts2/rest/DefaultContentTypeHandlerManager.java
plugins/rest/src/test/java/org/apache/struts2/rest/DefaultContentTypeHandlerManagerTest.java

Lukasz
here is a proposed enhancement to implement WW-4588.

WW-4588:  Improve the Struts2 Rest plugin to honor Accept header

---

core/src/main/java/org/apache/struts2/components/UIBean.java

change "cssStyle" to "cssErrorStyle"

fix spelling error in comments

---

core/src/main/java/org/apache/struts2/components/ServletUrlRenderer.java

At least that's what Webwork used to do

action parameters should be included when building the URL to action

---

core/pom.xml

[issue WW-4690](https://issues.apache.org/jira/browse/WW-4690)

WW-4690 added version to jshint-maven-plugin

---

core/src/main/java/org/apache/struts2/dispatcher/Parameter.java
core/src/test/java/org/apache/struts2/dispatcher/ParameterTest.java

WW-4737 Properly handle arrays containing nulls

---

core/src/main/java/org/apache/struts2/interceptor/I18nInterceptor.java

These changes prevent Struts to create session for request when it tries to check if request's session has pre-putted locale. It returns null instead if the request has no valid HttpSession.

[WW-4741] Do not force session creation on locale read operation

---

plugins/dojo/src/main/resources/org/apache/struts2/static/dojo/dojo.js
plugins/dojo/src/main/resources/org/apache/struts2/static/dojo/dojo.js.uncompressed.js
plugins/dojo/src/main/resources/org/apache/struts2/static/dojo/struts_dojo.js.uncompressed.js

[WW-4770](https://issues.apache.org/jira/browse/WW-4770)

WW-4770 Fixes problem with dojo.version

---

core/src/main/java/com/opensymphony/xwork2/validator/validators/DoubleRangeFieldValidator.java
core/src/main/java/com/opensymphony/xwork2/validator/validators/FieldValidatorSupport.java
core/src/main/java/com/opensymphony/xwork2/validator/validators/RangeValidatorSupport.java
core/src/main/java/com/opensymphony/xwork2/validator/validators/RegexFieldValidator.java
core/src/main/java/com/opensymphony/xwork2/validator/validators/RequiredFieldValidator.java
core/src/main/java/com/opensymphony/xwork2/validator/validators/RequiredStringValidator.java
core/src/main/java/com/opensymphony/xwork2/validator/validators/StringLengthFieldValidator.java
core/src/main/java/com/opensymphony/xwork2/validator/validators/URLValidator.java
core/src/main/java/com/opensymphony/xwork2/validator/validators/ValidatorSupport.java
core/src/test/java/com/opensymphony/xwork2/validator/DoubleRangeFieldValidatorTest.java
core/src/test/java/com/opensymphony/xwork2/validator/RegexFieldValidatorTest.java
core/src/test/java/com/opensymphony/xwork2/validator/StringLengthFieldValidatorTest.java
core/src/test/java/com/opensymphony/xwork2/validator/URLValidatorTest.java
core/src/test/java/com/opensymphony/xwork2/validator/validators/IntRangeFieldValidatorTest.java
core/src/test/java/com/opensymphony/xwork2/validator/validators/RequiredFieldValidatorTest.java
core/src/test/java/com/opensymphony/xwork2/validator/validators/RequiredStringValidatorTest.java
core/src/test/java/com/opensymphony/xwork2/validator/validators/ValidationAction.java

This PR adds support for validation of Collections in field validators
Resolves [WW-4578](https://issues.apache.org/jira/browse/WW-4578)

WW-4578: Multidimensional validation

---

core/src/main/java/com/opensymphony/xwork2/interceptor/DefaultWorkflowInterceptor.java
core/src/main/java/com/opensymphony/xwork2/interceptor/annotations/AnnotationWorkflowInterceptor.java
core/src/main/java/com/opensymphony/xwork2/util/AnnotationUtils.java
core/src/main/java/org/apache/struts2/components/Component.java
core/src/main/java/org/apache/struts2/interceptor/validation/AnnotationValidationInterceptor.java
core/src/test/java/com/opensymphony/xwork2/util/AnnotationUtilsTest.java
core/src/test/java/com/opensymphony/xwork2/util/annotation/DummyClass.java
core/src/test/java/com/opensymphony/xwork2/util/annotation/DummyClassExt.java
core/src/test/java/com/opensymphony/xwork2/util/annotation/DummyInterface.java
core/src/test/java/com/opensymphony/xwork2/util/annotation/MyAnnotationI.java
plugins/bean-validation/src/main/java/org/apache/struts/beanvalidation/validation/interceptor/BeanValidationInterceptor.java
pom.xml

During resolution of WW-4744 and WW-4694, I duplicated some works with annotations into Apache commons lang. Now, they just released them 😃 So this PR removes them from S2 which make it more light and decreases it's tests execution time 👌

WW-4744 WW-4694 Removes annotation search to commons lang 3.6

---

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java
core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java
core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessProxyTest.java
core/src/test/resources/com/opensymphony/xwork2/spring/actionContext-xwork.xml
plugins/spring/src/main/resources/struts-plugin.xml

add constant to control proxy member access

---

xwork-core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java
xwork-core/src/main/java/com/opensymphony/xwork2/util/ProxyUtil.java
xwork-core/src/test/java/com/opensymphony/xwork2/spring/ActionsFromSpringTest.java
xwork-core/src/test/resources/com/opensymphony/xwork2/spring/actionContext-xwork.xml

Ports only security related changes of #142 to branch support-2-3

WW-4805 Ports some of PR #142 changes to branch support-2-3

---

plugins/spring/src/main/resources/struts-plugin.xml
xwork-core/src/main/java/com/opensymphony/xwork2/XWorkConstants.java
xwork-core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java
xwork-core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java
xwork-core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java
xwork-core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessProxyTest.java
xwork-core/src/test/resources/com/opensymphony/xwork2/spring/actionContext-xwork.xml

Ports #146 to branch support-2-3.

WW-4805: Adds constant to control proxy member access (support-2-3)

---

core/src/main/java/com/opensymphony/xwork2/ObjectFactory.java
core/src/main/java/com/opensymphony/xwork2/conversion/ConversionPropertiesProcessor.java
core/src/main/java/com/opensymphony/xwork2/conversion/impl/DefaultConversionPropertiesProcessor.java
core/src/main/java/com/opensymphony/xwork2/conversion/impl/XWorkConverter.java
core/src/main/java/com/opensymphony/xwork2/inject/ContainerBuilder.java
core/src/main/java/com/opensymphony/xwork2/inject/Initializable.java
core/src/main/java/com/opensymphony/xwork2/spring/SpringObjectFactory.java
core/src/main/java/com/opensymphony/xwork2/spring/SpringProxyableObjectFactory.java
core/src/main/java/com/opensymphony/xwork2/spring/interceptor/ActionAutowiringInterceptor.java
core/src/test/java/com/opensymphony/xwork2/ProxyObjectFactory.java
core/src/test/java/com/opensymphony/xwork2/interceptor/ScopedModelDrivenInterceptorTest.java
core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java
plugins/cdi/src/main/java/org/apache/struts2/cdi/CdiObjectFactory.java
plugins/cdi/src/test/java/org/apache/struts2/cdi/CdiObjectFactoryTest.java
plugins/convention/src/test/java/org/apache/struts2/convention/PackageBasedActionConfigBuilderTest.java
plugins/osgi/src/main/java/org/apache/struts2/osgi/DelegatingObjectFactory.java
plugins/osgi/src/main/java/org/apache/struts2/osgi/SpringOsgiObjectFactory.java
plugins/plexus/src/main/java/org/apache/struts2/plexus/PlexusObjectFactory.java
plugins/spring/src/main/java/org/apache/struts2/spring/StrutsSpringObjectFactory.java

Fixes [WW-4849](https://issues.apache.org/jira/browse/WW-4849)

WW-4849: Initializable interface

---

core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java
core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java

Fixes issue [WW-4862](https://issues.apache.org/jira/browse/WW-4862)

WW-4862: Multipart regex

---

core/src/main/java/com/opensymphony/xwork2/StrutsTextProviderFactory.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/main/java/org/apache/struts2/config/DefaultBeanSelectionProvider.java

Implements [WW-4884](https://issues.apache.org/jira/browse/WW-4884)

WW-4884: Allow define just a TextProvider

---

core/src/main/java/com/opensymphony/xwork2/validator/DefaultValidatorFactory.java
core/src/main/java/com/opensymphony/xwork2/validator/ValidatorFactory.java
core/src/test/java/com/opensymphony/xwork2/spring/SpringObjectFactoryTest.java
core/src/test/resources/com/opensymphony/xwork2/spring/emptyContext-spring.xml

Also fixes already existed silent errors of `SpringObjectFactoryTest` which have born after #168 :)

WW-4876 WW-4841 Parses validators after all injections done

---

core/src/test/java/com/opensymphony/xwork2/DefaultActionInvocationTest.java
core/src/test/java/com/opensymphony/xwork2/SimpleAction.java
core/src/test/resources/xwork-sample.xml

Tests coverall comment on PR 😉

Increases the coverage of DefaultActionInvocation

---

core/src/main/java/org/apache/struts2/factory/PrefixBasedActionProxyFactory.java
core/src/test/java/org/apache/struts2/factory/PrefixBasedActionProxyFactoryTest.java
pom.xml

Resolves issue [WW-4903](https://issues.apache.org/jira/browse/WW-4903)

WW-4903: fixes PrefixBasedActionProxyFactory

---

core/src/test/java/org/apache/struts2/components/UIBeanTest.java

added test for methods:
- `setClass`
- `setStyle`

add tests to UIBean class

---

core/pom.xml
core/src/main/java/com/opensymphony/xwork2/XWorkJUnit4TestCase.java
core/src/main/java/com/opensymphony/xwork2/XWorkTestCase.java
core/src/main/java/com/opensymphony/xwork2/config/impl/DefaultConfiguration.java
core/src/main/java/com/opensymphony/xwork2/config/impl/LocatableConstantFactory.java
core/src/main/java/com/opensymphony/xwork2/config/impl/LocatableFactory.java
core/src/main/java/com/opensymphony/xwork2/config/providers/XWorkConfigurationProvider.java
core/src/main/java/com/opensymphony/xwork2/conversion/ConversionPropertiesProcessor.java
core/src/main/java/com/opensymphony/xwork2/conversion/impl/DefaultConversionPropertiesProcessor.java
core/src/main/java/com/opensymphony/xwork2/inject/ContainerBuilder.java
core/src/main/java/com/opensymphony/xwork2/inject/ContainerImpl.java
core/src/main/java/com/opensymphony/xwork2/inject/EarlyInitializable.java
core/src/main/java/com/opensymphony/xwork2/inject/Factory.java
core/src/main/java/com/opensymphony/xwork2/inject/InitializableFactory.java
core/src/main/java/com/opensymphony/xwork2/inject/InternalFactory.java
core/src/main/java/com/opensymphony/xwork2/inject/Scope.java
core/src/main/java/com/opensymphony/xwork2/validator/DefaultValidatorFactory.java
core/src/main/java/com/opensymphony/xwork2/validator/ValidatorFactory.java
core/src/main/java/org/apache/struts2/config/AbstractBeanSelectionProvider.java
core/src/main/java/org/apache/struts2/config/StrutsXmlConfigurationProvider.java
core/src/main/java/org/apache/struts2/factory/PrefixBasedActionProxyFactory.java
core/src/test/java/com/opensymphony/xwork2/config/ConfigurationManagerTest.java
core/src/test/java/com/opensymphony/xwork2/inject/ContainerImplTest.java
core/src/test/java/com/opensymphony/xwork2/inject/EarlyInitializableBean.java
core/src/test/java/com/opensymphony/xwork2/inject/EarlyInitializableCheck.java
core/src/test/java/com/opensymphony/xwork2/inject/InitializableBean.java
core/src/test/java/com/opensymphony/xwork2/inject/InitializableCheck.java
core/src/test/java/com/opensymphony/xwork2/ognl/SetPropertiesTest.java
core/src/test/java/com/opensymphony/xwork2/validator/SimpleActionValidationTest.java
core/src/test/java/org/apache/struts2/factory/PrefixBasedActionProxyFactoryTest.java

Implements [WW-4905](https://issues.apache.org/jira/browse/WW-4905)

WW-4905: Allows Initializable interface on implementing class instead of interface

---

core/src/main/java/com/opensymphony/xwork2/ognl/accessor/XWorkListPropertyAccessor.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/test/java/com/opensymphony/xwork2/ognl/accessor/XWorkListPropertyAccessorTest.java

Implements [WW-4909](https://issues.apache.org/jira/browse/WW-4909)

WW-4909: Renames a constant and adds a test

---

apps/pom.xml
core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java
plugins/embeddedjsp/pom.xml
plugins/json/pom.xml
plugins/rest/pom.xml
plugins/rest/src/test/java/org/apache/struts2/rest/DefaultHttpHeadersTest.java
pom.xml

Upgrades Spring to version 4.3.13
Refers [WW-4899](https://issues.apache.org/jira/browse/WW-4899)

WW-4899: upgrade Spring

---

apps/rest-showcase/pom.xml
apps/rest-showcase/src/main/resources/struts.xml
plugins/rest/pom.xml
plugins/rest/src/main/java/org/apache/struts2/rest/handler/JacksonXmlHandler.java
plugins/rest/src/test/java/org/apache/struts2/rest/handler/JacksonXmlHandlerTest.java
plugins/rest/src/test/java/org/apache/struts2/rest/handler/SimpleBean.java
pom.xml

Implements [WW-4922](https://issues.apache.org/jira/browse/WW-4922)

WW-4922: Jackson XML

---

core/src/main/java/org/apache/struts2/components/ListUIBean.java
core/src/main/java/org/apache/struts2/components/OptGroup.java
core/src/main/resources/template/simple/optgroup.ftl
core/src/test/java/org/apache/struts2/views/freemarker/FreemarkerResultMockedTest.java
core/src/test/resources/org/apache/struts2/views/freemarker/select.ftl
core/src/test/resources/struts.xml

1. allow set freemarker sequence or hash as list
2. if list is a List, use 'top' as listKey and listValue
Implements [WW-4910](https://issues.apache.org/jira/browse/WW-4910)

WW-4910 Align OptGroup with Select

---

apps/rest-showcase/src/main/webapp/WEB-INF/web.xml
apps/showcase/src/main/webapp/WEB-INF/web.xml
core/pom.xml
core/src/test/java/org/apache/struts2/dispatcher/StrutsPrepareAndExecuteFilterIntegrationTest.java
core/src/test/java/org/apache/struts2/dispatcher/TwoFilterIntegrationTest.java
plugins/convention/pom.xml
plugins/jasperreports/pom.xml
plugins/jfreechart/pom.xml
plugins/json/pom.xml
plugins/junit/pom.xml
plugins/portlet-tiles/pom.xml
plugins/portlet/pom.xml
plugins/portlet/src/main/java/org/apache/struts2/portlet/servlet/PortletServletContext.java
plugins/sitegraph/pom.xml
plugins/testng/pom.xml
plugins/tiles/pom.xml
pom.xml

Implements [WW-4760](https://issues.apache.org/jira/browse/WW-4760)

Upgrade to Java EE5

---

core/src/main/java/org/apache/struts2/components/Text.java
core/src/main/java/org/apache/struts2/views/jsp/TextTag.java
core/src/site/resources/tags/text.html
core/src/test/java/org/apache/struts2/views/jsp/TextTagTest.java

drop searchValueStack attribute from the s:text tag

---

pom.xml

update commons-beanutils dependency to version 1.9.3

---

xwork-core/src/main/java/com/opensymphony/xwork2/conversion/impl/CollectionConverter.java
xwork-core/src/main/java/com/opensymphony/xwork2/conversion/impl/XWorkList.java
xwork-core/src/test/java/com/opensymphony/xwork2/conversion/impl/XWorkListTest.java

Resolves [WW-4954](https://issues.apache.org/jira/browse/WW-4954)

WW-4954 Moves XWorkList out of the util package

---

core/src/main/java/com/opensymphony/xwork2/conversion/impl/CollectionConverter.java
core/src/main/java/com/opensymphony/xwork2/conversion/impl/XWorkList.java
core/src/test/java/com/opensymphony/xwork2/conversion/impl/XWorkListTest.java

Resolves [WW-4954](https://issues.apache.org/jira/browse/WW-4954)

WW-4954 Moves XWorkList out of util package

---

xwork-core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java

Improve log messages in SecurityMemberAccess

---

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java
core/src/test/java/com/opensymphony/xwork2/config/providers/EnvsValueSubstitutorTest.java
core/src/test/java/com/opensymphony/xwork2/config/providers/XmlConfigurationProviderEnvsSubstitutionTest.java
core/src/test/java/org/apache/struts2/util/FastByteArrayOutputStreamTest.java
core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-envs-substitution.xml

Unit test improvement (1 new test class, 2 test classes updated to permit Maven build to succeed on Windows).  Minor change within a preexisting class (restore method).

Proposed unit test improvement for Windows, plus one additional minor change

---

core/src/main/java/com/opensymphony/xwork2/util/ClassPathFinder.java
core/src/main/java/com/opensymphony/xwork2/util/ResolverUtil.java
core/src/main/java/com/opensymphony/xwork2/util/classloader/JarResourceStore.java
core/src/main/java/com/opensymphony/xwork2/util/location/LocatableProperties.java
core/src/main/java/com/opensymphony/xwork2/util/location/LocationImpl.java
plugins/embeddedjsp/src/main/java/org/apache/struts2/jasper/compiler/SmapUtil.java
plugins/osgi/src/main/java/org/apache/struts2/osgi/host/BaseOsgiHost.java
plugins/spring/src/main/java/org/apache/struts2/spring/StrutsSpringObjectFactory.java

Java 7 introduced the try-with-resources statement,
which implicitly closes Closeables.
Fixes sonar rule squid:S2095

Fix: Resources should be closed

---

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java

Minor update to Struts 2.5.x SecurityMemberAccess (clean re-attempt change for PR#275, eliminated conflicting pom.xml change).
Code changes:
- updated SecurityMemberAccess for compatibility with future OGNL 3.1.19+ versions
- updated SecurityMemberAccess constructor (minor cleanup and added comment)

Minor update to Struts 2.5.x SecurityMemberAccess.

---

core/src/main/java/com/opensymphony/xwork2/ActionSupport.java

see https://builds.apache.org/analysis/dashboard/index?id=org.apache.struts%3Astruts2-core%3Asrc%2Fmain%2Fjava%2Fcom%2Fopensymphony%2Fxwork2%2FActionSupport.java

Fix various sonar warnings for class ActionSupport

---

plugins/rest/pom.xml
plugins/rest/src/main/java/org/apache/struts2/rest/handler/JuneauXmlHandler.java
plugins/rest/src/test/java/org/apache/struts2/rest/handler/JuneauXmlHandlerTest.java
pom.xml

Implements [WW-4889](https://issues.apache.org/jira/browse/WW-4889)

[WW-4889] Adds XML handler based on Apache Juneau

---

plugins/rest/src/main/java/org/apache/struts2/rest/handler/JacksonJsonHandler.java
plugins/rest/src/main/resources/struts-plugin.xml
plugins/rest/src/test/java/org/apache/struts2/rest/handler/JacksonJsonHandlerTest.java

Implements [WW-4989](https://issues.apache.org/jira/browse/WW-4989)

[WW-4989] Uses JacksonXML handler a default handler for XML in the REST plugin

---

pom.xml

Update Struts 2.6 to the latest OGNL 3.2.x version available.

Update Struts 2.6 to the latest OGNL 3.2.x version available.

---

core/src/main/java/com/opensymphony/xwork2/spring/SpringObjectFactory.java

Refs [WW-4938](https://issues.apache.org/jira/browse/WW-4938)
Refs #295

[WW-4938] Reverts dropping injecting internal beans in Spring Factory

---

core/src/main/java/com/opensymphony/xwork2/ObjectFactory.java
core/src/main/java/com/opensymphony/xwork2/spring/SpringObjectFactory.java
core/src/test/java/com/opensymphony/xwork2/spring/SpringObjectFactoryTest.java

Refs [WW-4938](https://issues.apache.org/jira/browse/WW-4938)
Refs #300

[WW-4938] Adds missing test case and properly fixes injecting internal beans

---

pom.xml

Refs [WW-4975](https://issues.apache.org/jira/browse/WW-4975)

[WW-4975] Upgrades commons-fileupload to version 1.4 - Struts 2.6

---

pom.xml

Refs [WW-4975](https://issues.apache.org/jira/browse/WW-4975)

[WW-4975] Upgrades commons-fileupload to version 1.4 - Struts 2.5.x

---

pom.xml

Refs [WW-4975](https://issues.apache.org/jira/browse/WW-4975)

[WW-4975] Upgrades commons-fileupload to version 1.4 - Struts 2.3.x

---

core/src/main/java/com/opensymphony/xwork2/config/impl/DefaultConfiguration.java
core/src/main/java/com/opensymphony/xwork2/config/providers/XWorkConfigurationProvider.java
core/src/main/java/com/opensymphony/xwork2/factory/DefaultConverterFactory.java
core/src/main/java/com/opensymphony/xwork2/factory/StrutsConverterFactory.java
core/src/main/java/org/apache/struts2/conversion/StrutsTypeConverterCreator.java
core/src/main/java/org/apache/struts2/conversion/StrutsTypeConverterHolder.java
core/src/main/resources/struts-default.xml
core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowstatic-devmode-false.xml
core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowstatic-devmode-true.xml
core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowstatic-true.xml
core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-devmode-true.xml

Implements [WW-4996](https://issues.apache.org/jira/browse/WW-4996)

[WW-4996] Refactor DefaultTypeConverterCreator to use ObjectFactory#buildConverter

---

pom.xml

Refs [WW-5007](https://issues.apache.org/jira/browse/WW-5007)

[WW-5007] Upgrades Jackson libraries to version 2.9.8

---

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStackFactory.java
core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java
core/src/main/java/com/opensymphony/xwork2/util/ProxyUtil.java
core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java
core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowstatic-devmode-false.xml
core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowstatic-devmode-true.xml
core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-allowstatic-true.xml
core/src/test/resources/com/opensymphony/xwork2/config/providers/xwork-test-devmode-true.xml
pom.xml

Fix for `NPE` issue discovered in WW-5004.
- Guard fix for a `NPE` that can arise under certain conditions, identified by _A. Mashchenko_.
- This guard (or something similar) will probably be required for future non-public field access logic ... may want to hold-off on this PR and instead include the fix in a "fuller solution".

Fix for NPE issue discovered in WW-5004.

---

plugins/json/src/main/java/org/apache/struts2/json/JSONInterceptor.java
plugins/json/src/test/java/org/apache/struts2/json/JSONInterceptorTest.java

@yasserzamani I know that you've assigned that issue to yourself, but I think it is the most simple solution that we can merge in 2.5.x branch. Can you take a look.

WW-5009 EmptyStackException in JSON plugin due to concurrency

---

README.md

@lukaszlenart @yasserzamani Is this is correct job to link to?

Update jenkins badge

---

pom.xml

Update SLF4J in Struts 2.5.x to the latest 1.7.x version.
- update library version in pom.xml

Upgrade SLF4J to 1.7.26 (WW-5023)

---

.mvn/wrapper/MavenWrapperDownloader.java
.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

Include the latest fixes from https://github.com/takari/maven-wrapper

Update maven-wrapper to 0.5.3 and maven to 3.6.0

---

core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java
core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java

Fixes [WW-4958](https://issues.apache.org/jira/browse/WW-4958)

[WW-4958] Uses less restrictive RegEx to check if it's a multipart request

---

.travis.yml
Jenkinsfile

This PR switches from a normal Maven Pipeline build to Docker based, plus it fixes build on TravisCI

Defines a Docker build

---

pom.xml

Fixes [WW-5038](https://issues.apache.org/jira/browse/WW-5038)

[WW-5038] Upgrades jackson-databind to version 2.9.9.3

---

.travis.yml
pom.xml

WW-5033 - Update to latest versions for some Struts 2.5.x dependencies:
- ASM 7 -> 7.1
- OGNL 3.1.23 -> 3.1.24
- Spring 4.3.20.RELEASE -> 4.3.24.RELEASE

WW-5033 - Update to latest versions for some Struts 2.5.x dependencies:

---

core/src/main/java/org/apache/struts2/result/ServletRedirectResult.java
core/src/test/java/org/apache/struts2/result/ServletRedirectResultTest.java

Hello Apache Struts Team.
This PR is just a cherry-pick of PR#367 into master.
Merge pull request #367 from JCgH4164838Gh792C124B5/local_25x_SendRedirectEnh
Minor improvement proposed for ServletRedirectResult sendRedirect()
(cherry picked from commit 706bb560e45df0d31e0f01895fb209d2685e2bcd)

Forward-port PR#367 from 2.5.x to 2.6.x (cherry-pick)

---

bundles/admin/src/main/resources/static/js/shell.js

Variable was missing declaration and semicolon was missing

Add more consistency to code

---

plugins/jasperreports/pom.xml

and switch exclude from jackson-annotation to jackson-annotations
b/c the artifact name changed

WW-5045 Update jasperreports to 6.10.0

---

core/src/main/java/com/opensymphony/xwork2/inject/ContainerImpl.java
core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java
core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/main/java/org/apache/struts2/views/jsp/ui/OgnlTool.java
core/src/main/resources/org/apache/struts2/default.properties
core/src/main/resources/struts-default.xml
core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java
core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java
core/src/test/java/org/apache/struts2/result/StreamResultTest.java
pom.xml

Upgrade to OGNL 3.2.12 and adapt to its new features.

WW-5050 cherry pick #371 and related commits

---

core/src/main/java/com/opensymphony/xwork2/inject/ContainerImpl.java

Minor follow-up to WW-5050 changes to ContainerImpl.
- Made isStatic() utility method static, added javadoc comment.
- Refactored isNotPublic() into isPublicForReflection() with negation moved
to calling locations.  Also added javadoc comment.
- Added final declaration to several variables used in methods.
- Added @Override annotation to overridden methods.

Minor follow-up to WW-5050 changes to ContainerImpl

---

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/main/java/org/apache/struts2/config/entities/ConstantConfig.java
core/src/main/java/org/apache/struts2/interceptor/debugging/DebuggingInterceptor.java
core/src/main/java/org/apache/struts2/interceptor/debugging/ObjectToHTMLWriter.java
core/src/main/resources/org/apache/struts2/interceptor/debugging/browser.ftl
core/src/main/resources/struts-default.xml
core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java
core/src/test/java/com/opensymphony/xwork2/util/Foo.java
core/src/test/java/org/apache/struts2/config/entities/ConstantConfigTest.java
plugins/config-browser/src/main/resources/config-browser/actionNames.ftl
plugins/config-browser/src/main/resources/config-browser/showConfig.ftl

To test this enable `devMode` and add `?debug=browser` to a url, eg.: `http://localhost:8080/struts2-showcase/?debug=browser`
Fixes [WW-5054](https://issues.apache.org/jira/browse/WW-5054)

[WW-5054] debug=browser

---

apps/showcase/pom.xml
bundles/demo/pom.xml
core/pom.xml
core/src/main/java/org/apache/struts2/views/TagLibraryDirectiveProvider.java
core/src/main/java/org/apache/struts2/views/util/ContextUtil.java
core/src/test/java/org/apache/struts2/util/InvocationSessionStoreTest.java
plugins/embeddedjsp/pom.xml
plugins/embeddedjsp/src/test/resources/org/apache/struts2/complex0.jsp
plugins/portlet/pom.xml
plugins/sitemesh/src/main/java/org/apache/struts2/sitemesh/VelocityDecoratorServlet.java
plugins/velocity/pom.xml
plugins/velocity/src/main/java/org/apache/struts2/views/velocity/StrutsVelocityContext.java
plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityManager.java
plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityStrutsUtil.java
plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityTagLibrary.java
pom.xml

Implements [WW-5047](https://issues.apache.org/jira/browse/WW-5047)

[WW-5047] Upgrades to VelocityEngine 2.1 and VelocityTools 3.0

---

core/src/main/java/com/opensymphony/xwork2/config/impl/AbstractMatcher.java
core/src/main/java/com/opensymphony/xwork2/config/impl/ActionConfigMatcher.java
core/src/main/java/com/opensymphony/xwork2/config/impl/DefaultConfiguration.java
core/src/main/java/com/opensymphony/xwork2/config/impl/NamespaceMatcher.java
core/src/main/java/com/opensymphony/xwork2/config/providers/XWorkConfigurationProvider.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/test/java/com/opensymphony/xwork2/config/impl/ActionConfigMatcherTest.java

Follow up on https://github.com/apache/struts/pull/400
Refs [WW-5065](https://issues.apache.org/jira/browse/WW-5065)

[WW-5065] Defines a new flag to control appending params

---

apps/showcase/src/main/java/org/apache/struts2/showcase/fileupload/FileUploadAction.java
apps/showcase/src/main/resources/org/apache/struts2/showcase/fileupload/FileUploadAction-validation.xml

Minor change to fix WW-5072 (single file upload failure):
- Add action-local method to get upload file size.
- Change file upload validation to use new method.

Minor change to fix WW-5072

---

plugins/json/src/main/java/org/apache/struts2/json/JSONResult.java

Resolves [WW-5070](https://issues.apache.org/jira/browse/WW-5070)

[WW-5070] Adds more sophisticated logic to search for the Root

---

core/src/main/java/com/opensymphony/xwork2/config/impl/AbstractMatcher.java
core/src/main/java/com/opensymphony/xwork2/config/impl/ActionConfigMatcher.java
core/src/main/java/com/opensymphony/xwork2/config/impl/DefaultConfiguration.java
core/src/main/java/com/opensymphony/xwork2/config/impl/NamespaceMatcher.java
core/src/main/java/com/opensymphony/xwork2/config/providers/XWorkConfigurationProvider.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/test/java/com/opensymphony/xwork2/config/impl/ActionConfigMatcherTest.java

Refs https://github.com/apache/struts/pull/405
Refs [WW-5065](https://issues.apache.org/jira/browse/WW-5065)

[WW-5065] Defines a new flag to control appending params - cherry-pick

---

apps/showcase/src/main/java/org/apache/struts2/showcase/fileupload/FileUploadAction.java
apps/showcase/src/main/resources/org/apache/struts2/showcase/fileupload/FileUploadAction-validation.xml

Cherry-Pick PR#411 change into master.
Merge pull request #411 from JCgH4164838Gh792C124B5/WW-5072_fix
Minor change to fix WW-5072
(cherry picked from commit e46e662a7ac7fde7f96ff322e557190765a88cc9)

Cherry-Pick PR#411 into master

---

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java
core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java

Two small changes to address problems discovered during testing Struts 2.6 with AppEngine

Tiny improvements

---

core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java

Provide unit test for partial backport PR#416 for 2.5.x (from L. Lenart's PR#414) :
- DispatcherTest provides code coverage tests of all getLocale() paths.

Provide unit test for partial backport PR#416 for 2.5.x

---

core/src/main/java/com/opensymphony/xwork2/interceptor/ParametersInterceptor.java

Refs [WW-5077](https://issues.apache.org/jira/browse/WW-5077)

[WW-5077] Better logs

---

core/src/main/java/com/opensymphony/xwork2/interceptor/ParametersInterceptor.java

Refs [WW-5077](https://issues.apache.org/jira/browse/WW-5077)

[WW-5077] Uses better logging to inform user about excluded params (cherry-pick)

---

core/src/main/resources/template/simple/textarea.ftl
core/src/test/java/org/apache/struts2/views/jsp/ui/TextareaTest.java
core/src/test/resources/org/apache/struts2/views/jsp/ui/Textarea-2.txt

Fixes [WW-5081](https://issues.apache.org/jira/browse/WW-5081)

[WW-5081] Makes textarea compatible with W3C

---

core/src/main/java/org/apache/struts2/result/PlainResult.java
core/src/main/java/org/apache/struts2/result/plain/BodyWriter.java
core/src/main/java/org/apache/struts2/result/plain/DateHttpHeader.java
core/src/main/java/org/apache/struts2/result/plain/HttpCookies.java
core/src/main/java/org/apache/struts2/result/plain/HttpHeader.java
core/src/main/java/org/apache/struts2/result/plain/HttpHeaders.java
core/src/main/java/org/apache/struts2/result/plain/IntHttpHeader.java
core/src/main/java/org/apache/struts2/result/plain/ResponseBuilder.java
core/src/main/java/org/apache/struts2/result/plain/StringHttpHeader.java
core/src/test/java/org/apache/struts2/result/PlainResultTest.java

Implements [WW-5080](https://issues.apache.org/jira/browse/WW-5080)

[WW-5080] Defines a new result type plain to use directly with Java code

---

core/src/main/java/org/apache/struts2/interceptor/FileUploadInterceptor.java

Empty file upload, storeLocation null gives wrong error message.

---

core/src/main/java/org/apache/struts2/components/Component.java
core/src/main/java/org/apache/struts2/components/UIBean.java
core/src/main/java/org/apache/struts2/views/jsp/ui/AbstractUITag.java
core/src/main/resources/struts-default.xml
core/src/test/java/org/apache/struts2/components/UIBeanTest.java
core/src/test/java/org/apache/struts2/util/StrutsUtilTest.java
plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/AbstractTest.java
plugins/junit/src/main/java/org/apache/struts2/StrutsJUnit4TestCase.java

[WW-5095] Cherry picks changes from 2-5-x branch

---

core/src/main/java/com/opensymphony/xwork2/interceptor/StaticParametersInterceptor.java
core/src/main/java/org/apache/struts2/dispatcher/HttpParameters.java
core/src/test/java/com/opensymphony/xwork2/interceptor/StaticParametersInterceptorTest.java

Fixes [WW-5096](https://issues.apache.org/jira/browse/WW-5096)

[WW-5096] Fix StaticParametersInterceptor param overwrite

---

core/src/main/java/org/apache/struts2/components/ActionComponent.java

Fixes [WW-3730](https://issues.apache.org/jira/browse/WW-3730)

[WW-3730] Avoids conversion to String[] of passed params

---

core/src/main/java/org/apache/struts2/interceptor/I18nInterceptor.java
core/src/test/java/org/apache/struts2/interceptor/I18nInterceptorTest.java

This PR adds a new handler to support `Accept-Language` header when selecting `Locale`. `I18Interceptor` must be configured with a set of supported locale to properly filter out user's `Locale`.
If this PR will be accepted I will update docs.
Implements [WW-4929](https://issues.apache.org/jira/browse/WW-4929)

[WW-4929] Adds support for Accept-Language header when looking up Locale

---

core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java

Fixes [WW-5100](https://issues.apache.org/jira/browse/WW-5100)

[WW-5100] Applies encoding to response as well

---

core/src/main/java/org/apache/struts2/components/Component.java
core/src/main/java/org/apache/struts2/config/entities/ConstantConfig.java
core/src/main/java/org/apache/struts2/util/ComponentUtils.java
core/src/main/java/org/apache/struts2/util/StrutsUtil.java

Refs [WW-3877](https://issues.apache.org/jira/browse/WW-3877)

[WW-3877] Removes comments about altSyntax

---

core/src/main/java/com/opensymphony/xwork2/ActionChainResult.java
core/src/main/java/com/opensymphony/xwork2/Result.java
core/src/main/java/org/apache/struts2/result/HttpHeaderResult.java
core/src/main/java/org/apache/struts2/result/PlainResult.java
core/src/main/java/org/apache/struts2/result/PostbackResult.java
core/src/main/java/org/apache/struts2/result/ServletActionRedirectResult.java
core/src/main/java/org/apache/struts2/result/ServletRedirectResult.java
core/src/main/java/org/apache/struts2/views/xslt/XSLTResult.java
core/src/site/resources/tags/action-attributes.html
core/src/site/resources/tags/bean-attributes.html
core/src/site/resources/tags/date-attributes.html
core/src/site/resources/tags/iterator-attributes.html
core/src/site/resources/tags/number-attributes.html
core/src/site/resources/tags/set-attributes.html
core/src/site/resources/tags/text-attributes.html
core/src/site/resources/tags/url-attributes.html
core/src/test/java/com/opensymphony/xwork2/ActionChainResultTest.java
core/src/test/java/org/apache/struts2/result/HttpHeaderResultTest.java
core/src/test/java/org/apache/struts2/result/PlainResultTest.java
core/src/test/java/org/apache/struts2/result/PostbackResultTest.java
core/src/test/java/org/apache/struts2/result/ServletRedirectResultTest.java
core/src/test/java/org/apache/struts2/views/xslt/XSLTResultTest.java
plugins/gxp/src/main/java/org/apache/struts2/views/gxp/GxpResult.java
plugins/json/src/main/java/org/apache/struts2/json/JSONResult.java
plugins/json/src/test/java/org/apache/struts2/json/JSONResultTest.java
plugins/portlet/src/main/java/org/apache/struts2/portlet/result/PortletActionRedirectResult.java

Implements [WW-5063](https://issues.apache.org/jira/browse/WW-5063)

[WW-5063] Adds null check for ActionInvocation

---

core/src/main/java/org/apache/struts2/util/TextProviderHelper.java

and uses proper order for escaping
Fixes [WW-4742](https://issues.apache.org/jira/browse/WW-4742)

[WW-4742] Stops evaluating default message as a OGNL expression

---

core/src/main/java/com/opensymphony/xwork2/ObjectFactory.java
core/src/main/java/com/opensymphony/xwork2/config/impl/DefaultConfiguration.java
core/src/main/java/com/opensymphony/xwork2/config/providers/StrutsDefaultConfigurationProvider.java
core/src/main/java/com/opensymphony/xwork2/interceptor/ChainingInterceptor.java
core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java
core/src/main/java/com/opensymphony/xwork2/ognl/accessor/XWorkListPropertyAccessor.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/main/java/org/apache/struts2/config/entities/ConstantConfig.java
core/src/test/java/com/opensymphony/xwork2/ognl/accessor/XWorkListPropertyAccessorTest.java
plugins/cdi/src/main/java/org/apache/struts2/cdi/CdiObjectFactory.java
plugins/javatemplates/src/main/java/org/apache/struts2/views/java/JavaTemplateConstants.java
plugins/javatemplates/src/main/java/org/apache/struts2/views/java/JavaTemplateEngine.java
plugins/oval/src/main/java/org/apache/struts2/oval/interceptor/OValValidationInterceptor.java

Implements [WW-5000](https://issues.apache.org/jira/browse/WW-5000)

[WW-5000] Extracts string literals as constants

---

plugins/jfreechart/pom.xml
plugins/jfreechart/src/main/java/org/apache/struts2/dispatcher/ChartResult.java

Implements [WW-5099](https://issues.apache.org/jira/browse/WW-5099)

[WW-5099] Upgrades JFreeChart to version 1.5.1

---

core/src/main/java/com/opensymphony/xwork2/security/DefaultAcceptedPatternsChecker.java
core/src/test/java/com/opensymphony/xwork2/security/DefaultAcceptedPatternsCheckerTest.java

Implements [WW-5056](https://issues.apache.org/jira/browse/WW-5056)

[WW-5056] Accepts dashes in param names

---

core/src/main/java/com/opensymphony/xwork2/DefaultActionProxy.java
core/src/main/java/com/opensymphony/xwork2/conversion/impl/DateConverter.java
core/src/test/java/com/opensymphony/xwork2/StubTextProvider.java
core/src/test/java/com/opensymphony/xwork2/conversion/impl/DateConverterTest.java
core/src/test/java/com/opensymphony/xwork2/conversion/impl/XWorkBasicConverterTest.java
core/src/test/java/com/opensymphony/xwork2/conversion/impl/XWorkConverterTest.java
core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java
core/src/test/java/com/opensymphony/xwork2/validator/SimpleActionValidationTest.java

Implements [WW-4799](https://issues.apache.org/jira/browse/WW-4799)

[WW-4799] Adding struts.date.format as a conversion format for DateConverter

---

core/src/main/java/org/apache/struts2/result/PostbackResult.java

2.5.x backport: WW-5116 Fix wrong regex range

---

core/src/main/java/org/apache/struts2/components/TextArea.java
core/src/main/java/org/apache/struts2/views/jsp/ui/TextareaTag.java
core/src/main/resources/template/simple/textarea.ftl
core/src/site/resources/tags/textarea-attributes.html

Maxlength attribute added to textarea tag

WW-2411 Add a maxlength attribute to the textarea tag 

---

core/src/main/java/org/apache/struts2/components/UIBean.java
core/src/main/java/org/apache/struts2/views/jsp/ui/AbstractUITag.java
core/src/site/resources/tags/a.html
core/src/site/resources/tags/actionerror.html
core/src/site/resources/tags/actionmessage.html
core/src/site/resources/tags/checkbox.html
core/src/site/resources/tags/checkboxlist.html
core/src/site/resources/tags/combobox.html
core/src/site/resources/tags/component.html
core/src/site/resources/tags/datetextfield.html
core/src/site/resources/tags/debug.html
core/src/site/resources/tags/doubleselect.html
core/src/site/resources/tags/fielderror.html
core/src/site/resources/tags/file.html
core/src/site/resources/tags/form.html
core/src/site/resources/tags/head.html
core/src/site/resources/tags/hidden.html
core/src/site/resources/tags/inputtransferselect.html
core/src/site/resources/tags/label.html
core/src/site/resources/tags/optiontransferselect.html
core/src/site/resources/tags/password.html
core/src/site/resources/tags/radio.html
core/src/site/resources/tags/reset.html
core/src/site/resources/tags/select.html
core/src/site/resources/tags/submit.html
core/src/site/resources/tags/textarea.html
core/src/site/resources/tags/textfield.html
core/src/site/resources/tags/token.html
core/src/site/resources/tags/updownselect.html

Fixes [WW-5136](https://issues.apache.org/jira/browse/WW-5136)

[WW-5136] Makes class attribute deprecated

---

core/src/main/java/org/apache/struts2/components/UIBean.java
core/src/main/java/org/apache/struts2/views/jsp/ui/AbstractUITag.java
core/src/site/resources/tags/a.html
core/src/site/resources/tags/actionerror.html
core/src/site/resources/tags/actionmessage.html
core/src/site/resources/tags/checkbox.html
core/src/site/resources/tags/checkboxlist.html
core/src/site/resources/tags/combobox.html
core/src/site/resources/tags/component.html
core/src/site/resources/tags/datetextfield.html
core/src/site/resources/tags/debug.html
core/src/site/resources/tags/doubleselect.html
core/src/site/resources/tags/fielderror.html
core/src/site/resources/tags/file.html
core/src/site/resources/tags/form.html
core/src/site/resources/tags/head.html
core/src/site/resources/tags/hidden.html
core/src/site/resources/tags/inputtransferselect.html
core/src/site/resources/tags/label.html
core/src/site/resources/tags/optiontransferselect.html
core/src/site/resources/tags/password.html
core/src/site/resources/tags/radio.html
core/src/site/resources/tags/reset.html
core/src/site/resources/tags/select.html
core/src/site/resources/tags/submit.html
core/src/site/resources/tags/textarea.html
core/src/site/resources/tags/textfield.html
core/src/site/resources/tags/token.html
core/src/site/resources/tags/updownselect.html

Refs [WW-5136](https://issues.apache.org/jira/browse/WW-5136)

[WW-5136] Makes class attribute deprecated - cherry-pick

---

core/src/main/java/com/opensymphony/xwork2/config/impl/AbstractMatcher.java
core/src/test/java/com/opensymphony/xwork2/config/impl/AbstractMatcherTest.java

[WW-5073](https://issues.apache.org/jira/browse/WW-5073)

[WW-5073] - simplify AbstractMatcher convertParam

---

plugins/oval/src/main/java/org/apache/struts2/oval/interceptor/DefaultOValValidationManager.java
plugins/oval/src/main/java/org/apache/struts2/oval/interceptor/OValValidationInterceptor.java
plugins/oval/src/main/java/org/apache/struts2/oval/interceptor/OValValidationManager.java
plugins/oval/src/test/java/org/apache/struts2/oval/interceptor/ModelDrivenAction.java
plugins/oval/src/test/java/org/apache/struts2/oval/interceptor/OValValidationInterceptorTest.java
plugins/oval/src/test/java/org/apache/struts2/oval/interceptor/ValidationInMethods.java
pom.xml

Upgrades XStream and OVal
[WW-5142](https://issues.apache.org/jira/browse/WW-5142)
[WW-5143](https://issues.apache.org/jira/browse/WW-5143)

[WW-5143] [WW-5142] Upgrades OVal to ver. 3.2.1 and upgrades XStream to ver 1.4.18

---

core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java

Add test codes to check the encoding of response

Add test codes to check the encoding of response

---

pom.xml

with JDK 17 and 18 support according to https://asm.ow2.io/versions.html

[WW-5148] Upgrade ASM to version 9.2

---

core/src/main/java/org/apache/struts2/components/Checkbox.java
core/src/main/java/org/apache/struts2/components/UIBean.java
core/src/main/java/org/apache/struts2/views/jsp/ui/AbstractUITag.java

Fixes [WW-5149](https://issues.apache.org/jira/browse/WW-5149)

[WW-5149] Puts back "labelposition" with a warning of deprecation

---

pom.xml

https://logging.apache.org/log4j/2.x/security.html

log4j 2.17.0

---

.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

see https://github.com/apache/maven-wrapper
changes generated by `mvn wrapper:wrapper`

Update mvnw to 3.1.0 and migrate from takari to apache

---

pom.xml

Fixes [WW-5161](https://issues.apache.org/jira/browse/WW-5161)

[WW-5161] Update spring to 4.3.30

---

pom.xml

this will fix Reproducible Builds issue: see https://github.com/jvm-repo-rebuild/reproducible-central#org.apache.struts:struts2-parent

upgrade Felix maven-bundle-plugin to 5.1.3

---

pom.xml

upgrade maven-war-plugin to 3.3.1

---

apps/rest-showcase/pom.xml
core/src/main/java/com/opensymphony/xwork2/config/impl/DefaultConfiguration.java
core/src/main/java/com/opensymphony/xwork2/config/impl/MockConfiguration.java
core/src/main/java/com/opensymphony/xwork2/config/providers/StrutsDefaultConfigurationProvider.java
core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/main/java/org/apache/struts2/config/entities/ConstantConfig.java

This is a follow up of #227 and #464

[WW-4792] Uses proper names for constants

---

core/src/main/java/org/apache/struts2/components/CheckboxList.java
core/src/main/java/org/apache/struts2/components/ListUIBean.java
core/src/main/java/org/apache/struts2/components/Radio.java
core/src/main/java/org/apache/struts2/components/UIBean.java
core/src/main/java/org/apache/struts2/components/template/FreemarkerTemplateEngine.java
core/src/main/resources/template/simple/checkboxlist.ftl
core/src/main/resources/template/simple/dynamic-attributes.ftl
core/src/main/resources/template/simple/radiomap.ftl
core/src/test/java/org/apache/struts2/views/jsp/ui/TextfieldTest.java
core/src/test/resources/org/apache/struts2/views/jsp/ui/Textfield-5.txt

[WW-5117] Evaluates dynamic attributes - cherrypick

---

core/src/main/java/com/opensymphony/xwork2/util/AbstractLocalizedTextProvider.java
core/src/main/java/org/apache/struts2/util/TextProviderHelper.java

Addresses @gregh3269's comment in [WW-5112](https://issues.apache.org/jira/browse/WW-5112)

[WW-5112] Reduces logging in logic around missing resource key

---

core/src/main/java/com/opensymphony/xwork2/interceptor/ParametersInterceptor.java
core/src/test/java/com/opensymphony/xwork2/interceptor/ParametersInterceptorTest.java

@gregh3269 what about such simple solution? I have cherry-picked commits from https://github.com/apache/struts/pull/482
Resolves [WW-5115](https://issues.apache.org/jira/browse/WW-5115)

[WW-5115] Reduces logging for ignored DMI related params when DMI is disabled

---

apps/showcase/pom.xml
bundles/pom.xml
core/pom.xml
core/src/main/java/org/apache/struts2/components/Include.java
core/src/main/java/org/apache/struts2/components/ServletUrlRenderer.java
core/src/main/java/org/apache/struts2/util/StrutsUtil.java
core/src/main/java/org/apache/struts2/util/URLBean.java
core/src/test/java/org/apache/struts2/interceptor/CookieInterceptorTest.java
core/src/test/java/org/apache/struts2/views/jsp/StrutsMockServletContext.java
plugins/embeddedjsp/pom.xml
plugins/jasperreports/pom.xml
plugins/jfreechart/pom.xml
plugins/json/pom.xml
plugins/junit/pom.xml
plugins/osgi/pom.xml
plugins/pom.xml
plugins/portlet-mocks/pom.xml
plugins/portlet/pom.xml
plugins/portlet/src/main/java/org/apache/struts2/portlet/servlet/PortletServletContext.java
plugins/portlet/src/main/java/org/apache/struts2/portlet/servlet/PortletServletInputStream.java
plugins/portlet/src/main/java/org/apache/struts2/portlet/servlet/PortletServletOutputStream.java
plugins/portlet/src/main/java/org/apache/struts2/portlet/servlet/PortletServletRequest.java
plugins/portlet/src/main/java/org/apache/struts2/portlet/servlet/PortletServletResponse.java
plugins/rest/pom.xml
plugins/spring/pom.xml
plugins/testng/pom.xml
plugins/velocity/pom.xml
pom.xml

Refs [WW-5182](https://issues.apache.org/jira/browse/WW-5182)

[WW-5182] Upgrade to Servlet API 3.1

---

core/src/main/java/com/opensymphony/xwork2/config/providers/StrutsDefaultConfigurationProvider.java
core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java
core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java
core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStackFactory.java
core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java
core/src/main/java/com/opensymphony/xwork2/ognl/accessor/XWorkMethodAccessor.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/main/java/org/apache/struts2/config/entities/ConstantConfig.java
core/src/test/java/com/opensymphony/xwork2/interceptor/ParametersInterceptorTest.java
core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java
core/src/test/java/com/opensymphony/xwork2/ognl/OgnlValueStackTest.java
core/src/test/java/com/opensymphony/xwork2/ognl/SetPropertiesTest.java
core/src/test/java/com/test/SecurityMemberAccessTest.java
core/src/test/java/com/test/TestSecurityMemberAccess.java
core/src/test/java/org/apache/struts2/util/SecurityMemberAccessInServletsTest.java
plugins/spring/src/test/java/com/test/SecurityMemberAccessProxyTest.java

Implements [WW-5181](https://issues.apache.org/jira/browse/WW-5181)

[WW-5181] Blocks permanently access to static methods

---

core/pom.xml
core/src/test/java/org/apache/struts2/result/PlainResultTest.java
plugins/portlet-mocks/pom.xml
plugins/portlet/pom.xml
pom.xml

Refs [WW-5165](https://issues.apache.org/jira/browse/WW-5165)
Closes #534

[WW-5165] Upgrades Spring to version 5.3.20

---

core/src/main/java/com/opensymphony/xwork2/conversion/impl/DateConverter.java
core/src/test/java/com/opensymphony/xwork2/conversion/impl/DateConverterTest.java

Reviewed what I had done before, and here is another patch. 
org.apache.struts2.components.Date.DATETAG_PROPERTY override, and localdate/localtime.

Add basic LocalDateTime support WW-5175

---

pom.xml

see last releases rebuild results: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/struts/README.md

upgrade Felix m-bundle-p: reproducible builds

---

bom/pom.xml

Fixes [WW-5187](https://issues.apache.org/jira/browse/WW-5187)

Add async and velocity plugin to bom

---

plugins/sitemesh/src/main/java/org/apache/struts2/sitemesh/VelocityPageFilter.java
plugins/sitemesh/src/main/resources/struts-plugin.xml

Also docs need to be updated to mark this change.
Fixes [WW-5187](https://issues.apache.org/jira/browse/WW-5187)

[WW-5187] Comments out Velocity based PageFilter

---

apps/rest-showcase/src/main/webapp/WEB-INF/web.xml
apps/showcase/src/main/webapp/WEB-INF/web.xml
plugins/tiles/src/main/java/org/apache/struts2/tiles/StrutsApplicationResource.java
plugins/tiles/src/main/java/org/apache/struts2/tiles/StrutsWildcardServletApplicationContext.java

Refs [WW-5185](https://issues.apache.org/jira/browse/WW-5185)

[WW-5185] Reintroduces proper implementation of Tiles resource to support wildcard matching of Tiles definitions

---

core/src/main/java/org/apache/struts2/components/Date.java
core/src/test/java/org/apache/struts2/components/DateTest.java

Fixes [WW-5197](https://issues.apache.org/jira/browse/WW-5197)

WW-5197 Adds support for java.sql.Date

---

pom.xml

Fixes [WW-5201](https://issues.apache.org/jira/browse/WW-5201)

[WW-5201] Upgrades log4j2 to version 2.18.0

---

apps/showcase/pom.xml
plugins/bean-validation/pom.xml
pom.xml

Depends on #575 
Fixes [WW-5193](https://issues.apache.org/jira/browse/WW-5193)

[WW-5193] Uses proper org.hibernate.validator groupId and upgrade to version 6.1.3.Final

---

pom.xml

Fixes [WW-5204](https://issues.apache.org/jira/browse/WW-5204)

[WW-5204] Upgrades OGNL to version 3.3.3

---

.travis.yml

In reference to https://github.com/apache/struts/pull/582#issuecomment-1207209619 and to fix the build

Add openjdk17 to build, remove oraclejdk9 (EOL) and switch from oraclejdk to openjdk to fix Travis CI build

---

pom.xml

see https://github.com/apache/maven-surefire/releases/tag/surefire-3.0.0-M7

Update maven-surefire-plugin to 3.0.0-M7

---

core/src/main/java/com/opensymphony/xwork2/util/finder/ClassFinder.java
plugins/convention/src/main/java/org/apache/struts2/convention/DefaultClassFinder.java

Fixes [WW-5207](https://issues.apache.org/jira/browse/WW-5207)

[WW-5207] Uses ASM 9 by default

---

core/src/main/java/org/apache/struts2/interceptor/csp/CspInterceptor.java
core/src/main/java/org/apache/struts2/interceptor/csp/CspSettings.java
core/src/main/java/org/apache/struts2/interceptor/csp/DefaultCspSettings.java
core/src/test/java/org/apache/struts2/interceptor/CspInterceptorTest.java
core/src/test/java/org/apache/struts2/views/freemarker/FreemarkerResultMockedTest.java

Fixes [WW-5215](https://issues.apache.org/jira/browse/WW-5215)

[WW-5215] Checks if session was already created before applying CSP settings

---

pom.xml

Fixes [WW-5212](https://issues.apache.org/jira/browse/WW-5212)

[WW-5212] Upgrades to Spring 5.3.22

---

core/src/main/java/org/apache/struts2/interceptor/CoepInterceptor.java
core/src/main/java/org/apache/struts2/interceptor/CoopInterceptor.java
core/src/main/java/org/apache/struts2/interceptor/FetchMetadataInterceptor.java
core/src/main/java/org/apache/struts2/interceptor/csp/CspInterceptor.java
core/src/main/java/org/apache/struts2/interceptor/csp/DefaultCspSettings.java
core/src/main/resources/struts-default.xml
core/src/test/java/org/apache/struts2/interceptor/CoopInterceptorTest.java
core/src/test/java/org/apache/struts2/interceptor/CspInterceptorTest.java
core/src/test/java/org/apache/struts2/interceptor/FetchMetadataInterceptorTest.java

Fixes [WW-5218](https://issues.apache.org/jira/browse/WW-5218)

[WW-5218] Allows to disable CSP related interceptors

---

core/pom.xml
core/src/test/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequestTest.java
plugins/testng/pom.xml
plugins/testng/src/main/java/org/apache/struts2/testng/StrutsTestCase.java
plugins/testng/src/main/java/org/apache/struts2/testng/TestNGXWorkTestCase.java
plugins/testng/src/test/java/org/apache/struts2/testng/TestNGStrutsTestCaseTest.java
plugins/testng/src/test/java/org/apache/struts2/testng/TestNGXWorkTestCaseTest.java
pom.xml

Also moves test classes under testng package
Fixes [WW-5219](https://issues.apache.org/jira/browse/WW-5219)

WW-5219 Moves TestNG related classes into TestNG plugin

---

pom.xml

Closes [WW-5213](https://issues.apache.org/jira/browse/WW-5213)

[WW-5213] Upgrades javax.el to 3.0.1-b12

---

assembly/src/main/assembly/min-lib.xml
plugins/cdi/src/test/java/org/apache/struts2/cdi/CdiObjectFactoryTest.java
pom.xml

Addresses [WW-5226](https://issues.apache.org/jira/browse/WW-5226)

[WW-5226] Upgrade weld-core to version 2.4.8.Final

---

pom.xml

Closes [WW-5227](https://issues.apache.org/jira/browse/WW-5227)

[WW-5227] Upgrades Log4j to version 2.19.0

---

pom.xml

Reviewers @apache/struts-committers 
Closes [WW-5229](https://issues.apache.org/jira/browse/WW-5229)

[WW-5229] Upgrades Spring to version 5.3.23

---

pom.xml

Reviewers @apache/struts-committers 
Closes [WW-5228](https://issues.apache.org/jira/browse/WW-5228)

[WW-5228] Upgrades OWASP dependency-check-maven to version 7.2.0

---

pom.xml

Reviewers @apache/struts-committers 
Closes [WW-5231](https://issues.apache.org/jira/browse/WW-5231)

[WW-5231] Upgrades apache-rat-plugin to version 0.15

---

apps/rest-showcase/pom.xml
apps/showcase/pom.xml
core/pom.xml
plugins/embeddedjsp/pom.xml
pom.xml

Refs [WW-5232](https://issues.apache.org/jira/browse/WW-5232)

[WW-5232] Applies proper coverage settings for Jacoco plugin and Sonar

---

Jenkinsfile
core/src/main/java/com/opensymphony/xwork2/interceptor/ParametersInterceptor.java
core/src/test/java/com/opensymphony/xwork2/interceptor/ParametersInterceptorTest.java
pom.xml

Refs [WW-5184](https://issues.apache.org/jira/browse/WW-5184)

[WW-5184] Uses debug log level when parameter value was not accepted

---

plugins/tiles/src/main/java/org/apache/tiles/template/GetAsStringModel.java
plugins/tiles/src/main/java/org/apache/tiles/web/jsp/taglib/AddAttributeTag.java
plugins/tiles/src/main/java/org/apache/tiles/web/jsp/taglib/AddListAttributeTag.java
plugins/tiles/src/main/java/org/apache/tiles/web/jsp/taglib/DefinitionTag.java
plugins/tiles/src/main/java/org/apache/tiles/web/jsp/taglib/GetAsStringTag.java
plugins/tiles/src/main/java/org/apache/tiles/web/jsp/taglib/ImportAttributeTag.java
plugins/tiles/src/main/java/org/apache/tiles/web/jsp/taglib/InsertAttributeTag.java
plugins/tiles/src/main/java/org/apache/tiles/web/jsp/taglib/InsertDefinitionTag.java
plugins/tiles/src/main/java/org/apache/tiles/web/jsp/taglib/InsertTemplateTag.java
plugins/tiles/src/main/java/org/apache/tiles/web/jsp/taglib/PutAttributeTag.java
plugins/tiles/src/main/java/org/apache/tiles/web/jsp/taglib/PutListAttributeTag.java
plugins/tiles/src/main/java/org/apache/tiles/web/jsp/taglib/SetCurrentContainerTag.java
plugins/tiles/src/main/java/org/apache/tiles/web/jsp/taglib/UseAttributeTag.java
plugins/tiles/src/main/java/org/apache/tiles/web/jsp/taglib/package-info.java
plugins/tiles/src/main/resources/META-INF/tld/tiles-extras-jsp.tld
plugins/tiles/src/main/resources/META-INF/tld/tiles-jsp.tld

Add missing classes and tld definition.

---

pom.xml

Closes [WW-5244](https://issues.apache.org/jira/browse/WW-5244)

[WW-5244] Upgrades commons-text to version 1.10.0

---

pom.xml

Closes [WW-5245](https://issues.apache.org/jira/browse/WW-5245)

[WW-5245] Upgrades Jackson Databind to version 2.13.4.2

---

plugins/rest/src/main/java/org/apache/struts2/rest/handler/XStreamHandler.java
plugins/rest/src/main/java/org/apache/struts2/rest/handler/xstream/XStreamAllowedClassNames.java
plugins/rest/src/main/java/org/apache/struts2/rest/handler/xstream/XStreamAllowedClasses.java
plugins/rest/src/main/java/org/apache/struts2/rest/handler/xstream/XStreamPermissionProvider.java
plugins/rest/src/main/java/org/apache/struts2/rest/handler/xstream/XStreamProvider.java
plugins/rest/src/test/java/org/apache/struts2/rest/handler/XStreamHandlerTest.java

Implements [WW-2815](https://issues.apache.org/jira/browse/WW-2815)

[WW-2815] Refactors XStreamHandler to allow to provide a custom configuration

---

pom.xml

Closes [WW-5230](https://issues.apache.org/jira/browse/WW-5230)

[WW-5230] Upgrades OGNL to version 3.3.4

---

core/src/main/java/com/opensymphony/xwork2/util/NamedVariablePatternMatcher.java
core/src/test/java/com/opensymphony/xwork2/util/NamedVariablePatternMatcherTest.java

Fixes [WW-3529](https://issues.apache.org/jira/browse/WW-3529)

[WW-3529] Fixes usage of RegEx related characters in named pattern

---

core/src/main/java/com/opensymphony/xwork2/XWorkTestCase.java
core/src/main/java/com/opensymphony/xwork2/inject/ContainerImpl.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/main/java/org/apache/struts2/dispatcher/InitOperations.java
core/src/test/java/org/apache/struts2/dispatcher/InitOperationsTest.java

Closes [WW-3737](https://issues.apache.org/jira/browse/WW-3737)

[WW-3737] Allows to define a custom separator used to split patterns

---

core/src/main/java/com/opensymphony/xwork2/util/DomHelper.java
core/src/main/java/org/apache/struts2/views/xslt/XSLTResult.java
core/src/main/resources/author.dtd
core/src/test/java/com/opensymphony/xwork2/util/DomHelperTest.java

Fixes [WW-5252](https://issues.apache.org/jira/browse/WW-5252)

[WW-5252] Disables parsing external entities

---

core/src/main/resources/template/simple/checkbox.ftl
core/src/main/resources/template/simple/common-attributes.ftl
core/src/main/resources/template/xhtml/checkbox.ftl
core/src/test/java/org/apache/struts2/views/jsp/AbstractUITagTest.java
core/src/test/java/org/apache/struts2/views/jsp/ui/CheckboxTest.java
core/src/test/resources/org/apache/struts2/views/jsp/ui/DoubleSelect-5.txt

Closes [WW-5257](https://issues.apache.org/jira/browse/WW-5257)

[WW-5257] Cleans up template

---

core/src/main/java/com/opensymphony/xwork2/DefaultActionInvocation.java
core/src/main/java/com/opensymphony/xwork2/interceptor/AbstractInterceptor.java
core/src/main/java/com/opensymphony/xwork2/interceptor/ConditionalInterceptor.java
core/src/main/java/com/opensymphony/xwork2/interceptor/Interceptor.java
core/src/main/java/org/apache/struts2/interceptor/CoepInterceptor.java
core/src/main/java/org/apache/struts2/interceptor/CoopInterceptor.java
core/src/main/java/org/apache/struts2/interceptor/FetchMetadataInterceptor.java
core/src/main/java/org/apache/struts2/interceptor/csp/CspInterceptor.java
core/src/test/java/com/opensymphony/xwork2/DefaultActionInvocationTest.java
core/src/test/java/org/apache/struts2/interceptor/CoepInterceptorTest.java
core/src/test/java/org/apache/struts2/interceptor/CoopInterceptorTest.java
core/src/test/java/org/apache/struts2/interceptor/CspInterceptorTest.java
core/src/test/java/org/apache/struts2/interceptor/FetchMetadataInterceptorTest.java

Closes [WW-4173](https://issues.apache.org/jira/browse/WW-4173)

[WW-4173] Introduces a dedicated interface to allow conditionally disabling a given interceptor

---

core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/main/java/org/apache/struts2/components/Checkbox.java
core/src/main/java/org/apache/struts2/components/UIBean.java
core/src/main/resources/template/simple/checkbox.ftl
core/src/site/resources/tags/checkbox-attributes.html
core/src/test/java/org/apache/struts2/views/jsp/ui/CheckboxTest.java
core/src/test/resources/struts-checkbox-submit-unchecked.xml

Closes [WW-5260](https://issues.apache.org/jira/browse/WW-5260)
Also addresses [WW-5257](https://issues.apache.org/jira/browse/WW-5257)

[WW-5260] Introduces a constant to set submitUnchecked attribute of checkbox tag globally

---

plugins/oval/pom.xml
pom.xml
src/etc/project-suppression.xml

CVE-2016-1000027 is reported as a false positive, you can gain more information [here](https://github.com/spring-projects/spring-framework/issues/24434)

Updates OWASP suppressions as some reports are false positive

---

.asf.yaml

More details on [wiki](https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-AutolinksforJira)

Defines to autolink PRs to issues in ASF JIRA

---

core/src/main/resources/struts-default.xml

Fixes [WW-5263](https://issues.apache.org/jira/browse/WW-5263)

[WW-5263] Uses proper names for CSP, COOP and COEP interceptors

---

apps/showcase/src/test/java/it/org/apache/struts2/showcase/DispatcherResultTest.java
core/src/main/java/org/apache/struts2/dispatcher/PrepareOperations.java
core/src/main/java/org/apache/struts2/dispatcher/filter/StrutsExecuteFilter.java
core/src/main/java/org/apache/struts2/dispatcher/filter/StrutsPrepareFilter.java

Fixes [WW-5199](https://issues.apache.org/jira/browse/WW-5199)

WW-5199 Allow forwarding from/to actions

---

pom.xml

Closes [WW-5269](https://issues.apache.org/jira/browse/WW-5269)

[WW-5269] Upgrades Jackson to version 2.14.1

---

core/src/main/java/org/apache/struts2/components/Date.java
core/src/main/java/org/apache/struts2/components/date/SimpleDateFormatAdapter.java
core/src/test/java/org/apache/struts2/components/DateTest.java

Closes [WW-5272](https://issues.apache.org/jira/browse/WW-5272)

[WW-5272] Extends <s:date/> to support java.sql.Time

---

pom.xml

Closes [WW-5277](https://issues.apache.org/jira/browse/WW-5277)

[WW-5277] Upgrades Freemarker to version 2.3.32

---

core/src/main/java/org/apache/struts2/dispatcher/filter/StrutsPrepareAndExecuteFilter.java

Fixes [WW-5276](https://issues.apache.org/jira/browse/WW-5276)

[WW-5276] Cleans up also wrapper request to avoid resource leak and potential DoS attack

---

core/src/main/java/org/apache/struts2/action/CspSettingsAware.java
core/src/main/java/org/apache/struts2/interceptor/csp/CspInterceptor.java
core/src/main/java/org/apache/struts2/interceptor/csp/CspSettings.java
core/src/main/java/org/apache/struts2/interceptor/csp/DefaultCspSettings.java
core/src/test/java/org/apache/struts2/interceptor/CspInterceptorTest.java

Closes [WW-5275](https://issues.apache.org/jira/browse/WW-5275)

[WW-5275] Allows to provide a custom CspSettings per action

---

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java
core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java
core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessTest.java

WW-5268 Ability to exempt classes from package exclusions

---

core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/main/java/org/apache/struts2/config/entities/ConstantConfig.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java
core/src/main/resources/org/apache/struts2/default.properties
core/src/main/resources/org/apache/struts2/struts-messages.properties
core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java
plugins/pell-multipart/src/main/java/org/apache/struts2/dispatcher/multipart/PellMultiPartRequest.java

WW-5266 Implement struts.multipart.maxFileSize

---

apps/showcase/src/main/resources/struts-wait.xml
core/src/main/java/com/opensymphony/xwork2/config/providers/StrutsDefaultConfigurationProvider.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/main/java/org/apache/struts2/config/StrutsBeanSelectionProvider.java
core/src/main/java/org/apache/struts2/interceptor/ExecuteAndWaitInterceptor.java
core/src/main/java/org/apache/struts2/interceptor/exec/StrutsExecutorProvider.java
core/src/main/resources/struts-beans.xml

Closes [WW-5289](https://issues.apache.org/jira/browse/WW-5289)

[WW-5289] Fixes creating executor to avoid locking JVM on shutdown

---

core/src/main/java/org/apache/struts2/components/Date.java
core/src/test/java/org/apache/struts2/components/DateTest.java
core/src/test/java/org/apache/struts2/views/jsp/ui/DateTagTest.java

Closes [WW-5295](https://issues.apache.org/jira/browse/WW-5295)

[WW-5295] Adds support for java.time.LocalTime to <s:date/> tag

---

plugins/velocity/src/main/java/org/apache/struts2/views/velocity/StrutsVelocityContext.java

WW-5298 Clean up StrutsVelocityContext

---

core/src/main/java/com/opensymphony/xwork2/ActionChainResult.java

WW-5299 Clean up ActionChainResult

---

core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java

WW-5300 Make Dispatcher methods overridable

---

plugins/javatemplates/src/main/java/org/apache/struts2/views/java/simple/TextAreaHandler.java

Java templates plugin, add minlength and maxlength to textarea.

WW-5308 Java templates plugin, add minlength and maxlength to textarea.

---

core/src/main/java/com/opensymphony/xwork2/util/NamedVariablePatternMatcher.java
core/src/test/java/com/opensymphony/xwork2/util/NamedVariablePatternMatcherTest.java

Fixes [WW-5309](https://issues.apache.org/jira/browse/WW-5309)

[WW-5309] Supports patterns starting with variable

---

core/src/main/java/org/apache/struts2/components/ActionComponent.java
core/src/main/java/org/apache/struts2/components/Component.java
core/src/main/java/org/apache/struts2/components/Form.java
core/src/main/java/org/apache/struts2/views/jsp/StrutsBodyTagSupport.java
core/src/main/java/org/apache/struts2/views/jsp/TagUtils.java
core/src/test/java/org/apache/struts2/views/jsp/AbstractTagTest.java
core/src/test/java/org/apache/struts2/views/jsp/ActionTagTest.java
core/src/test/java/org/apache/struts2/views/jsp/AnchorTagTest.java
core/src/test/java/org/apache/struts2/views/jsp/URLTagTest.java
core/src/test/java/org/apache/struts2/views/jsp/ui/FormTagTest.java
core/src/test/java/org/apache/struts2/views/jsp/ui/TextfieldTest.java

Closes [WW-5261](https://issues.apache.org/jira/browse/WW-5261)

[WW-5261] Avoids creating ValueStack if no ActionContext is available

---

core/src/main/java/org/apache/struts2/components/ServletUrlRenderer.java
core/src/main/java/org/apache/struts2/result/ServletDispatcherResult.java
core/src/main/java/org/apache/struts2/url/QueryStringParser.java
core/src/main/java/org/apache/struts2/url/StrutsQueryStringParser.java
core/src/test/java/org/apache/struts2/url/StrutsQueryStringParserTest.java

Closes [WW-5310](https://issues.apache.org/jira/browse/WW-5310)

[WW-5310] Supports fragment in URL

---

pom.xml

Closes [WW-5315](https://issues.apache.org/jira/browse/WW-5315)

[WW-5315] Upgrades ASM to version 9.5

---

pom.xml

Closes [WW-5317](https://issues.apache.org/jira/browse/WW-5317)

[WW-5317] Upgrades log4j to version 2.20.0

---

pom.xml

Closes [WW-5318](https://issues.apache.org/jira/browse/WW-5318)

[WW-5318] Upgrades slf4j to version 2.0.7

---

pom.xml

Closes [WW-5325](https://issues.apache.org/jira/browse/WW-5325)

[WW-5325] Upgrades commons-lang3 to version 2.13.0

---

pom.xml

Closes [WW-5329](https://issues.apache.org/jira/browse/WW-5329)
Closes #721

[WW-5329] Upgrades xstream to version 1.4.20

---

core/src/main/java/org/apache/struts2/result/StreamResult.java

Update StreamResult.java - fix misspell

---

core/src/main/resources/struts-excluded-classes.xml
core/src/test/java/com/opensymphony/xwork2/ognl/OgnlUtilTest.java

Refs [WW-5327](https://issues.apache.org/jira/browse/WW-5327)
Refs #715

[WW-5327] Removes duplicated exclusion

---

.github/workflows/maven.yml
Jenkinsfile

Addresses warning:
> The version of Java (11.0.20) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17.
Read more [here](https://docs.sonarcloud.io/appendices/scanner-environment/)

Uses Java 17 to perform Code Quality check

---

core/src/main/java/org/apache/struts2/dispatcher/ApplicationMap.java
core/src/main/java/org/apache/struts2/dispatcher/RequestMap.java
core/src/main/java/org/apache/struts2/views/jsp/TagUtils.java
core/src/test/java/org/apache/struts2/dispatcher/ApplicationMapTest.java
core/src/test/java/org/apache/struts2/dispatcher/RequestMapTest.java
core/src/test/java/org/apache/struts2/interceptor/exec/StrutsBackgroundProcessTest.java
plugins/portlet/src/main/java/org/apache/struts2/portlet/PortletApplicationMap.java
plugins/portlet/src/main/java/org/apache/struts2/portlet/PortletRequestMap.java
plugins/portlet/src/main/java/org/apache/struts2/portlet/PortletSessionMap.java

Fixes [WW-5331](https://issues.apache.org/jira/browse/WW-5331)

[WW-5331] Uses proper signature of get()

---

core/src/main/java/com/opensymphony/xwork2/XWorkTestCase.java
core/src/main/java/org/apache/struts2/views/util/ContextUtil.java
plugins/json/pom.xml
plugins/pom.xml
plugins/rest/pom.xml
plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityManager.java
plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityStrutsUtil.java
plugins/velocity/src/test/java/org/apache/struts2/views/velocity/VelocityManagerTest.java
plugins/velocity/src/test/java/org/apache/struts2/views/velocity/result/VelocityResultTest.java
plugins/velocity/src/test/resources/tools.xml

WW-5334 Misc VelocityManager code cleanup

---

plugins/async/pom.xml

Drops duplicated dependency

---

core/src/main/java/com/opensymphony/xwork2/security/DefaultAcceptedPatternsChecker.java

WW-5348 Allow overriding of logging behaviour in DefaultAcceptedPatternsChecker

---

bundles/demo/pom.xml
core/pom.xml
plugins/osgi/pom.xml
plugins/tiles/pom.xml
plugins/tiles/src/main/java/org/apache/tiles/core/definition/digester/DigesterDefinitionsReader.java
pom.xml

Closes [WW-5347](https://issues.apache.org/jira/browse/WW-5347)

[WW-5347] Upgrades to commons-digester3 ver 3.2

---

plugins/sitemesh/pom.xml
pom.xml

Closes [WW-5344](https://issues.apache.org/jira/browse/WW-5344)

[WW-5344] Un-deprecates Sitemesh plugin and upgrades Sitmesh to ver 2.5.0

---

.github/workflows/maven.yml
core/src/test/java/com/opensymphony/xwork2/inject/ContainerImplTest.java
pom.xml

Add JDK 21 build

---

core/src/main/java/com/opensymphony/xwork2/security/DefaultExcludedPatternsChecker.java
core/src/test/java/com/opensymphony/xwork2/interceptor/ParametersInterceptorTest.java

WW-5354 Ensure ActionSupport fields are not parameter injectable

---

core/src/main/resources/struts-excluded-classes.xml

WW-5358 Expand exclusion lists

---

.asf.yaml
Jenkinsfile
core/src/main/java/com/opensymphony/xwork2/ognl/OgnlUtil.java
core/src/main/java/com/opensymphony/xwork2/ognl/OgnlValueStack.java
core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java
core/src/main/java/org/apache/struts2/StrutsConstants.java
core/src/test/java/com/opensymphony/xwork2/ognl/SecurityMemberAccessTest.java
plugins/velocity/src/main/java/org/apache/struts2/views/velocity/StrutsVelocityContext.java
plugins/velocity/src/test/java/org/apache/struts2/views/velocity/StrutsVelocityContextTest.java

Forward merging changes merged into master that are missing from `release/struts-7-0-x`.

2023-11-21 Forward merge master into release/7.0

---

apps/rest-showcase/pom.xml
apps/rest-showcase/src/test/java/it/org/apache/struts2/rest/example/GetOrdersTest.java
apps/rest-showcase/src/test/java/it/org/apache/struts2/rest/example/ListOrdersTest.java
apps/rest-showcase/src/test/java/it/org/apache/struts2/rest/example/PostOrderTest.java
apps/showcase/pom.xml
apps/showcase/src/test/java/it/org/apache/struts2/showcase/ActionChainingTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/ActionTagExampleTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/AsyncTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/CRUDTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/ComponentTagExampleTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/ConversionTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/DispatcherResultTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/ExecAndWaitTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/FileDownloadTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/FileUploadTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/ForwardTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/FreeMarkerManagerTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/StaticContentTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/UITagExampleTest.java
apps/showcase/src/test/java/it/org/apache/struts2/showcase/ValidationTest.java
pom.xml

Upgrades dependency and modifies tests

Upgrades Htmlunit to version 3.6.0

---

core/src/main/java/org/apache/struts2/action/CspReportAction.java

WW-5373 
change comment to match 204 http status and change parameter name statusCode to status.

[WW-5373] Update JavaDoc CspReportAction.java 

---

core/src/main/java/com/opensymphony/xwork2/util/MemberAccessValueStack.java

Closes [WW-5328](https://issues.apache.org/jira/browse/WW-5328)

[WW-5328] Removes deprecated setters

---

core/src/main/java/org/apache/struts2/interceptor/FileUploadInterceptor.java

Parameters related to file uploads, esp. `<xxx>FileName`, will be added only after existing parameters with identical names (case-insensitive) have been removed.
Since the 2-5-x class `HttpParameters` is not available yet, the fix is done very locally in class `FileUploadInterceptor`, i.e. other potential parameter pollutions are not covered (e.g. during the later execution of other interceptors that also update the parameters).
The fix has been tested using a [vulnerable test application](https://github.com/henrikplate/struts-demo).

Fix CVE-2023-50164 in 2-3-x

---

assembly/pom.xml
pom.xml

Closes [WW-5390](https://issues.apache.org/jira/browse/WW-5390)

[WW-5390] Fixes generating assemblies during release process

---

.github/workflows/scorecards-analysis.yaml
core/src/main/java/org/apache/struts2/components/File.java
core/src/site/resources/tags/file-attributes.html
plugins/config-browser/src/main/java/org/apache/struts2/config_browser/ShowBeansAction.java
plugins/javatemplates/src/main/java/org/apache/struts2/views/java/simple/FileHandler.java
plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/FileTest.java
plugins/rest/src/main/java/org/apache/struts2/rest/ContentTypeInterceptor.java
plugins/rest/src/test/java/org/apache/struts2/rest/ContentTypeInterceptorTest.java
plugins/sitemesh/src/main/java/org/apache/struts2/sitemesh/OldDecorator2NewStrutsVelocityDecorator.java
plugins/sitemesh/src/main/java/org/apache/struts2/sitemesh/VelocityDecoratorServlet.java
plugins/sitemesh/src/main/java/org/apache/struts2/sitemesh/VelocityPageFilter.java
plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityBeanSelectionProvider.java
plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityManager.java
plugins/velocity/src/main/java/org/apache/struts2/views/velocity/VelocityManagerInterface.java
plugins/velocity/src/main/java/org/apache/struts2/views/velocity/result/VelocityResult.java
plugins/velocity/src/main/java/org/apache/struts2/views/velocity/template/VelocityTemplateEngine.java
plugins/velocity/src/main/resources/struts-plugin.xml
pom.xml

Updates Struts 7 with the latest changes from the `master` branch

Merge master to 7-x-x 2024-02-16

---

core/src/main/java/com/opensymphony/xwork2/config/providers/XmlDocConfigurationProvider.java

WW-5364 Fix potential NPE in XmlDocConfigurationProvider

---

.asf.yaml

Based on [.asf.yaml](https://github.com/apache/infrastructure-asfyaml?tab=readme-ov-file#branchpro) instruction

Enables required review by codeowners

---

core/src/main/java/org/apache/struts2/interceptor/ParameterAware.java

WW-5251
--
Correction for #898

WW-5251 Fix deprecated interface method signature

---

plugins/tiles/pom.xml
plugins/tiles/src/main/java/org/apache/struts2/tiles/StrutsTilesContainerFactory.java
plugins/tiles/src/test/java/org/apache/struts2/tiles/StrutsTilesContainerFactoryTest.java

Closes [WW-5402](https://issues.apache.org/jira/browse/WW-5402)

WW-5402 Auto loads Tiles definitions from classpath

---

pom.xml

Closes [WW-5390](https://issues.apache.org/jira/browse/WW-5390)

WW-5390 Fixes creating assembly and attaching sources when preparing a new release

---

core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java

WW-5406
--
Fixing a minor bug I introduced with #910

WW-5406 Fix injection order issue for excluded patterns

---

pom.xml

Closes [WW-5420](https://issues.apache.org/jira/browse/WW-5420)

WW-5420 Upgrades commons-text to ver. 1.12.0

---

core/src/main/java/com/opensymphony/xwork2/ActionSupport.java
core/src/main/java/com/opensymphony/xwork2/DefaultLocaleProvider.java
core/src/main/java/com/opensymphony/xwork2/LocaleProvider.java
core/src/main/java/com/opensymphony/xwork2/validator/DelegatingValidatorContext.java
core/src/main/java/org/apache/struts2/interceptor/I18nInterceptor.java
core/src/test/java/com/opensymphony/xwork2/DefaultLocaleProviderTest.java
core/src/test/java/com/opensymphony/xwork2/LocaleProviderTest.java
core/src/test/java/org/apache/struts2/interceptor/I18nInterceptorTest.java

Fixes issue with trimable locale string
Closes [WW-5422](https://issues.apache.org/jira/browse/WW-5422)

WW-5422 Fixes support for trimable locale string in request

---

.asf.yaml

This option doesn't play with Silence Consensus

Disables required reviewers option

---

pom.xml

Closes [WW-5412](https://issues.apache.org/jira/browse/WW-5412)

[WW-5412] Upgrades struts-master to ver 15

---

plugins/cdi/pom.xml

Closes [WW-5438](https://issues.apache.org/jira/browse/WW-5438)

WW-5438 Fixes scope of Weld dependencies

---

plugins/jasperreports/pom.xml

WW-5441 Bump net.sf.jasperreports:jasperreports to 6.21.3

---

core/src/main/java/com/opensymphony/xwork2/ognl/SecurityMemberAccess.java

WW-5428 Stop further excessive logging in DevMode

---

pom.xml

WW-5443
--
Seeing lots of security warnings in IntelliJ about this dependency

WW-5443 Bump Spring dependencies to 5.3.37

---

apps/showcase/src/main/java/org/apache/struts2/showcase/fileupload/FileUploadAction.java
apps/showcase/src/main/webapp/WEB-INF/fileupload/upload-success.jsp
apps/showcase/src/test/java/it/org/apache/struts2/showcase/FileUploadTest.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/StrutsUploadedFile.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/UploadedFile.java
core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java
core/src/test/java/org/apache/struts2/interceptor/FileUploadInterceptorTest.java
plugins/pell-multipart/src/main/java/org/apache/struts2/dispatcher/multipart/PellMultiPartRequest.java

Refs [WW-5461](https://issues.apache.org/jira/browse/WW-5461)

WW-5461 Extends UploadedFile with inputName field

---

plugins/jfreechart/pom.xml
pom.xml

Merge master into 7.x.x 2024-09-10

---

.github/workflows/codeql.yml
.github/workflows/scorecards-analysis.yaml
core/src/main/java/org/apache/struts2/components/UIBean.java
core/src/test/java/org/apache/struts2/components/UIBeanTest.java
plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/AbstractTest.java
plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/HeadTest.java
plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/LinkTest.java
plugins/javatemplates/src/test/java/org/apache/struts2/views/java/simple/ScriptTest.java
plugins/tiles/pom.xml
pom.xml

Merge changes from the master branch into 7.x.x branch

Merge master branch into 7.x.x 2024-10-15

---

core/src/main/java/com/opensymphony/xwork2/Result.java
core/src/main/java/com/opensymphony/xwork2/factory/DefaultResultFactory.java
core/src/main/java/org/apache/struts2/ActionInvocation.java
core/src/main/java/org/apache/struts2/factory/StrutsResultFactory.java
core/src/main/java/org/apache/struts2/interceptor/ChainingInterceptor.java
core/src/main/java/org/apache/struts2/result/Result.java
core/src/test/java/com/opensymphony/xwork2/config/providers/ConfigurationProviderOgnlAllowlistTest.java

WW-3714
--
Resolves unusual issue compiling JSPs.

WW-3714 Move new Result class into result package

---

core/src/main/java/com/opensymphony/xwork2/Action.java
core/src/main/java/org/apache/struts2/ActionContext.java
core/src/main/java/org/apache/struts2/ActionInvocation.java
core/src/main/java/org/apache/struts2/ActionSupport.java
core/src/main/java/org/apache/struts2/action/Action.java
core/src/main/java/org/apache/struts2/result/Result.java
core/src/test/java/com/opensymphony/xwork2/config/providers/ConfigurationProviderOgnlAllowlistTest.java

WW-5459 Move new Action class into action package

---

plugins/dwr/README.md
plugins/dwr/pom.xml

WW-5484 Marks the DWR plugin as deprecated

---

.asf.yaml
.github/workflows/codeql.yml
.github/workflows/maven.yml
.github/workflows/scorecards-analysis.yaml
.github/workflows/sonar.yml
Jenkinsfile

PR prepares on renaming master branch into main. I'm going yo use [this approach](https://gist.github.com/danieldogeanu/739f88ea5312aaa23180e162e3ae89ab) to rename the branch.
Refs [WW-5405](https://issues.apache.org/jira/browse/WW-5405)

WW-5405 Prepares to rename master branch into main

---

.github/workflows/sonar.yml
README.md

WW-5405 Uses proper links to build statuses

---

core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java
core/src/main/java/org/apache/struts2/security/DefaultExcludedPatternsChecker.java
core/src/test/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequestTest.java
core/src/test/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequestTest.java
core/src/test/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequestTest.java
core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java
core/src/test/java/org/apache/struts2/security/DefaultExcludedPatternsCheckerTest.java

WW-5501 Excludes malicious names

---

pom.xml

WW-5503 Removes unused dependencies

---

core/src/main/java/com/opensymphony/xwork2/util/DebugUtils.java
core/src/test/java/org/apache/struts2/interceptor/parameter/ParametersInterceptorTest.java

WW-5498 Adds devMode errors as action messages to avoid breaking validation logic

---

core/src/main/java/org/apache/struts2/dispatcher/Dispatcher.java
core/src/test/java/org/apache/struts2/dispatcher/DispatcherTest.java

WW-5500 Extends pattern to validate multipart uploads

---

.github/dependabot.yml

Updates dependabot.yml

---

core/src/main/java/org/apache/struts2/interceptor/FileUploadInterceptor.java

The previous fix for CVE-2023-50164 (see #819) removed existing parameters if their names were equal (case-insensitive) to parameters related to file uploads, e.g. `uploadFileName` vs. `UploadFileName`.
However, the previous fix was incomplete, because it does not catch other OGNL expressions that could also be used by attackers to override the file name of upload actions, e.g. `top.uploadFileName`.
The fix proposed in this PR overcomes this problem by checking for containment rather than equality, i.e. any existing parameter that contains e.g. `uploadFileName` (case-insensitive) will be removed before adding a legitimate `UploadFileName`.
This check is only enabled for the two parameters related to file name and content-type. It is not enabled for the file itself, e.g. parameter …

Fix CVE-2024-53677 in 2-3-x

---

core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java
core/src/test/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequestTest.java
core/src/test/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequestTest.java
core/src/test/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequestTest.java
core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java

[WW-5501](https://issues.apache.org/jira/browse/WW-5501)
PR cherry-picks #1181

WW-5501 Only exclude malicious file names

---

core/src/main/java/org/apache/struts2/components/UIBean.java
core/src/main/java/org/apache/struts2/views/jsp/ui/AbstractUITag.java

WW-5510
--
This will be removed in the minor release, migrate to use native html tooltip support

WW-5510 Marks support for tooltips as deprecated

---

core/src/main/java/org/apache/struts2/components/UIBean.java
core/src/main/java/org/apache/struts2/views/jsp/TagUtils.java
core/src/test/java/org/apache/struts2/components/UIBeanTagTest.java

WW-5516
--
Cherry-pick of #1190

7.0: WW-5516 Fix TemplateDir and Theme fallback to Request/Session/Application attributes

---

core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java

Works great, except for the inject typo.

Fix inject

---

core/src/main/java/org/apache/struts2/dispatcher/AttributeMap.java
core/src/test/java/org/apache/struts2/dispatcher/AttributeMapTest.java

WW-5526 Fix AttributeMap NPE when PageContext has no request

---

core/src/main/java/org/apache/struts2/dispatcher/AttributeMap.java
core/src/test/java/org/apache/struts2/dispatcher/AttributeMapTest.java

6.7: WW-5526 Fix AttributeMap NPE when PageContext has no request

---

core/src/main/java/org/apache/struts2/dispatcher/multipart/AbstractMultiPartRequest.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaMultiPartRequest.java
core/src/main/java/org/apache/struts2/dispatcher/multipart/JakartaStreamMultiPartRequest.java
plugins/pell-multipart/src/main/java/org/apache/struts2/dispatcher/multipart/PellMultiPartRequest.java

WW-5501
Cherry picks changes from #1203

WW-5501 Ignores DMI related action field

---

core/src/site/resources/tags/combobox-attributes.html
core/src/site/resources/tags/password-attributes.html
core/src/site/resources/tags/textfield-attributes.html

WW-5529 Adds autogenerated files with updated desc

---

plugins/javatemplates/src/main/java/org/apache/struts2/views/java/simple/CheckboxListHandler.java

Swap cssStyle and style attributes to input from the label and add checkboxLabel class attribute to label. This matches ftl version.
See WW-5527.

WW-5527 Sync tag with main ftl template.

---

core/src/main/java/com/opensymphony/xwork2/ognl/OgnlReflectionContextFactory.java
core/src/main/java/com/opensymphony/xwork2/util/reflection/ReflectionContextFactory.java
plugins/config-browser/src/main/java/org/apache/struts2/config_browser/ShowValidatorAction.java

WW-5544 Marks ReflectionContextFactory as deprecated and uses ActionContext instead

---

core/src/main/java/org/apache/struts2/interceptor/AbstractFileUploadInterceptor.java
core/src/test/java/org/apache/struts2/interceptor/ActionFileUploadInterceptorTest.java

WW-5546 Fixes NPE when uploaded file is empty

---

.asf.yaml

more details can be found here https://github.com/apache/infrastructure-asfyaml/blob/main/README.md#branch-protection

Adjusts required checks to the new structure

---

apps/pom.xml
apps/rest-showcase/pom.xml
apps/showcase/pom.xml
assembly/pom.xml
bom/pom.xml
core/pom.xml
jakarta/pom.xml
jakarta/velocity-tools-jsp-jakarta/pom.xml
jakarta/velocity-tools-view-jakarta/pom.xml
parent/pom.xml
plugins/async/pom.xml
plugins/bean-validation/pom.xml
plugins/cdi/pom.xml
plugins/config-browser/pom.xml
plugins/convention/pom.xml
plugins/jasperreports/pom.xml
plugins/jasperreports7/pom.xml
plugins/javatemplates/pom.xml
plugins/jfreechart/pom.xml
plugins/json/pom.xml
plugins/junit/pom.xml
plugins/pom.xml
plugins/rest/pom.xml
plugins/spring/pom.xml
plugins/testng/pom.xml
plugins/tiles/pom.xml
plugins/velocity/pom.xml
plugins/xslt/pom.xml
pom.xml

I'm going to prepare another 7.1.1 release based on comments posted in dev list related to testing 7.1.0 build

Reverse merge changes from release/7.1.0

---

parent/pom.xml

WW-5574 Upgrades commons-logging to version 1.3.5
